// @generated by iguana. Do not edit manually.
// grammar FollowRestriction
// 
// S
//   = S_Plus_0
// 
// T
//   = Char !>> Char
// 
// Id
//   = Id_Plus_1 !>> Char
// 
// S_Plus_0
//   = S_Plus_0 WS Id
//   | Id
// 
// Id_Plus_1
//   = Id_Plus_1 Char
//   | Char
// 
// StartS
//   = WS start:S WS
// 
// StartT
//   = WS start:T WS
// 
// StartId
//   = WS start:Id WS
// 
// Char = ([a-z])
// WS = ([ ]*)
use std::cell::OnceCell;
use crate::{
    scanner::FollowRestrictionScanner, types::{EbnfKind, Nonterminal, Slot, Terminal},
};
use iguana_runtime::{
    descriptor::Descriptor, env::{Env, EnvId},
    gss::{GSSNode, PoppedElement},
    ids::{GssNodeId, NonterminalId, SlotId, TerminalId},
    input::Input, parser::{Parser, Stats, init_logger},
    record, scanner::Scanner,
    sppf::{IntermediateNode, NonterminalNode, SPPFNode, SPPFNodeId, Span, TerminalNode},
    utils::{inline_map::InlineMap, inline_vec::InlineVec},
};
#[cfg(feature = "debug-trace")]
use iguana_runtime::trace::TraceEvent;
use rustc_hash::FxHashMap;
use phf::phf_map;
pub const NONTERMINALS: [Nonterminal; 8] = [
    Nonterminal {
        name: "S",
        display: "S",
        kind: None,
    },
    Nonterminal {
        name: "T",
        display: "T",
        kind: None,
    },
    Nonterminal {
        name: "Id",
        display: "Id",
        kind: None,
    },
    Nonterminal {
        name: "S_Plus_0",
        display: "Id+",
        kind: Some(EbnfKind::Plus),
    },
    Nonterminal {
        name: "Id_Plus_1",
        display: "Char+",
        kind: Some(EbnfKind::Plus),
    },
    Nonterminal {
        name: "StartS",
        display: "StartS",
        kind: None,
    },
    Nonterminal {
        name: "StartT",
        display: "StartT",
        kind: None,
    },
    Nonterminal {
        name: "StartId",
        display: "StartId",
        kind: None,
    },
];
static NONTERMINAL_IDS: phf::Map<&'static str, NonterminalId> = phf_map! {
    "S" => NonterminalId(0), "T" => NonterminalId(1), "Id" => NonterminalId(2),
    "S_Plus_0" => NonterminalId(3), "Id_Plus_1" => NonterminalId(4), "StartS" =>
    NonterminalId(5), "StartT" => NonterminalId(6), "StartId" => NonterminalId(7)
};
pub const TERMINALS: [Terminal; 3] = [
    Terminal { name: "Char" },
    Terminal { name: "WS" },
    Terminal { name: "Epsilon" },
];
pub const SLOTS: [Slot; 29] = [
    Slot { display_name: "S : . Id+" },
    Slot { display_name: "S : Id+." },
    Slot {
        display_name: "T : . Char !>> Char",
    },
    Slot {
        display_name: "T : Char !>> Char.",
    },
    Slot {
        display_name: "Id : . Char+ !>> Char",
    },
    Slot {
        display_name: "Id : Char+ !>> Char.",
    },
    Slot {
        display_name: "Id+ : . Id+ WS Id",
    },
    Slot {
        display_name: "Id+ : Id+ . WS Id",
    },
    Slot {
        display_name: "Id+ : Id+ WS . Id",
    },
    Slot {
        display_name: "Id+ : Id+ WS Id.",
    },
    Slot { display_name: "Id+ : . Id" },
    Slot { display_name: "Id+ : Id." },
    Slot {
        display_name: "Char+ : . Char+ Char",
    },
    Slot {
        display_name: "Char+ : Char+ . Char",
    },
    Slot {
        display_name: "Char+ : Char+ Char.",
    },
    Slot {
        display_name: "Char+ : . Char",
    },
    Slot {
        display_name: "Char+ : Char.",
    },
    Slot {
        display_name: "StartS : . WS start:S WS",
    },
    Slot {
        display_name: "StartS : WS . start:S WS",
    },
    Slot {
        display_name: "StartS : WS start:S . WS",
    },
    Slot {
        display_name: "StartS : WS start:S WS.",
    },
    Slot {
        display_name: "StartT : . WS start:T WS",
    },
    Slot {
        display_name: "StartT : WS . start:T WS",
    },
    Slot {
        display_name: "StartT : WS start:T . WS",
    },
    Slot {
        display_name: "StartT : WS start:T WS.",
    },
    Slot {
        display_name: "StartId : . WS start:Id WS",
    },
    Slot {
        display_name: "StartId : WS . start:Id WS",
    },
    Slot {
        display_name: "StartId : WS start:Id . WS",
    },
    Slot {
        display_name: "StartId : WS start:Id WS.",
    },
];
impl<'i> Parser<'i> for FollowRestrictionParser<'i> {
    fn nonterminal_display_name(nonterminal_id: NonterminalId) -> &'static str {
        NONTERMINALS[nonterminal_id.index()].display
    }
    fn nonterminal_id(name: &str) -> Option<NonterminalId> {
        NONTERMINAL_IDS.get(name).copied()
    }
    fn terminal_name(terminal_id: TerminalId) -> &'static str {
        TERMINALS[terminal_id.index()].name
    }
    fn slot_name(slot_id: SlotId) -> &'static str {
        SLOTS[slot_id.index()].display_name
    }
    fn epsilon() -> TerminalId {
        TerminalId((TERMINALS.len() - 1) as u16)
    }
    fn execute(
        &mut self,
        input_index: u32,
        slot_id: SlotId,
        result: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        env: Option<EnvId>,
    ) {
        record!(self, ProcessingDescriptor, input_index, slot_id, result, gss_node_id);
        match slot_id {
            //S : . S_Plus_0
            SlotId(0) => {
                if let Some(right_child_id) = self.parse_s_plus_0_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    let new_node = right_child_id;
                    //S : S_Plus_0.
                    self.execute(j, SlotId(1), Some(new_node), gss_node_id, env);
                }
            }
            //S : S_Plus_0.
            SlotId(1) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(0), SlotId(1))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(1), popped_element);
                }
            }
            //T : . Char !>> Char
            SlotId(2) => {
                record!(self, MatchingTerminal, "Char", input_index);
                match self.scanner.match_token(TerminalId(0), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "Char", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(0), input_index, j);
                        if self.scanner.match_token(TerminalId(0), j).is_none() {
                            let new_node = right_child_id;
                            //T : Char !>> Char.
                            self.execute(j, SlotId(3), Some(new_node), gss_node_id, env);
                        }
                    }
                    None => {
                        record!(
                            self, MatchFailed, "Char", input_index, SlotId(2),
                            gss_node_id, result
                        );
                    }
                }
            }
            //T : Char !>> Char.
            SlotId(3) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(1), SlotId(3))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(3), popped_element);
                }
            }
            //Id : . Id_Plus_1 !>> Char
            SlotId(4) => {
                if let Some(right_child_id) = self.parse_id_plus_1_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    if !(self.scanner.match_token(TerminalId(0), j).is_none()) {
                        return;
                    }
                    let new_node = right_child_id;
                    //Id : Id_Plus_1 !>> Char.
                    self.execute(j, SlotId(5), Some(new_node), gss_node_id, env);
                }
            }
            //Id : Id_Plus_1 !>> Char.
            SlotId(5) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(2), SlotId(5))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(5), popped_element);
                }
            }
            //S_Plus_0 : . S_Plus_0 WS Id
            SlotId(6) => {
                if let Some(right_child_id) = self.parse_s_plus_0_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    let new_node = right_child_id;
                    //S_Plus_0 : S_Plus_0 . WS Id
                    self.execute(j, SlotId(7), Some(new_node), gss_node_id, env);
                }
            }
            //S_Plus_0 : S_Plus_0 . WS Id
            SlotId(7) => {
                record!(self, MatchingTerminal, "WS", input_index);
                match self.scanner.match_token(TerminalId(1), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "WS", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(1), input_index, j);
                        if let Some((j, new_node)) = self
                            .create_intermediate_node(result, right_child_id, SlotId(8))
                        {
                            //S_Plus_0 : S_Plus_0 WS . Id
                            self.execute(j, SlotId(8), Some(new_node), gss_node_id, env);
                        }
                    }
                    None => {
                        record!(
                            self, MatchFailed, "WS", input_index, SlotId(7), gss_node_id,
                            result
                        );
                    }
                }
            }
            //S_Plus_0 : S_Plus_0 WS . Id
            SlotId(8) => {
                if let Some(right_child_id) = self.parse_id_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    if let Some((j, new_node)) = self
                        .create_intermediate_node(result, right_child_id, SlotId(9))
                    {
                        //S_Plus_0 : S_Plus_0 WS Id.
                        self.execute(j, SlotId(9), Some(new_node), gss_node_id, env);
                    }
                }
            }
            //S_Plus_0 : S_Plus_0 WS Id.
            SlotId(9) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(3), SlotId(9))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(9), popped_element);
                }
            }
            //S_Plus_0 : . Id
            SlotId(10) => {
                if let Some(right_child_id) = self.parse_id_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    let new_node = right_child_id;
                    //S_Plus_0 : Id.
                    self.execute(j, SlotId(11), Some(new_node), gss_node_id, env);
                }
            }
            //S_Plus_0 : Id.
            SlotId(11) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(3), SlotId(11))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(11), popped_element);
                }
            }
            //Id_Plus_1 : . Id_Plus_1 Char
            SlotId(12) => {
                if let Some(right_child_id) = self.parse_id_plus_1_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    let new_node = right_child_id;
                    //Id_Plus_1 : Id_Plus_1 . Char
                    self.execute(j, SlotId(13), Some(new_node), gss_node_id, env);
                }
            }
            //Id_Plus_1 : Id_Plus_1 . Char
            SlotId(13) => {
                record!(self, MatchingTerminal, "Char", input_index);
                match self.scanner.match_token(TerminalId(0), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "Char", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(0), input_index, j);
                        if let Some((j, new_node)) = self
                            .create_intermediate_node(result, right_child_id, SlotId(14))
                        {
                            //Id_Plus_1 : Id_Plus_1 Char.
                            self.execute(
                                j,
                                SlotId(14),
                                Some(new_node),
                                gss_node_id,
                                env,
                            );
                        }
                    }
                    None => {
                        record!(
                            self, MatchFailed, "Char", input_index, SlotId(13),
                            gss_node_id, result
                        );
                    }
                }
            }
            //Id_Plus_1 : Id_Plus_1 Char.
            SlotId(14) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(4), SlotId(14))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(14), popped_element);
                }
            }
            //Id_Plus_1 : . Char
            SlotId(15) => {
                record!(self, MatchingTerminal, "Char", input_index);
                match self.scanner.match_token(TerminalId(0), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "Char", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(0), input_index, j);
                        let new_node = right_child_id;
                        //Id_Plus_1 : Char.
                        self.execute(j, SlotId(16), Some(new_node), gss_node_id, env);
                    }
                    None => {
                        record!(
                            self, MatchFailed, "Char", input_index, SlotId(15),
                            gss_node_id, result
                        );
                    }
                }
            }
            //Id_Plus_1 : Char.
            SlotId(16) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(4), SlotId(16))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(16), popped_element);
                }
            }
            //StartS : . WS start:S WS
            SlotId(17) => {
                record!(self, MatchingTerminal, "WS", input_index);
                match self.scanner.match_token(TerminalId(1), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "WS", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(1), input_index, j);
                        let new_node = right_child_id;
                        //StartS : WS . start:S WS
                        self.execute(j, SlotId(18), Some(new_node), gss_node_id, env);
                    }
                    None => {
                        record!(
                            self, MatchFailed, "WS", input_index, SlotId(17),
                            gss_node_id, result
                        );
                    }
                }
            }
            //StartS : WS . start:S WS
            SlotId(18) => {
                if let Some(right_child_id) = self.parse_s_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    if let Some((j, new_node)) = self
                        .create_intermediate_node(result, right_child_id, SlotId(19))
                    {
                        //StartS : WS start:S . WS
                        self.execute(j, SlotId(19), Some(new_node), gss_node_id, env);
                    }
                }
            }
            //StartS : WS start:S . WS
            SlotId(19) => {
                record!(self, MatchingTerminal, "WS", input_index);
                match self.scanner.match_token(TerminalId(1), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "WS", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(1), input_index, j);
                        if let Some((j, new_node)) = self
                            .create_intermediate_node(result, right_child_id, SlotId(20))
                        {
                            //StartS : WS start:S WS.
                            self.execute(
                                j,
                                SlotId(20),
                                Some(new_node),
                                gss_node_id,
                                env,
                            );
                        }
                    }
                    None => {
                        record!(
                            self, MatchFailed, "WS", input_index, SlotId(19),
                            gss_node_id, result
                        );
                    }
                }
            }
            //StartS : WS start:S WS.
            SlotId(20) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(5), SlotId(20))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(20), popped_element);
                }
            }
            //StartT : . WS start:T WS
            SlotId(21) => {
                record!(self, MatchingTerminal, "WS", input_index);
                match self.scanner.match_token(TerminalId(1), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "WS", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(1), input_index, j);
                        let new_node = right_child_id;
                        //StartT : WS . start:T WS
                        self.execute(j, SlotId(22), Some(new_node), gss_node_id, env);
                    }
                    None => {
                        record!(
                            self, MatchFailed, "WS", input_index, SlotId(21),
                            gss_node_id, result
                        );
                    }
                }
            }
            //StartT : WS . start:T WS
            SlotId(22) => {
                if let Some(right_child_id) = self.parse_t_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    if let Some((j, new_node)) = self
                        .create_intermediate_node(result, right_child_id, SlotId(23))
                    {
                        //StartT : WS start:T . WS
                        self.execute(j, SlotId(23), Some(new_node), gss_node_id, env);
                    }
                }
            }
            //StartT : WS start:T . WS
            SlotId(23) => {
                record!(self, MatchingTerminal, "WS", input_index);
                match self.scanner.match_token(TerminalId(1), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "WS", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(1), input_index, j);
                        if let Some((j, new_node)) = self
                            .create_intermediate_node(result, right_child_id, SlotId(24))
                        {
                            //StartT : WS start:T WS.
                            self.execute(
                                j,
                                SlotId(24),
                                Some(new_node),
                                gss_node_id,
                                env,
                            );
                        }
                    }
                    None => {
                        record!(
                            self, MatchFailed, "WS", input_index, SlotId(23),
                            gss_node_id, result
                        );
                    }
                }
            }
            //StartT : WS start:T WS.
            SlotId(24) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(6), SlotId(24))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(24), popped_element);
                }
            }
            //StartId : . WS start:Id WS
            SlotId(25) => {
                record!(self, MatchingTerminal, "WS", input_index);
                match self.scanner.match_token(TerminalId(1), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "WS", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(1), input_index, j);
                        let new_node = right_child_id;
                        //StartId : WS . start:Id WS
                        self.execute(j, SlotId(26), Some(new_node), gss_node_id, env);
                    }
                    None => {
                        record!(
                            self, MatchFailed, "WS", input_index, SlotId(25),
                            gss_node_id, result
                        );
                    }
                }
            }
            //StartId : WS . start:Id WS
            SlotId(26) => {
                if let Some(right_child_id) = self.parse_id_ll1(input_index) {
                    let j = self.sppf_node(right_child_id).right_extent();
                    if let Some((j, new_node)) = self
                        .create_intermediate_node(result, right_child_id, SlotId(27))
                    {
                        //StartId : WS start:Id . WS
                        self.execute(j, SlotId(27), Some(new_node), gss_node_id, env);
                    }
                }
            }
            //StartId : WS start:Id . WS
            SlotId(27) => {
                record!(self, MatchingTerminal, "WS", input_index);
                match self.scanner.match_token(TerminalId(1), input_index) {
                    Some(j) => {
                        record!(self, MatchSuccess, "WS", input_index, j);
                        let right_child_id = self
                            .get_or_create_terminal_node(TerminalId(1), input_index, j);
                        if let Some((j, new_node)) = self
                            .create_intermediate_node(result, right_child_id, SlotId(28))
                        {
                            //StartId : WS start:Id WS.
                            self.execute(
                                j,
                                SlotId(28),
                                Some(new_node),
                                gss_node_id,
                                env,
                            );
                        }
                    }
                    None => {
                        record!(
                            self, MatchFailed, "WS", input_index, SlotId(27),
                            gss_node_id, result
                        );
                    }
                }
            }
            //StartId : WS start:Id WS.
            SlotId(28) => {
                if let Some(nonterminal_node_id) = self
                    .create_nonterminal_node(result, NonterminalId(7), SlotId(28))
                {
                    let popped_element = PoppedElement {
                        nonterminal_node_id,
                        return_value: None,
                    };
                    self.pop(gss_node_id, SlotId(28), popped_element);
                }
            }
            _ => {
                panic!("Unknown grammar slot id: {slot_id}");
            }
        }
    }
    fn add_first_descriptors(
        &mut self,
        nonterminal_id: NonterminalId,
        input_index: u32,
        gss_node_id: GssNodeId,
        env: Option<EnvId>,
    ) {
        match nonterminal_id {
            //S : . S_Plus_0
            NonterminalId(0) => {
                self.add_first_descriptor(SlotId(0), input_index, gss_node_id, env);
            }
            //T : . Char !>> Char
            NonterminalId(1) => {
                self.add_first_descriptor(SlotId(2), input_index, gss_node_id, env);
            }
            //Id : . Id_Plus_1 !>> Char
            NonterminalId(2) => {
                self.add_first_descriptor(SlotId(4), input_index, gss_node_id, env);
            }
            //S_Plus_0
            NonterminalId(3) => {
                //S_Plus_0 : . S_Plus_0 WS Id
                self.add_first_descriptor(SlotId(6), input_index, gss_node_id, env);
                //S_Plus_0 : . Id
                self.add_first_descriptor(SlotId(10), input_index, gss_node_id, env);
            }
            //Id_Plus_1
            NonterminalId(4) => {
                //Id_Plus_1 : . Id_Plus_1 Char
                self.add_first_descriptor(SlotId(12), input_index, gss_node_id, env);
                //Id_Plus_1 : . Char
                self.add_first_descriptor(SlotId(15), input_index, gss_node_id, env);
            }
            //StartS : . WS start:S WS
            NonterminalId(5) => {
                self.add_first_descriptor(SlotId(17), input_index, gss_node_id, env);
            }
            //StartT : . WS start:T WS
            NonterminalId(6) => {
                self.add_first_descriptor(SlotId(21), input_index, gss_node_id, env);
            }
            //StartId : . WS start:Id WS
            NonterminalId(7) => {
                self.add_first_descriptor(SlotId(25), input_index, gss_node_id, env);
            }
            _ => {
                panic!("Unknown nonterminal id: {nonterminal_id}");
            }
        }
    }
    fn get_gss_node(
        &self,
        nonterminal_id: NonterminalId,
        input_index: u32,
    ) -> Option<GssNodeId> {
        let gss_nodes = &self.gss_nodes_index[nonterminal_id.index()];
        gss_nodes.iter().find(|(k, _)| *k == input_index).map(|x| x.1)
    }
    fn add_gss_node(
        &mut self,
        nonterminal_id: NonterminalId,
        input_index: u32,
        gss_node_id: GssNodeId,
    ) {
        let gss_nodes = &mut self.gss_nodes_index[nonterminal_id.index()];
        gss_nodes.push((input_index, gss_node_id));
    }
    fn new_gss_node(
        &mut self,
        nonterminal_id: NonterminalId,
        input_index: u32,
    ) -> GssNodeId {
        let gss_node_id = GssNodeId(self.gss_nodes.len() as u32);
        let gss_node = GSSNode::new(gss_node_id, nonterminal_id, input_index);
        record!(self, GSSNodeCreated, nonterminal_id, input_index);
        self.gss_nodes.push(gss_node);
        self.stats.gss_nodes_count += 1;
        gss_node_id
    }
    fn gss_node(&self, id: GssNodeId) -> &GSSNode {
        &self.gss_nodes[id.index()]
    }
    fn gss_node_mut(&mut self, id: GssNodeId) -> &mut GSSNode {
        self.gss_nodes.get_mut(id.index()).expect("GSS node id should be valid")
    }
    fn sppf_node(&self, id: SPPFNodeId) -> &SPPFNode {
        &self.sppf_nodes[id.index()]
    }
    fn sppf_node_mut(&mut self, id: SPPFNodeId) -> &mut SPPFNode {
        &mut self.sppf_nodes[id.index()]
    }
    fn add_descriptor(&mut self, descriptor: Descriptor) {
        record!(
            self, DescriptorAdded, descriptor.input_index, descriptor.slot_id, descriptor
            .sppf_node_id, descriptor.gss_node_id
        );
        self.stats_mut().descriptors_count += 1;
        self.descriptors.push(descriptor);
    }
    fn next_descriptor(&mut self) -> Option<Descriptor> {
        self.descriptors.pop()
    }
    fn add_terminal_node(&mut self, terminal_node: TerminalNode) -> SPPFNodeId {
        let terminal_node_id = SPPFNodeId(self.sppf_nodes.len() as u32);
        self.stats.terminal_nodes_count += 1;
        self.terminal_nodes_index[terminal_node.terminal_id.index()]
            .insert(terminal_node.span, terminal_node_id);
        record!(
            self, TerminalNodeCreated, terminal_node.terminal_id, terminal_node.span
        );
        self.sppf_nodes.push(SPPFNode::Terminal(terminal_node));
        terminal_node_id
    }
    fn add_nonterminal_node(&mut self, nonterminal_node: NonterminalNode) -> SPPFNodeId {
        let nonterminal_node_id = SPPFNodeId(self.sppf_nodes.len() as u32);
        self.stats.nonterminal_nodes_count += 1;
        self.nonterminal_nodes_index[nonterminal_node.nonterminal_id.index()]
            .insert(nonterminal_node.span, nonterminal_node_id);
        record!(
            self, NonterminalNodeCreated, nonterminal_node.nonterminal_id,
            nonterminal_node.span, nonterminal_node.child
        );
        self.sppf_nodes.push(SPPFNode::Nonterminal(nonterminal_node));
        nonterminal_node_id
    }
    fn add_intermediate_node(
        &mut self,
        intermediate_node: IntermediateNode,
    ) -> SPPFNodeId {
        let intermediate_node_id = SPPFNodeId(self.sppf_nodes.len() as u32);
        self.stats.intermediate_nodes_count += 1;
        self.intermediate_nodes_index[intermediate_node.slot_id.index()]
            .insert(intermediate_node.span, intermediate_node_id);
        record!(
            self, IntermediateNodeCreated, intermediate_node.slot_id, intermediate_node
            .span, intermediate_node.child.0, intermediate_node.child.1
        );
        self.sppf_nodes.push(SPPFNode::Intermediate(intermediate_node));
        intermediate_node_id
    }
    fn input(&self) -> &'i Input {
        self.scanner.input
    }
    fn stats(&self) -> &Stats {
        &self.stats
    }
    fn stats_mut(&mut self) -> &mut Stats {
        &mut self.stats
    }
    fn lookup_nonterminal_node(
        &self,
        nonterminal_id: NonterminalId,
        left_extent: u32,
        right_extent: u32,
    ) -> Option<SPPFNodeId> {
        let map = &self.nonterminal_nodes_index[nonterminal_id.index()];
        map.get(&Span::new(left_extent, right_extent)).copied()
    }
    fn lookup_intermediate_node(
        &self,
        slot_id: SlotId,
        left_extent: u32,
        right_extent: u32,
    ) -> Option<SPPFNodeId> {
        let map = &self.intermediate_nodes_index[slot_id.index()];
        map.get(&Span::new(left_extent, right_extent)).copied()
    }
    fn lookup_terminal_node(
        &self,
        terminal_id: TerminalId,
        left_extent: u32,
        right_extent: u32,
    ) -> Option<SPPFNodeId> {
        let map = &self.terminal_nodes_index[terminal_id.index()];
        map.get(&Span::new(left_extent, right_extent)).copied()
    }
    fn gss_nodes(&self) -> impl Iterator<Item = &GSSNode> {
        self.gss_nodes.iter()
    }
    fn add_intermediate_node_child(
        &mut self,
        node: SPPFNodeId,
        child1: SPPFNodeId,
        child2: SPPFNodeId,
    ) {
        self.intermediate_nodes_children.push((node, (child1, child2)));
    }
    fn add_nonterminal_node_child(&mut self, node: SPPFNodeId, child: SPPFNodeId) {
        self.nonterminal_nodes_children.push((node, child));
    }
    fn intermediate_nodes_children_map(
        &self,
    ) -> &FxHashMap<SPPFNodeId, Vec<(SPPFNodeId, SPPFNodeId)>> {
        self.intermediate_nodes_children_map
            .get_or_init(|| {
                let mut map: FxHashMap<SPPFNodeId, Vec<(SPPFNodeId, SPPFNodeId)>> = FxHashMap::default();
                for (k, v) in &self.intermediate_nodes_children {
                    map.entry(*k).or_default().push(*v);
                }
                map
            })
    }
    fn nonterminal_nodes_children_map(&self) -> &FxHashMap<SPPFNodeId, Vec<SPPFNodeId>> {
        self.nonterminal_nodes_children_map
            .get_or_init(|| {
                let mut map: FxHashMap<SPPFNodeId, Vec<SPPFNodeId>> = FxHashMap::default();
                for (k, v) in &self.nonterminal_nodes_children {
                    map.entry(*k).or_default().push(*v);
                }
                map
            })
    }
    #[cfg(feature = "debug-trace")]
    fn add_trace_event(&mut self, event: TraceEvent) {
        if let Some(trace_events) = &mut self.trace_events {
            trace_events.push(event);
        }
    }
    fn start_nonterminal(&self) -> NonterminalId {
        self.start_nonterminal
    }
    fn new_env(&mut self) -> (EnvId, &mut Env) {
        let id = EnvId(self.envs.len() as u32);
        self.envs.push(Env::default());
        (id, &mut self.envs[id.index()])
    }
    fn lookup(&self, name: &str, env_id: EnvId) -> i32 {
        let env = &self.envs[env_id.index()];
        env.get(name)
    }
    fn clone_env(&mut self, source: EnvId) -> (EnvId, &mut Env) {
        let bindings = self.envs[source.0 as usize].bindings.clone();
        let (new_id, new_env) = self.new_env();
        new_env.bindings = bindings;
        (new_id, new_env)
    }
    fn post_conditions(
        &self,
        slot: SlotId,
        left_extent: u32,
        right_extent: u32,
    ) -> bool {
        match slot {
            SlotId(5) => self.scanner.match_token(TerminalId(0), right_extent).is_none(),
            _ => true,
        }
    }
}
pub struct FollowRestrictionParser<'i> {
    start_nonterminal: NonterminalId,
    scanner: FollowRestrictionScanner<'i>,
    descriptors: Vec<Descriptor>,
    gss_nodes: Vec<GSSNode>,
    //A vector from nonterminal_ids to a tuple (input_index, gss_node_id)
    gss_nodes_index: [Vec<(u32, GssNodeId)>; 8],
    sppf_nodes: Vec<SPPFNode>,
    stats: Stats,
    nonterminal_nodes_index: [InlineMap<Span, SPPFNodeId>; 8],
    intermediate_nodes_index: [InlineMap<Span, SPPFNodeId>; 29],
    terminal_nodes_index: [InlineMap<Span, SPPFNodeId>; 3],
    intermediate_nodes_children: Vec<(SPPFNodeId, (SPPFNodeId, SPPFNodeId))>,
    intermediate_nodes_children_map: OnceCell<
        FxHashMap<SPPFNodeId, Vec<(SPPFNodeId, SPPFNodeId)>>,
    >,
    nonterminal_nodes_children: Vec<(SPPFNodeId, SPPFNodeId)>,
    nonterminal_nodes_children_map: OnceCell<FxHashMap<SPPFNodeId, Vec<SPPFNodeId>>>,
    envs: Vec<Env>,
    #[cfg(feature = "debug-trace")]
    pub trace_events: Option<Vec<TraceEvent>>,
}
impl<'i> FollowRestrictionParser<'i> {
    pub fn new(input: &'i Input, start_nonterminal: NonterminalId) -> Self {
        init_logger();
        Self {
            start_nonterminal,
            scanner: FollowRestrictionScanner::new(input),
            gss_nodes_index: [const { vec![] }; 8],
            descriptors: vec![],
            gss_nodes: vec![],
            sppf_nodes: vec![],
            nonterminal_nodes_index: [const { InlineMap::Empty }; 8],
            intermediate_nodes_index: [const { InlineMap::Empty }; 29],
            terminal_nodes_index: [const { InlineMap::Empty }; 3],
            stats: Stats::default(),
            intermediate_nodes_children: vec![],
            intermediate_nodes_children_map: OnceCell::new(),
            nonterminal_nodes_children: vec![],
            nonterminal_nodes_children_map: OnceCell::new(),
            envs: vec![],
            #[cfg(feature = "debug-trace")]
            trace_events: None,
        }
    }
    fn create_s(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(0), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn create_t(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(1), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn create_id(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(2), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn create_s_plus_0(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(3), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn create_id_plus_1(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(4), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn create_start_s(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(5), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn create_start_t(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(6), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn create_start_id(
        &mut self,
        sppf_node_id: Option<SPPFNodeId>,
        gss_node_id: GssNodeId,
        return_slot: SlotId,
        env: Option<EnvId>,
    ) {
        self.create(NonterminalId(7), sppf_node_id, gss_node_id, return_slot, env);
    }
    fn parse_s_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        if self.scanner.match_token(TerminalId(0), i).is_some() {
            let mut j = i;
            let right_child_id = {
                let start = j;
                let node = self.parse_s_plus_0_ll1(start)?;
                let end = self.sppf_node(node).right_extent();
                j = end;
                node
            };
            let left_extent = self.sppf_node(right_child_id).left_extent();
            let mut current = right_child_id;
            return Some(
                self
                    .get_or_create_nonterminal_node(
                        NonterminalId(0),
                        SlotId(1),
                        left_extent,
                        j,
                        current,
                        false,
                    )
                    .unwrap(),
            );
        }
        None
    }
    fn parse_t_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        if self.scanner.match_token(TerminalId(0), i).is_some() {
            let mut j = i;
            let right_child_id = {
                let start = j;
                let end = self.scanner.match_token(TerminalId(0), start)?;
                if !(self.scanner.match_token(TerminalId(0), end).is_none()) {
                    return None;
                }
                let node = self.get_or_create_terminal_node(TerminalId(0), start, end);
                j = end;
                node
            };
            let left_extent = self.sppf_node(right_child_id).left_extent();
            let mut current = right_child_id;
            return Some(
                self
                    .get_or_create_nonterminal_node(
                        NonterminalId(1),
                        SlotId(3),
                        left_extent,
                        j,
                        current,
                        false,
                    )
                    .unwrap(),
            );
        }
        None
    }
    fn parse_id_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        if self.scanner.match_token(TerminalId(0), i).is_some() {
            let mut j = i;
            let right_child_id = {
                let start = j;
                let node = self.parse_id_plus_1_ll1(start)?;
                let end = self.sppf_node(node).right_extent();
                j = end;
                if !(self.scanner.match_token(TerminalId(0), end).is_none()) {
                    return None;
                }
                node
            };
            let left_extent = self.sppf_node(right_child_id).left_extent();
            let mut current = right_child_id;
            return Some(
                self
                    .get_or_create_nonterminal_node(
                        NonterminalId(2),
                        SlotId(5),
                        left_extent,
                        j,
                        current,
                        false,
                    )
                    .unwrap(),
            );
        }
        None
    }
    fn parse_s_plus_0_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        let mut j = i;
        let (body_node, body_end) = (self
            .parse_id_ll1(j)
            .map(|node| {
                let end = self.sppf_node(node).right_extent();
                (node, end)
            }))?;
        j = body_end;
        let left_extent = i;
        let mut current = self
            .get_or_create_nonterminal_node(
                NonterminalId(3),
                SlotId(11),
                left_extent,
                j,
                body_node,
                false,
            )
            .unwrap();
        loop {
            let Some((node_0, pos_0)) = self
                .scanner
                .match_token(TerminalId(1), j)
                .map(|end| {
                    (self.get_or_create_terminal_node(TerminalId(1), j, end), end)
                }) else {
                break;
            };
            let Some((node_1, pos_1)) = self
                .parse_id_ll1(pos_0)
                .map(|node| {
                    let end = self.sppf_node(node).right_extent();
                    (node, end)
                }) else {
                break;
            };
            j = pos_1;
            current = self
                .get_or_create_intermediate_node(
                    SlotId(8),
                    left_extent,
                    pos_0,
                    current,
                    node_0,
                    false,
                )
                .unwrap();
            current = self
                .get_or_create_intermediate_node(
                    SlotId(9),
                    left_extent,
                    pos_1,
                    current,
                    node_1,
                    false,
                )
                .unwrap();
            current = self
                .get_or_create_nonterminal_node(
                    NonterminalId(3),
                    SlotId(9),
                    left_extent,
                    j,
                    current,
                    false,
                )
                .unwrap();
        }
        Some(current)
    }
    fn parse_id_plus_1_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        let mut j = i;
        let (body_node, body_end) = (self
            .scanner
            .match_token(TerminalId(0), j)
            .map(|end| {
                (self.get_or_create_terminal_node(TerminalId(0), j, end), end)
            }))?;
        j = body_end;
        let left_extent = i;
        let mut current = self
            .get_or_create_nonterminal_node(
                NonterminalId(4),
                SlotId(16),
                left_extent,
                j,
                body_node,
                false,
            )
            .unwrap();
        loop {
            let Some((node_0, pos_0)) = self
                .scanner
                .match_token(TerminalId(0), j)
                .map(|end| {
                    (self.get_or_create_terminal_node(TerminalId(0), j, end), end)
                }) else {
                break;
            };
            j = pos_0;
            current = self
                .get_or_create_intermediate_node(
                    SlotId(14),
                    left_extent,
                    pos_0,
                    current,
                    node_0,
                    false,
                )
                .unwrap();
            current = self
                .get_or_create_nonterminal_node(
                    NonterminalId(4),
                    SlotId(14),
                    left_extent,
                    j,
                    current,
                    false,
                )
                .unwrap();
        }
        Some(current)
    }
    fn parse_start_s_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        if self.scanner.match_token(TerminalId(0), i).is_some()
            || self.scanner.match_token(TerminalId(1), i).is_some()
        {
            let mut j = i;
            let right_child_id = {
                let start = j;
                let end = self.scanner.match_token(TerminalId(1), start)?;
                let node = self.get_or_create_terminal_node(TerminalId(1), start, end);
                j = end;
                node
            };
            let left_extent = self.sppf_node(right_child_id).left_extent();
            let mut current = right_child_id;
            let right_child_id = {
                let start = j;
                let node = self.parse_s_ll1(start)?;
                let end = self.sppf_node(node).right_extent();
                j = end;
                node
            };
            current = self
                .get_or_create_intermediate_node(
                    SlotId(19),
                    left_extent,
                    j,
                    current,
                    right_child_id,
                    false,
                )
                .unwrap();
            let right_child_id = {
                let start = j;
                let end = self.scanner.match_token(TerminalId(1), start)?;
                let node = self.get_or_create_terminal_node(TerminalId(1), start, end);
                j = end;
                node
            };
            current = self
                .get_or_create_intermediate_node(
                    SlotId(20),
                    left_extent,
                    j,
                    current,
                    right_child_id,
                    false,
                )
                .unwrap();
            return Some(
                self
                    .get_or_create_nonterminal_node(
                        NonterminalId(5),
                        SlotId(20),
                        left_extent,
                        j,
                        current,
                        false,
                    )
                    .unwrap(),
            );
        }
        None
    }
    fn parse_start_t_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        if self.scanner.match_token(TerminalId(0), i).is_some()
            || self.scanner.match_token(TerminalId(1), i).is_some()
        {
            let mut j = i;
            let right_child_id = {
                let start = j;
                let end = self.scanner.match_token(TerminalId(1), start)?;
                let node = self.get_or_create_terminal_node(TerminalId(1), start, end);
                j = end;
                node
            };
            let left_extent = self.sppf_node(right_child_id).left_extent();
            let mut current = right_child_id;
            let right_child_id = {
                let start = j;
                let node = self.parse_t_ll1(start)?;
                let end = self.sppf_node(node).right_extent();
                j = end;
                node
            };
            current = self
                .get_or_create_intermediate_node(
                    SlotId(23),
                    left_extent,
                    j,
                    current,
                    right_child_id,
                    false,
                )
                .unwrap();
            let right_child_id = {
                let start = j;
                let end = self.scanner.match_token(TerminalId(1), start)?;
                let node = self.get_or_create_terminal_node(TerminalId(1), start, end);
                j = end;
                node
            };
            current = self
                .get_or_create_intermediate_node(
                    SlotId(24),
                    left_extent,
                    j,
                    current,
                    right_child_id,
                    false,
                )
                .unwrap();
            return Some(
                self
                    .get_or_create_nonterminal_node(
                        NonterminalId(6),
                        SlotId(24),
                        left_extent,
                        j,
                        current,
                        false,
                    )
                    .unwrap(),
            );
        }
        None
    }
    fn parse_start_id_ll1(&mut self, i: u32) -> Option<SPPFNodeId> {
        if self.scanner.match_token(TerminalId(0), i).is_some()
            || self.scanner.match_token(TerminalId(1), i).is_some()
        {
            let mut j = i;
            let right_child_id = {
                let start = j;
                let end = self.scanner.match_token(TerminalId(1), start)?;
                let node = self.get_or_create_terminal_node(TerminalId(1), start, end);
                j = end;
                node
            };
            let left_extent = self.sppf_node(right_child_id).left_extent();
            let mut current = right_child_id;
            let right_child_id = {
                let start = j;
                let node = self.parse_id_ll1(start)?;
                let end = self.sppf_node(node).right_extent();
                j = end;
                node
            };
            current = self
                .get_or_create_intermediate_node(
                    SlotId(27),
                    left_extent,
                    j,
                    current,
                    right_child_id,
                    false,
                )
                .unwrap();
            let right_child_id = {
                let start = j;
                let end = self.scanner.match_token(TerminalId(1), start)?;
                let node = self.get_or_create_terminal_node(TerminalId(1), start, end);
                j = end;
                node
            };
            current = self
                .get_or_create_intermediate_node(
                    SlotId(28),
                    left_extent,
                    j,
                    current,
                    right_child_id,
                    false,
                )
                .unwrap();
            return Some(
                self
                    .get_or_create_nonterminal_node(
                        NonterminalId(7),
                        SlotId(28),
                        left_extent,
                        j,
                        current,
                        false,
                    )
                    .unwrap(),
            );
        }
        None
    }
}

