// @generated by iguana. Do not edit manually.

use iguana_runtime::{
    grammar::{Grammar, Nonterminal, Slot, Terminal},
    ids::{NonterminalId, TerminalId},
    scanner::TerminalSet,
};
pub const TYPE: NonterminalId = NonterminalId(0);
pub const START_E: NonterminalId = NonterminalId(1);
pub const START_TYPE: NonterminalId = NonterminalId(2);
pub const E: NonterminalId = NonterminalId(3);
pub struct AmbRootNestedGrammar;
impl Grammar for AmbRootNestedGrammar {
    const NAME: &'static str = "AmbRootNested";
    const NONTERMINALS: &'static [Nonterminal] = &[
        Nonterminal {
            name: "Type",
            display_name: "Type",
        },
        Nonterminal {
            name: "StartE",
            display_name: "E(0)",
        },
        Nonterminal {
            name: "StartType",
            display_name: "Type",
        },
        Nonterminal {
            name: "E",
            display_name: "E",
        },
    ];
    const DISPLAY_ORDER: &'static [&'static str] = &["E", "Type"];
    const TERMINALS: &'static [Terminal] = &[
        Terminal { name: "Id" },
        Terminal { name: "WS" },
        Terminal { name: "\"(\"" },
        Terminal { name: "\")\"" },
        Terminal { name: "\"-\"" },
        Terminal { name: "Epsilon" },
        Terminal { name: "EOF" },
    ];
    const SLOTS: &'static [Slot] = &[
        Slot {
            display_name: "Type : . Id",
        },
        Slot {
            display_name: "Type : Id.",
        },
        Slot {
            display_name: "E(0) : . WS start:E(0) WS",
        },
        Slot {
            display_name: "E(0) : WS . start:E(0) WS",
        },
        Slot {
            display_name: "E(0) : WS start:E(0) . WS",
        },
        Slot {
            display_name: "E(0) : WS start:E(0) WS.",
        },
        Slot {
            display_name: "Type : . WS start:Type WS",
        },
        Slot {
            display_name: "Type : WS . start:Type WS",
        },
        Slot {
            display_name: "Type : WS start:Type . WS",
        },
        Slot {
            display_name: "Type : WS start:Type WS.",
        },
        Slot {
            display_name: "E : . \"(\" WS Type WS \")\" WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"(\" . WS Type WS \")\" WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"(\" WS . Type WS \")\" WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"(\" WS Type . WS \")\" WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"(\" WS Type WS . \")\" WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"(\" WS Type WS \")\" . WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"(\" WS Type WS \")\" WS . E(2) return 2",
        },
        Slot {
            display_name: "E : \"(\" WS Type WS \")\" WS E(2) . return 2",
        },
        Slot {
            display_name: "E : \"(\" WS Type WS \")\" WS E(2) return 2.",
        },
        Slot {
            display_name: "E : . \"-\" WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"-\" . WS E(2) return 2",
        },
        Slot {
            display_name: "E : \"-\" WS . E(2) return 2",
        },
        Slot {
            display_name: "E : \"-\" WS E(2) . return 2",
        },
        Slot {
            display_name: "E : \"-\" WS E(2) return 2.",
        },
        Slot {
            display_name: "E : . [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] . l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) . [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] . WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS . \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" . WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS . E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) . return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1.",
        },
        Slot {
            display_name: "E : . [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] . l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) . [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] . WS \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS . \"-\" WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" . WS E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS . E(1) return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) . return 1",
        },
        Slot {
            display_name: "E : [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS \"-\" WS E(1) return 1.",
        },
        Slot {
            display_name: "E : . \"(\" WS E(0) WS \")\" return 0",
        },
        Slot {
            display_name: "E : \"(\" . WS E(0) WS \")\" return 0",
        },
        Slot {
            display_name: "E : \"(\" WS . E(0) WS \")\" return 0",
        },
        Slot {
            display_name: "E : \"(\" WS E(0) . WS \")\" return 0",
        },
        Slot {
            display_name: "E : \"(\" WS E(0) WS . \")\" return 0",
        },
        Slot {
            display_name: "E : \"(\" WS E(0) WS \")\" . return 0",
        },
        Slot {
            display_name: "E : \"(\" WS E(0) WS \")\" return 0.",
        },
        Slot {
            display_name: "E : . Id return 0",
        },
        Slot {
            display_name: "E : Id . return 0",
        },
        Slot {
            display_name: "E : Id return 0.",
        },
    ];
    const LAYOUT_NAME: Option<&'static str> = Some("WS");
    const LAYOUT_TERMINALS: &'static [TerminalId] = &[TerminalId(1)];
    fn nonterminal_id(name: &str) -> Option<NonterminalId> {
        match name {
            "Type" => Some(TYPE),
            "StartE" => Some(START_E),
            "StartType" => Some(START_TYPE),
            "E" => Some(E),
            _ => None,
        }
    }
}
// E { WS, ")", "-", EOF }
pub static FOLLOW_SET_E: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(1), TerminalId(3), TerminalId(4), TerminalId(6)],
};
// E { Id, "(", "-" }
pub static FIRST_SET_E: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(0), TerminalId(2), TerminalId(4)],
};
// E(p: i32) : . "(" WS Type WS ")" WS E(2) return 2 { "(" }
pub static FIRST_SET_E_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(2)],
};
// E(p: i32) : . "-" WS E(2) return 2 { "-" }
pub static FIRST_SET_E_ALT1: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[TerminalId(4)],
};
// E(p: i32) : . [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS "-" WS E(1) return 1 {
// Id, "(", "-" }
pub static FIRST_SET_E_ALT2: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(0), TerminalId(2), TerminalId(4)],
};
// E(p: i32) : . [1 >= p] l_pr=E(p) [(l_pr == 0) || (l_pr >= 1)] WS "-" WS E(1) return 1 {
// Id, "(", "-" }
pub static FIRST_SET_E_ALT3: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(0), TerminalId(2), TerminalId(4)],
};
// E(p: i32) : . "(" WS E(0) WS ")" return 0 { "(" }
pub static FIRST_SET_E_ALT4: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(2)],
};
// E(p: i32) : . Id return 0 { Id }
pub static FIRST_SET_E_ALT5: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(0)],
};
// Type { WS, ")", EOF }
pub static FOLLOW_SET_TYPE: TerminalSet = TerminalSet {
    id: 5,
    terminals: &[TerminalId(1), TerminalId(3), TerminalId(6)],
};
// Type { Id }
pub static FIRST_SET_TYPE: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(0)],
};
// Type : . Id { Id }
pub static FIRST_SET_TYPE_ALT0: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(0)],
};
// StartE { EOF }
pub static FOLLOW_SET_START_E: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[TerminalId(6)],
};
// StartE { Id, WS, "(", "-" }
pub static FIRST_SET_START_E: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[TerminalId(0), TerminalId(1), TerminalId(2), TerminalId(4)],
};
// StartE : . WS start:E(0) WS { Id, WS, "(", "-" }
pub static FIRST_SET_START_E_ALT0: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(0), TerminalId(1), TerminalId(2), TerminalId(4)],
};
// StartType { EOF }
pub static FOLLOW_SET_START_TYPE: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[TerminalId(6)],
};
// StartType { Id, WS }
pub static FIRST_SET_START_TYPE: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(0), TerminalId(1)],
};
// StartType : . WS start:Type WS { Id, WS }
pub static FIRST_SET_START_TYPE_ALT0: TerminalSet = TerminalSet {
    id: 8,
    terminals: &[TerminalId(0), TerminalId(1)],
};
