#!/bin/sh
cargo fmt --check --all && cargo fmt --manifest-path tests/Cargo.toml --check --all || {
    echo
    echo "Run: cargo fmt --all && cargo fmt --manifest-path tests/Cargo.toml --all"
    exit 1
}
