// @generated by iguana. Do not edit manually.

pub mod grammar_data;
pub mod parser;
pub mod parse_tree;
pub mod scanner;
pub mod types;
use std::error::Error;
use std::fmt::{self, Display, Formatter};
use std::time::Duration;
use iguana_runtime::{
    input::Input, parse_tree::ParseContext, parser::{ParseResult, Parser},
};
use parse_tree::*;
use parser::MultipleExceptParser;
#[derive(Debug)]
pub struct ParseError {
    pub line: u32,
    pub column: u32,
    pub message: String,
}
impl Display for ParseError {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(
            f, "Parse error at line {}, column {}: {}", self.line, self.column, self
            .message
        )
    }
}
impl Error for ParseError {}
pub struct ParseSuccess<T> {
    pub tree: T,
    pub parse_duration: Duration,
    pub tree_construction_duration: Duration,
}
pub fn parse_syntax_identifier<'a>(
    input: &Input,
    ctx: &'a ParseContext,
) -> std::result::Result<ParseSuccess<&'a SyntaxIdentifier>, ParseError> {
    let mut parser = MultipleExceptParser::new(input, grammar_data::SYNTAX_IDENTIFIER);
    match parser.run() {
        ParseResult::Success(success) => {
            let parse_duration = success.duration;
            let tree_start = std::time::Instant::now();
            let parse_tree_builder = MultipleExceptParseTreeBuilder::new(ctx);
            let tree = parse_tree::create_parse_tree_syntax_identifier(
                success.sppf_node_id,
                &parser,
                &parse_tree_builder,
            );
            let tree_construction_duration = tree_start.elapsed();
            Ok(ParseSuccess {
                tree,
                parse_duration,
                tree_construction_duration,
            })
        }
        ParseResult::Failure(error) => {
            let (line, column, message) = parser.format_error(&error);
            Err(ParseError {
                line,
                column,
                message,
            })
        }
    }
}
pub fn parse_lexical_identifier<'a>(
    input: &Input,
    ctx: &'a ParseContext,
) -> std::result::Result<ParseSuccess<&'a LexicalIdentifier>, ParseError> {
    let mut parser = MultipleExceptParser::new(input, grammar_data::LEXICAL_IDENTIFIER);
    match parser.run() {
        ParseResult::Success(success) => {
            let parse_duration = success.duration;
            let tree_start = std::time::Instant::now();
            let parse_tree_builder = MultipleExceptParseTreeBuilder::new(ctx);
            let tree = parse_tree::create_parse_tree_lexical_identifier(
                success.sppf_node_id,
                &parser,
                &parse_tree_builder,
            );
            let tree_construction_duration = tree_start.elapsed();
            Ok(ParseSuccess {
                tree,
                parse_duration,
                tree_construction_duration,
            })
        }
        ParseResult::Failure(error) => {
            let (line, column, message) = parser.format_error(&error);
            Err(ParseError {
                line,
                column,
                message,
            })
        }
    }
}

