// @generated by iguana. Do not edit manually.
// You may distribute this file under any license of your choice. It embeds
// fragments of iguana's GPL-licensed source, and iguana grants an additional
// permission (GPL v3 section 7) that waives the GPL for generated parsers.
// Full text: https://github.com/iguana-parser/iguana-rs/blob/main/iguana-compiler/LICENSE-GPL

use crate::parser::AltSeqParser;
use iguana_runtime::{
    ids::{NonterminalId, SlotId, TerminalId},
    input::Span,
    parse_tree::{
        Bump, NodeKind, OneOrMany, Origin, ParseTreeBuilder, ParseTreeNode, SexprOptions,
        visit_sppf,
    },
    sppf::{NonterminalNode, SPPFNodeId, TerminalNode},
};
use std::vec::IntoIter;
#[derive(Debug, Clone, Copy)]
pub enum TokenKind {
    // Hex
    T0,
    // "a"
    T1,
    // "b"
    T2,
    // "c"
    T3,
    // "d"
    T4,
    // "e"
    T5,
    // "f"
    T6,
}
impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            TokenKind::T0 => "Hex",
            TokenKind::T1 => "\"a\"",
            TokenKind::T2 => "\"b\"",
            TokenKind::T3 => "\"c\"",
            TokenKind::T4 => "\"d\"",
            TokenKind::T5 => "\"e\"",
            TokenKind::T6 => "\"f\"",
        }
    }
}
#[derive(Debug)]
pub struct Start<T, L> {
    pub before: L,
    pub node: T,
    pub after: L,
    pub span: Span,
}
#[derive(Debug, Clone, Copy)]
pub enum ParseTree<'a> {
    S(&'a S<'a>),
    A(&'a A<'a>),
    B(&'a B<'a>),
    C(&'a C<'a>),
    D(&'a D<'a>),
    E(&'a E<'a>),
    F(&'a F<'a>),
    // (A B | C)
    Alt0(&'a Alt0<'a>),
    // (D | E F)
    Alt1(&'a Alt1<'a>),
    // S
    StartS(&'a Start<&'a S<'a>, ()>),
    // A
    StartA(&'a Start<&'a A<'a>, ()>),
    // B
    StartB(&'a Start<&'a B<'a>, ()>),
    // C
    StartC(&'a Start<&'a C<'a>, ()>),
    // D
    StartD(&'a Start<&'a D<'a>, ()>),
    // E
    StartE(&'a Start<&'a E<'a>, ()>),
    // F
    StartF(&'a Start<&'a F<'a>, ()>),
    Token(Token),
}
impl<'a> ParseTree<'a> {
    pub fn children(&self) -> Vec<ParseTree<'a>> {
        match self {
            ParseTree::S(s) => (0..s.child_count()).filter_map(|i| s.child(i)).collect(),
            ParseTree::A(a) => (0..a.child_count()).filter_map(|i| a.child(i)).collect(),
            ParseTree::B(b) => (0..b.child_count()).filter_map(|i| b.child(i)).collect(),
            ParseTree::C(c) => (0..c.child_count()).filter_map(|i| c.child(i)).collect(),
            ParseTree::D(d) => (0..d.child_count()).filter_map(|i| d.child(i)).collect(),
            ParseTree::E(e) => (0..e.child_count()).filter_map(|i| e.child(i)).collect(),
            ParseTree::F(f) => (0..f.child_count()).filter_map(|i| f.child(i)).collect(),
            ParseTree::Alt0(alt_0) => (0..alt_0.child_count())
                .filter_map(|i| alt_0.child(i))
                .collect(),
            ParseTree::Alt1(alt_1) => (0..alt_1.child_count())
                .filter_map(|i| alt_1.child(i))
                .collect(),
            ParseTree::StartS(start_s) => (0..start_s.child_count())
                .filter_map(|i| start_s.child(i))
                .collect(),
            ParseTree::StartA(start_a) => (0..start_a.child_count())
                .filter_map(|i| start_a.child(i))
                .collect(),
            ParseTree::StartB(start_b) => (0..start_b.child_count())
                .filter_map(|i| start_b.child(i))
                .collect(),
            ParseTree::StartC(start_c) => (0..start_c.child_count())
                .filter_map(|i| start_c.child(i))
                .collect(),
            ParseTree::StartD(start_d) => (0..start_d.child_count())
                .filter_map(|i| start_d.child(i))
                .collect(),
            ParseTree::StartE(start_e) => (0..start_e.child_count())
                .filter_map(|i| start_e.child(i))
                .collect(),
            ParseTree::StartF(start_f) => (0..start_f.child_count())
                .filter_map(|i| start_f.child(i))
                .collect(),
            ParseTree::Token(_) => vec![],
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            ParseTree::S(s) => s.display_name(),
            ParseTree::A(a) => a.display_name(),
            ParseTree::B(b) => b.display_name(),
            ParseTree::C(c) => c.display_name(),
            ParseTree::D(d) => d.display_name(),
            ParseTree::E(e) => e.display_name(),
            ParseTree::F(f) => f.display_name(),
            ParseTree::Alt0(alt_0) => alt_0.display_name(),
            ParseTree::Alt1(alt_1) => alt_1.display_name(),
            ParseTree::StartS(start_s) => start_s.display_name(),
            ParseTree::StartA(start_a) => start_a.display_name(),
            ParseTree::StartB(start_b) => start_b.display_name(),
            ParseTree::StartC(start_c) => start_c.display_name(),
            ParseTree::StartD(start_d) => start_d.display_name(),
            ParseTree::StartE(start_e) => start_e.display_name(),
            ParseTree::StartF(start_f) => start_f.display_name(),
            ParseTree::Token(token) => token.kind.name(),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            ParseTree::S(s) => s.child_count(),
            ParseTree::A(a) => a.child_count(),
            ParseTree::B(b) => b.child_count(),
            ParseTree::C(c) => c.child_count(),
            ParseTree::D(d) => d.child_count(),
            ParseTree::E(e) => e.child_count(),
            ParseTree::F(f) => f.child_count(),
            ParseTree::Alt0(alt_0) => alt_0.child_count(),
            ParseTree::Alt1(alt_1) => alt_1.child_count(),
            ParseTree::StartS(start_s) => start_s.child_count(),
            ParseTree::StartA(start_a) => start_a.child_count(),
            ParseTree::StartB(start_b) => start_b.child_count(),
            ParseTree::StartC(start_c) => start_c.child_count(),
            ParseTree::StartD(start_d) => start_d.child_count(),
            ParseTree::StartE(start_e) => start_e.child_count(),
            ParseTree::StartF(start_f) => start_f.child_count(),
            ParseTree::Token(_) => 0,
        }
    }
    pub fn span(&self) -> Span {
        match self {
            ParseTree::S(s) => s.span(),
            ParseTree::A(a) => a.span(),
            ParseTree::B(b) => b.span(),
            ParseTree::C(c) => c.span(),
            ParseTree::D(d) => d.span(),
            ParseTree::E(e) => e.span(),
            ParseTree::F(f) => f.span(),
            ParseTree::Alt0(alt_0) => alt_0.span(),
            ParseTree::Alt1(alt_1) => alt_1.span(),
            ParseTree::StartS(start_s) => start_s.span(),
            ParseTree::StartA(start_a) => start_a.span(),
            ParseTree::StartB(start_b) => start_b.span(),
            ParseTree::StartC(start_c) => start_c.span(),
            ParseTree::StartD(start_d) => start_d.span(),
            ParseTree::StartE(start_e) => start_e.span(),
            ParseTree::StartF(start_f) => start_f.span(),
            ParseTree::Token(token) => token.span(),
        }
    }
    ///True when this node is an ambiguity cluster (any `*::Amb` variant). The
    ///uniform way to detect ambiguity without matching each nonterminal's enum.
    pub fn is_amb(&self) -> bool {
        match self {
            ParseTree::S(s) => matches!(s, S::Amb(_)),
            ParseTree::A(a) => matches!(a, A::Amb(_)),
            ParseTree::B(b) => matches!(b, B::Amb(_)),
            ParseTree::C(c) => matches!(c, C::Amb(_)),
            ParseTree::D(d) => matches!(d, D::Amb(_)),
            ParseTree::E(e) => matches!(e, E::Amb(_)),
            ParseTree::F(f) => matches!(f, F::Amb(_)),
            ParseTree::Alt0(alt_0) => matches!(alt_0, Alt0::Amb(_)),
            ParseTree::Alt1(alt_1) => matches!(alt_1, Alt1::Amb(_)),
            ParseTree::StartS(_) => false,
            ParseTree::StartA(_) => false,
            ParseTree::StartB(_) => false,
            ParseTree::StartC(_) => false,
            ParseTree::StartD(_) => false,
            ParseTree::StartE(_) => false,
            ParseTree::StartF(_) => false,
            ParseTree::Token(_) => false,
        }
    }
    ///Pointer identity of the underlying node, or `None` for tokens (by-value
    ///leaves that are never shared). Two parse trees with the same `node_id` are
    ///the same allocation, i.e. a node shared between parents in the ambiguity DAG.
    pub fn node_id(&self) -> Option<usize> {
        match self {
            ParseTree::S(s) => Some(*s as *const _ as usize),
            ParseTree::A(a) => Some(*a as *const _ as usize),
            ParseTree::B(b) => Some(*b as *const _ as usize),
            ParseTree::C(c) => Some(*c as *const _ as usize),
            ParseTree::D(d) => Some(*d as *const _ as usize),
            ParseTree::E(e) => Some(*e as *const _ as usize),
            ParseTree::F(f) => Some(*f as *const _ as usize),
            ParseTree::Alt0(alt_0) => Some(*alt_0 as *const _ as usize),
            ParseTree::Alt1(alt_1) => Some(*alt_1 as *const _ as usize),
            ParseTree::StartS(start_s) => Some(*start_s as *const _ as usize),
            ParseTree::StartA(start_a) => Some(*start_a as *const _ as usize),
            ParseTree::StartB(start_b) => Some(*start_b as *const _ as usize),
            ParseTree::StartC(start_c) => Some(*start_c as *const _ as usize),
            ParseTree::StartD(start_d) => Some(*start_d as *const _ as usize),
            ParseTree::StartE(start_e) => Some(*start_e as *const _ as usize),
            ParseTree::StartF(start_f) => Some(*start_f as *const _ as usize),
            ParseTree::Token(_) => None,
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        match self {
            ParseTree::S(s) => s.origin(),
            ParseTree::A(a) => a.origin(),
            ParseTree::B(b) => b.origin(),
            ParseTree::C(c) => c.origin(),
            ParseTree::D(d) => d.origin(),
            ParseTree::E(e) => e.origin(),
            ParseTree::F(f) => f.origin(),
            ParseTree::Alt0(alt_0) => alt_0.origin(),
            ParseTree::Alt1(alt_1) => alt_1.origin(),
            ParseTree::StartS(start_s) => start_s.origin(),
            ParseTree::StartA(start_a) => start_a.origin(),
            ParseTree::StartB(start_b) => start_b.origin(),
            ParseTree::StartC(start_c) => start_c.origin(),
            ParseTree::StartD(start_d) => start_d.origin(),
            ParseTree::StartE(start_e) => start_e.origin(),
            ParseTree::StartF(start_f) => start_f.origin(),
            ParseTree::Token(_) => None,
        }
    }
    fn unwrap_s(self) -> &'a S<'a> {
        match self {
            ParseTree::S(s) => s,
            _ => panic!(),
        }
    }
    fn unwrap_a(self) -> &'a A<'a> {
        match self {
            ParseTree::A(a) => a,
            _ => panic!(),
        }
    }
    fn unwrap_b(self) -> &'a B<'a> {
        match self {
            ParseTree::B(b) => b,
            _ => panic!(),
        }
    }
    fn unwrap_c(self) -> &'a C<'a> {
        match self {
            ParseTree::C(c) => c,
            _ => panic!(),
        }
    }
    fn unwrap_d(self) -> &'a D<'a> {
        match self {
            ParseTree::D(d) => d,
            _ => panic!(),
        }
    }
    fn unwrap_e(self) -> &'a E<'a> {
        match self {
            ParseTree::E(e) => e,
            _ => panic!(),
        }
    }
    fn unwrap_f(self) -> &'a F<'a> {
        match self {
            ParseTree::F(f) => f,
            _ => panic!(),
        }
    }
    fn unwrap_alt_0(self) -> &'a Alt0<'a> {
        match self {
            ParseTree::Alt0(alt_0) => alt_0,
            _ => panic!(),
        }
    }
    fn unwrap_alt_1(self) -> &'a Alt1<'a> {
        match self {
            ParseTree::Alt1(alt_1) => alt_1,
            _ => panic!(),
        }
    }
    fn unwrap_start_s(self) -> &'a Start<&'a S<'a>, ()> {
        match self {
            ParseTree::StartS(start_s) => start_s,
            _ => panic!(),
        }
    }
    fn unwrap_start_a(self) -> &'a Start<&'a A<'a>, ()> {
        match self {
            ParseTree::StartA(start_a) => start_a,
            _ => panic!(),
        }
    }
    fn unwrap_start_b(self) -> &'a Start<&'a B<'a>, ()> {
        match self {
            ParseTree::StartB(start_b) => start_b,
            _ => panic!(),
        }
    }
    fn unwrap_start_c(self) -> &'a Start<&'a C<'a>, ()> {
        match self {
            ParseTree::StartC(start_c) => start_c,
            _ => panic!(),
        }
    }
    fn unwrap_start_d(self) -> &'a Start<&'a D<'a>, ()> {
        match self {
            ParseTree::StartD(start_d) => start_d,
            _ => panic!(),
        }
    }
    fn unwrap_start_e(self) -> &'a Start<&'a E<'a>, ()> {
        match self {
            ParseTree::StartE(start_e) => start_e,
            _ => panic!(),
        }
    }
    fn unwrap_start_f(self) -> &'a Start<&'a F<'a>, ()> {
        match self {
            ParseTree::StartF(start_f) => start_f,
            _ => panic!(),
        }
    }
    fn unwrap_token(self) -> Token {
        match self {
            ParseTree::Token(t) => t,
            _ => panic!(),
        }
    }
}
pub trait ListNode<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>>;
}
pub trait OptNode {
    type Inner;
    fn value(&self) -> Option<&Self::Inner>;
}
// S = (A B | C) (D | E F) Hex
#[derive(Debug)]
pub enum S<'a> {
    Alt0 {
        alt_0: &'a Alt0<'a>,
        alt_1: &'a Alt1<'a>,
        hex: Token,
        span: Span,
    },
    Amb(&'a [&'a S<'a>]),
}
// A = "a"
#[derive(Debug)]
pub enum A<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a A<'a>]),
}
// B = "b"
#[derive(Debug)]
pub enum B<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a B<'a>]),
}
// C = "c"
#[derive(Debug)]
pub enum C<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a C<'a>]),
}
// D = "d"
#[derive(Debug)]
pub enum D<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a D<'a>]),
}
// E = "e"
#[derive(Debug)]
pub enum E<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a E<'a>]),
}
// F = "f"
#[derive(Debug)]
pub enum F<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a F<'a>]),
}
// (A B | C)
#[derive(Debug)]
pub enum Alt0<'a> {
    // Alt_0 = A B
    Alt0 {
        a: &'a A<'a>,
        b: &'a B<'a>,
        span: Span,
    },
    // Alt_0 = C
    Alt1 {
        c: &'a C<'a>,
        span: Span,
    },
    Amb(&'a [&'a Alt0<'a>]),
}
// (D | E F)
#[derive(Debug)]
pub enum Alt1<'a> {
    // Alt_1 = D
    Alt0 {
        d: &'a D<'a>,
        span: Span,
    },
    // Alt_1 = E F
    Alt1 {
        e: &'a E<'a>,
        f: &'a F<'a>,
        span: Span,
    },
    Amb(&'a [&'a Alt1<'a>]),
}
impl<'a> S<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::S(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            S::Alt0 {
                alt_0, alt_1, hex, ..
            } => match index {
                0 => Some(ParseTree::Alt0(alt_0)),
                1 => Some(ParseTree::Alt1(alt_1)),
                2 => Some(ParseTree::Token(*hex)),
                _ => None,
            },
            S::Amb(alts) => alts.get(index).copied().map(ParseTree::S),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            S::Alt0 { .. } => 3usize,
            S::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            S::Alt0 { span, .. } => *span,
            S::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            S::Amb(_) => "Amb",
            _ => "S",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn alt_0(&self) -> &'a Alt0<'a> {
        match self {
            S::Alt0 { alt_0, .. } => alt_0,
            S::Amb(_) => panic!("S is ambiguous"),
        }
    }
    pub fn alt_1(&self) -> &'a Alt1<'a> {
        match self {
            S::Alt0 { alt_1, .. } => alt_1,
            S::Amb(_) => panic!("S is ambiguous"),
        }
    }
    pub fn hex(&self) -> Token {
        match self {
            S::Alt0 { hex, .. } => *hex,
            S::Amb(_) => panic!("S is ambiguous"),
        }
    }
}
impl<'a> A<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::A(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            A::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            A::Amb(alts) => alts.get(index).copied().map(ParseTree::A),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            A::Alt0 { .. } => 1usize,
            A::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            A::Alt0 { span, .. } => *span,
            A::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            A::Amb(_) => "Amb",
            _ => "A",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            A::Alt0 { lit_0, .. } => *lit_0,
            A::Amb(_) => panic!("A is ambiguous"),
        }
    }
}
impl<'a> B<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::B(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            B::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            B::Amb(alts) => alts.get(index).copied().map(ParseTree::B),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            B::Alt0 { .. } => 1usize,
            B::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            B::Alt0 { span, .. } => *span,
            B::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            B::Amb(_) => "Amb",
            _ => "B",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            B::Alt0 { lit_0, .. } => *lit_0,
            B::Amb(_) => panic!("B is ambiguous"),
        }
    }
}
impl<'a> C<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::C(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            C::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            C::Amb(alts) => alts.get(index).copied().map(ParseTree::C),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            C::Alt0 { .. } => 1usize,
            C::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            C::Alt0 { span, .. } => *span,
            C::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            C::Amb(_) => "Amb",
            _ => "C",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            C::Alt0 { lit_0, .. } => *lit_0,
            C::Amb(_) => panic!("C is ambiguous"),
        }
    }
}
impl<'a> D<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::D(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            D::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            D::Amb(alts) => alts.get(index).copied().map(ParseTree::D),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            D::Alt0 { .. } => 1usize,
            D::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            D::Alt0 { span, .. } => *span,
            D::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            D::Amb(_) => "Amb",
            _ => "D",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            D::Alt0 { lit_0, .. } => *lit_0,
            D::Amb(_) => panic!("D is ambiguous"),
        }
    }
}
impl<'a> E<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::E(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            E::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            E::Amb(alts) => alts.get(index).copied().map(ParseTree::E),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            E::Alt0 { .. } => 1usize,
            E::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            E::Alt0 { span, .. } => *span,
            E::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            E::Amb(_) => "Amb",
            _ => "E",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            E::Alt0 { lit_0, .. } => *lit_0,
            E::Amb(_) => panic!("E is ambiguous"),
        }
    }
}
impl<'a> F<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::F(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            F::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            F::Amb(alts) => alts.get(index).copied().map(ParseTree::F),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            F::Alt0 { .. } => 1usize,
            F::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            F::Alt0 { span, .. } => *span,
            F::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            F::Amb(_) => "Amb",
            _ => "F",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            F::Alt0 { lit_0, .. } => *lit_0,
            F::Amb(_) => panic!("F is ambiguous"),
        }
    }
}
impl<'a> Alt0<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Alt0(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            Alt0::Alt0 { a, b, .. } => match index {
                0 => Some(ParseTree::A(a)),
                1 => Some(ParseTree::B(b)),
                _ => None,
            },
            Alt0::Alt1 { c, .. } => match index {
                0 => Some(ParseTree::C(c)),
                _ => None,
            },
            Alt0::Amb(alts) => alts.get(index).copied().map(ParseTree::Alt0),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            Alt0::Alt0 { .. } => 2usize,
            Alt0::Alt1 { .. } => 1usize,
            Alt0::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            Alt0::Alt0 { span, .. } => *span,
            Alt0::Alt1 { span, .. } => *span,
            Alt0::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            Alt0::Amb(_) => "Amb",
            _ => "(A B | C)",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        match self {
            Alt0::Amb(_) => None,
            _ => Some(Origin::Alt),
        }
    }
}
impl<'a> Alt1<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Alt1(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            Alt1::Alt0 { d, .. } => match index {
                0 => Some(ParseTree::D(d)),
                _ => None,
            },
            Alt1::Alt1 { e, f, .. } => match index {
                0 => Some(ParseTree::E(e)),
                1 => Some(ParseTree::F(f)),
                _ => None,
            },
            Alt1::Amb(alts) => alts.get(index).copied().map(ParseTree::Alt1),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            Alt1::Alt0 { .. } => 1usize,
            Alt1::Alt1 { .. } => 2usize,
            Alt1::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            Alt1::Alt0 { span, .. } => *span,
            Alt1::Alt1 { span, .. } => *span,
            Alt1::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            Alt1::Amb(_) => "Amb",
            _ => "(D | E F)",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        match self {
            Alt1::Amb(_) => None,
            _ => Some(Origin::Alt),
        }
    }
}
impl<'a> Start<&'a S<'a>, ()> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartS(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::S(self.node)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Start"
    }
    pub fn origin(&self) -> Option<Origin> {
        Some(Origin::Start)
    }
}
impl<'a> Start<&'a A<'a>, ()> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartA(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::A(self.node)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Start"
    }
    pub fn origin(&self) -> Option<Origin> {
        Some(Origin::Start)
    }
}
impl<'a> Start<&'a B<'a>, ()> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartB(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::B(self.node)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Start"
    }
    pub fn origin(&self) -> Option<Origin> {
        Some(Origin::Start)
    }
}
impl<'a> Start<&'a C<'a>, ()> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartC(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::C(self.node)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Start"
    }
    pub fn origin(&self) -> Option<Origin> {
        Some(Origin::Start)
    }
}
impl<'a> Start<&'a D<'a>, ()> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartD(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::D(self.node)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Start"
    }
    pub fn origin(&self) -> Option<Origin> {
        Some(Origin::Start)
    }
}
impl<'a> Start<&'a E<'a>, ()> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartE(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::E(self.node)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Start"
    }
    pub fn origin(&self) -> Option<Origin> {
        Some(Origin::Start)
    }
}
impl<'a> Start<&'a F<'a>, ()> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartF(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::F(self.node)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Start"
    }
    pub fn origin(&self) -> Option<Origin> {
        Some(Origin::Start)
    }
}
impl<'a> Alt0<'a> {
    pub fn as_a(&self) -> Option<&A<'_>> {
        match self {
            Alt0::Alt0 { a, .. } => Some(a),
            _ => None,
        }
    }
    pub fn as_c(&self) -> Option<&C<'_>> {
        match self {
            Alt0::Alt1 { c, .. } => Some(c),
            _ => None,
        }
    }
}
impl<'a> Alt1<'a> {
    pub fn as_d(&self) -> Option<&D<'_>> {
        match self {
            Alt1::Alt0 { d, .. } => Some(d),
            _ => None,
        }
    }
    pub fn as_e(&self) -> Option<&E<'_>> {
        match self {
            Alt1::Alt1 { e, .. } => Some(e),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy)]
pub struct Token {
    pub kind: TokenKind,
    span: Span,
}
impl Token {
    pub fn as_parse_tree<'a>(&self) -> ParseTree<'a> {
        ParseTree::Token(*self)
    }
    pub fn span(&self) -> Span {
        self.span
    }
}
fn token_kind(terminal_id: TerminalId) -> TokenKind {
    match terminal_id {
        // Hex
        TerminalId(0) => TokenKind::T0,
        // "a"
        TerminalId(1) => TokenKind::T1,
        // "b"
        TerminalId(2) => TokenKind::T2,
        // "c"
        TerminalId(3) => TokenKind::T3,
        // "d"
        TerminalId(4) => TokenKind::T4,
        // "e"
        TerminalId(5) => TokenKind::T5,
        // "f"
        TerminalId(6) => TokenKind::T6,
        _ => unreachable!("Unknown TerminalId: {:?}", terminal_id),
    }
}
pub struct AltSeqParseTreeBuilder<'a> {
    pub arena: &'a Bump,
}
impl<'a> AltSeqParseTreeBuilder<'a> {
    pub fn new(tree_arena: &'a Bump) -> Self {
        Self { arena: tree_arena }
    }
}
impl<'a> ParseTreeBuilder<ParseTree<'a>> for AltSeqParseTreeBuilder<'a> {
    fn new_nonterminal_node(
        &self,
        nonterminal_node: &NonterminalNode,
        children: OneOrMany<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match nonterminal_node.nonterminal_id {
            // S
            NonterminalId(0) => match nonterminal_node.return_slot {
                // S : (A B | C) (D | E F) Hex.
                SlotId(3) => {
                    let [alt_0, alt_1, hex] = children.into_array::<3usize>();
                    ParseTree::S(self.arena.alloc(S::Alt0 {
                        alt_0: alt_0.unwrap_alt_0(),
                        alt_1: alt_1.unwrap_alt_1(),
                        hex: hex.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // A
            NonterminalId(1) => match nonterminal_node.return_slot {
                // A : "a".
                SlotId(5) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::A(self.arena.alloc(A::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // B
            NonterminalId(2) => match nonterminal_node.return_slot {
                // B : "b".
                SlotId(7) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::B(self.arena.alloc(B::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // C
            NonterminalId(3) => match nonterminal_node.return_slot {
                // C : "c".
                SlotId(9) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::C(self.arena.alloc(C::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // D
            NonterminalId(4) => match nonterminal_node.return_slot {
                // D : "d".
                SlotId(11) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::D(self.arena.alloc(D::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // E
            NonterminalId(5) => match nonterminal_node.return_slot {
                // E : "e".
                SlotId(13) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::E(self.arena.alloc(E::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // F
            NonterminalId(6) => match nonterminal_node.return_slot {
                // F : "f".
                SlotId(15) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::F(self.arena.alloc(F::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Alt_0
            NonterminalId(7) => match nonterminal_node.return_slot {
                // (A B | C) : A B.
                SlotId(18) => {
                    let [a, b] = children.into_array::<2usize>();
                    ParseTree::Alt0(self.arena.alloc(Alt0::Alt0 {
                        a: a.unwrap_a(),
                        b: b.unwrap_b(),
                        span: nonterminal_node.span,
                    }))
                }
                // (A B | C) : C.
                SlotId(20) => {
                    let [c] = children.into_array::<1usize>();
                    ParseTree::Alt0(self.arena.alloc(Alt0::Alt1 {
                        c: c.unwrap_c(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Alt_1
            NonterminalId(8) => match nonterminal_node.return_slot {
                // (D | E F) : D.
                SlotId(22) => {
                    let [d] = children.into_array::<1usize>();
                    ParseTree::Alt1(self.arena.alloc(Alt1::Alt0 {
                        d: d.unwrap_d(),
                        span: nonterminal_node.span,
                    }))
                }
                // (D | E F) : E F.
                SlotId(25) => {
                    let [e, f] = children.into_array::<2usize>();
                    ParseTree::Alt1(self.arena.alloc(Alt1::Alt1 {
                        e: e.unwrap_e(),
                        f: f.unwrap_f(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartS
            NonterminalId(9) => match nonterminal_node.return_slot {
                // S : start:S.
                SlotId(27) => {
                    let [start] = children.into_array::<1usize>();
                    ParseTree::StartS(self.arena.alloc(Start {
                        before: (),
                        node: start.unwrap_s(),
                        after: (),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartA
            NonterminalId(10) => match nonterminal_node.return_slot {
                // A : start:A.
                SlotId(29) => {
                    let [start] = children.into_array::<1usize>();
                    ParseTree::StartA(self.arena.alloc(Start {
                        before: (),
                        node: start.unwrap_a(),
                        after: (),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartB
            NonterminalId(11) => match nonterminal_node.return_slot {
                // B : start:B.
                SlotId(31) => {
                    let [start] = children.into_array::<1usize>();
                    ParseTree::StartB(self.arena.alloc(Start {
                        before: (),
                        node: start.unwrap_b(),
                        after: (),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartC
            NonterminalId(12) => match nonterminal_node.return_slot {
                // C : start:C.
                SlotId(33) => {
                    let [start] = children.into_array::<1usize>();
                    ParseTree::StartC(self.arena.alloc(Start {
                        before: (),
                        node: start.unwrap_c(),
                        after: (),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartD
            NonterminalId(13) => match nonterminal_node.return_slot {
                // D : start:D.
                SlotId(35) => {
                    let [start] = children.into_array::<1usize>();
                    ParseTree::StartD(self.arena.alloc(Start {
                        before: (),
                        node: start.unwrap_d(),
                        after: (),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartE
            NonterminalId(14) => match nonterminal_node.return_slot {
                // E : start:E.
                SlotId(37) => {
                    let [start] = children.into_array::<1usize>();
                    ParseTree::StartE(self.arena.alloc(Start {
                        before: (),
                        node: start.unwrap_e(),
                        after: (),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartF
            NonterminalId(15) => match nonterminal_node.return_slot {
                // F : start:F.
                SlotId(39) => {
                    let [start] = children.into_array::<1usize>();
                    ParseTree::StartF(self.arena.alloc(Start {
                        before: (),
                        node: start.unwrap_f(),
                        after: (),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            _ => unreachable!(),
        }
    }
    fn new_token(&self, terminal_node: &TerminalNode) -> ParseTree<'a> {
        ParseTree::Token(Token {
            kind: token_kind(terminal_node.terminal_id),
            span: terminal_node.span,
        })
    }
    fn new_ambiguity_node(
        &self,
        parent: NonterminalId,
        alternatives: Vec<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match parent {
            crate::grammar_data::S => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_s()));
                ParseTree::S(self.arena.alloc(S::Amb(slice)))
            }
            crate::grammar_data::A => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_a()));
                ParseTree::A(self.arena.alloc(A::Amb(slice)))
            }
            crate::grammar_data::B => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_b()));
                ParseTree::B(self.arena.alloc(B::Amb(slice)))
            }
            crate::grammar_data::C => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_c()));
                ParseTree::C(self.arena.alloc(C::Amb(slice)))
            }
            crate::grammar_data::D => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_d()));
                ParseTree::D(self.arena.alloc(D::Amb(slice)))
            }
            crate::grammar_data::E => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_e()));
                ParseTree::E(self.arena.alloc(E::Amb(slice)))
            }
            crate::grammar_data::F => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_f()));
                ParseTree::F(self.arena.alloc(F::Amb(slice)))
            }
            crate::grammar_data::ALT_0 => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_alt_0()));
                ParseTree::Alt0(self.arena.alloc(Alt0::Amb(slice)))
            }
            crate::grammar_data::ALT_1 => {
                let slice = self
                    .arena
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_alt_1()));
                ParseTree::Alt1(self.arena.alloc(Alt1::Amb(slice)))
            }
            crate::grammar_data::START_S => {
                let first = alternatives[0].unwrap_start_s();
                let inner = self.arena.alloc_slice_fill_iter(
                    alternatives.into_iter().map(|a| a.unwrap_start_s().node),
                );
                let node = &*self.arena.alloc(S::Amb(inner));
                ParseTree::StartS(self.arena.alloc(Start {
                    before: first.before,
                    node,
                    after: first.after,
                    span: first.span,
                }))
            }
            crate::grammar_data::START_A => {
                let first = alternatives[0].unwrap_start_a();
                let inner = self.arena.alloc_slice_fill_iter(
                    alternatives.into_iter().map(|a| a.unwrap_start_a().node),
                );
                let node = &*self.arena.alloc(A::Amb(inner));
                ParseTree::StartA(self.arena.alloc(Start {
                    before: first.before,
                    node,
                    after: first.after,
                    span: first.span,
                }))
            }
            crate::grammar_data::START_B => {
                let first = alternatives[0].unwrap_start_b();
                let inner = self.arena.alloc_slice_fill_iter(
                    alternatives.into_iter().map(|a| a.unwrap_start_b().node),
                );
                let node = &*self.arena.alloc(B::Amb(inner));
                ParseTree::StartB(self.arena.alloc(Start {
                    before: first.before,
                    node,
                    after: first.after,
                    span: first.span,
                }))
            }
            crate::grammar_data::START_C => {
                let first = alternatives[0].unwrap_start_c();
                let inner = self.arena.alloc_slice_fill_iter(
                    alternatives.into_iter().map(|a| a.unwrap_start_c().node),
                );
                let node = &*self.arena.alloc(C::Amb(inner));
                ParseTree::StartC(self.arena.alloc(Start {
                    before: first.before,
                    node,
                    after: first.after,
                    span: first.span,
                }))
            }
            crate::grammar_data::START_D => {
                let first = alternatives[0].unwrap_start_d();
                let inner = self.arena.alloc_slice_fill_iter(
                    alternatives.into_iter().map(|a| a.unwrap_start_d().node),
                );
                let node = &*self.arena.alloc(D::Amb(inner));
                ParseTree::StartD(self.arena.alloc(Start {
                    before: first.before,
                    node,
                    after: first.after,
                    span: first.span,
                }))
            }
            crate::grammar_data::START_E => {
                let first = alternatives[0].unwrap_start_e();
                let inner = self.arena.alloc_slice_fill_iter(
                    alternatives.into_iter().map(|a| a.unwrap_start_e().node),
                );
                let node = &*self.arena.alloc(E::Amb(inner));
                ParseTree::StartE(self.arena.alloc(Start {
                    before: first.before,
                    node,
                    after: first.after,
                    span: first.span,
                }))
            }
            crate::grammar_data::START_F => {
                let first = alternatives[0].unwrap_start_f();
                let inner = self.arena.alloc_slice_fill_iter(
                    alternatives.into_iter().map(|a| a.unwrap_start_f().node),
                );
                let node = &*self.arena.alloc(F::Amb(inner));
                ParseTree::StartF(self.arena.alloc(Start {
                    before: first.before,
                    node,
                    after: first.after,
                    span: first.span,
                }))
            }
            _ => unreachable!("nonterminal cannot be ambiguous"),
        }
    }
}
pub fn create_parse_tree<'a>(
    root_id: SPPFNodeId,
    nonterminal_id: NonterminalId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> ParseTree<'a> {
    match nonterminal_id {
        crate::grammar_data::S => ParseTree::S(create_parse_tree_s(root_id, parser, builder)),
        crate::grammar_data::A => ParseTree::A(create_parse_tree_a(root_id, parser, builder)),
        crate::grammar_data::B => ParseTree::B(create_parse_tree_b(root_id, parser, builder)),
        crate::grammar_data::C => ParseTree::C(create_parse_tree_c(root_id, parser, builder)),
        crate::grammar_data::D => ParseTree::D(create_parse_tree_d(root_id, parser, builder)),
        crate::grammar_data::E => ParseTree::E(create_parse_tree_e(root_id, parser, builder)),
        crate::grammar_data::F => ParseTree::F(create_parse_tree_f(root_id, parser, builder)),
        crate::grammar_data::ALT_0 => {
            ParseTree::Alt0(create_parse_tree_alt_0(root_id, parser, builder))
        }
        crate::grammar_data::ALT_1 => {
            ParseTree::Alt1(create_parse_tree_alt_1(root_id, parser, builder))
        }
        crate::grammar_data::START_S => {
            ParseTree::StartS(create_parse_tree_start_s(root_id, parser, builder))
        }
        crate::grammar_data::START_A => {
            ParseTree::StartA(create_parse_tree_start_a(root_id, parser, builder))
        }
        crate::grammar_data::START_B => {
            ParseTree::StartB(create_parse_tree_start_b(root_id, parser, builder))
        }
        crate::grammar_data::START_C => {
            ParseTree::StartC(create_parse_tree_start_c(root_id, parser, builder))
        }
        crate::grammar_data::START_D => {
            ParseTree::StartD(create_parse_tree_start_d(root_id, parser, builder))
        }
        crate::grammar_data::START_E => {
            ParseTree::StartE(create_parse_tree_start_e(root_id, parser, builder))
        }
        crate::grammar_data::START_F => {
            ParseTree::StartF(create_parse_tree_start_f(root_id, parser, builder))
        }
        _ => panic!(),
    }
}
pub fn create_parse_tree_s<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a S<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_s()
}
pub fn create_parse_tree_a<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a A<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_a()
}
pub fn create_parse_tree_b<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a B<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_b()
}
pub fn create_parse_tree_c<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a C<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_c()
}
pub fn create_parse_tree_d<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a D<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_d()
}
pub fn create_parse_tree_e<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a E<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_e()
}
pub fn create_parse_tree_f<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a F<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_f()
}
pub fn create_parse_tree_alt_0<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Alt0<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_alt_0()
}
pub fn create_parse_tree_alt_1<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Alt1<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_alt_1()
}
pub fn create_parse_tree_start_s<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Start<&'a S<'a>, ()> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_s()
}
pub fn create_parse_tree_start_a<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Start<&'a A<'a>, ()> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_a()
}
pub fn create_parse_tree_start_b<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Start<&'a B<'a>, ()> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_b()
}
pub fn create_parse_tree_start_c<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Start<&'a C<'a>, ()> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_c()
}
pub fn create_parse_tree_start_d<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Start<&'a D<'a>, ()> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_d()
}
pub fn create_parse_tree_start_e<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Start<&'a E<'a>, ()> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_e()
}
pub fn create_parse_tree_start_f<'a>(
    root_id: SPPFNodeId,
    parser: &AltSeqParser,
    builder: &AltSeqParseTreeBuilder<'a>,
) -> &'a Start<&'a F<'a>, ()> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_f()
}
impl<'a> ParseTreeNode for ParseTree<'a> {
    fn children(&self) -> Vec<Self> {
        ParseTree::children(self)
    }
    fn display_name(&self) -> &'static str {
        ParseTree::display_name(self)
    }
    fn span(&self) -> Span {
        ParseTree::span(self)
    }
    fn kind(&self) -> NodeKind {
        if self.is_amb() {
            NodeKind::Amb
        } else if matches!(self, ParseTree::Token(_)) {
            NodeKind::Token
        } else {
            NodeKind::Nonterminal
        }
    }
    fn node_id(&self) -> Option<usize> {
        ParseTree::node_id(self)
    }
    fn origin(&self) -> Option<Origin> {
        ParseTree::origin(self)
    }
}
const LAYOUT_NAME: Option<&str> = None;
pub fn to_sexpr(node: ParseTree<'_>) -> String {
    iguana_runtime::parse_tree::to_sexpr(node, LAYOUT_NAME)
}
pub fn to_sexpr_with(node: ParseTree<'_>, options: SexprOptions) -> String {
    iguana_runtime::parse_tree::to_sexpr_with(node, LAYOUT_NAME, options)
}
/// Converts a parse tree to a JSON string of nodes and edges, for visualization.
pub fn to_json(node: ParseTree<'_>) -> String {
    iguana_runtime::parse_tree::to_json(node, LAYOUT_NAME)
}
