// @generated by iguana. Do not edit manually.

use crate::parser::GroupParser;
use iguana_runtime::{
    ids::{NonterminalId, SlotId, TerminalId},
    parse_tree::{
        Bump, NodeKind, OneOrMany, Origin, ParseContext, ParseTreeBuilder, ParseTreeNode,
        SexprOptions, visit_sppf,
    },
    sppf::{NonterminalNode, SPPFNodeId, Span, TerminalNode},
};
use std::vec::IntoIter;
#[derive(Debug, Clone, Copy)]
pub enum TokenKind {
    // "b"
    T0,
    // "c"
    T1,
    // "d"
    T2,
}
impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            TokenKind::T0 => "\"b\"",
            TokenKind::T1 => "\"c\"",
            TokenKind::T2 => "\"d\"",
        }
    }
}
#[derive(Debug, Clone, Copy)]
pub enum ParseTree<'a> {
    A(&'a A<'a>),
    B(&'a B<'a>),
    C(&'a C<'a>),
    D(&'a D<'a>),
    // (B C D)
    Group0(&'a Group0<'a>),
    Token(Token),
}
impl<'a> ParseTree<'a> {
    pub fn children(&self) -> Vec<ParseTree<'a>> {
        match self {
            ParseTree::A(a) => (0..a.child_count()).filter_map(|i| a.child(i)).collect(),
            ParseTree::B(b) => (0..b.child_count()).filter_map(|i| b.child(i)).collect(),
            ParseTree::C(c) => (0..c.child_count()).filter_map(|i| c.child(i)).collect(),
            ParseTree::D(d) => (0..d.child_count()).filter_map(|i| d.child(i)).collect(),
            ParseTree::Group0(group_0) => (0..group_0.child_count())
                .filter_map(|i| group_0.child(i))
                .collect(),
            ParseTree::Token(_) => vec![],
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            ParseTree::A(a) => a.display_name(),
            ParseTree::B(b) => b.display_name(),
            ParseTree::C(c) => c.display_name(),
            ParseTree::D(d) => d.display_name(),
            ParseTree::Group0(group_0) => group_0.display_name(),
            ParseTree::Token(token) => token.kind.name(),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            ParseTree::A(a) => a.child_count(),
            ParseTree::B(b) => b.child_count(),
            ParseTree::C(c) => c.child_count(),
            ParseTree::D(d) => d.child_count(),
            ParseTree::Group0(group_0) => group_0.child_count(),
            ParseTree::Token(_) => 0,
        }
    }
    pub fn span(&self) -> Span {
        match self {
            ParseTree::A(a) => a.span(),
            ParseTree::B(b) => b.span(),
            ParseTree::C(c) => c.span(),
            ParseTree::D(d) => d.span(),
            ParseTree::Group0(group_0) => group_0.span(),
            ParseTree::Token(token) => token.span(),
        }
    }
    #[doc = "True when this node is an ambiguity cluster (any `*::Amb` variant). The"]
    #[doc = "uniform way to detect ambiguity without matching each nonterminal's enum."]
    pub fn is_amb(&self) -> bool {
        match self {
            ParseTree::A(a) => matches!(a, A::Amb(_)),
            ParseTree::B(b) => matches!(b, B::Amb(_)),
            ParseTree::C(c) => matches!(c, C::Amb(_)),
            ParseTree::D(d) => matches!(d, D::Amb(_)),
            ParseTree::Group0(group_0) => matches!(group_0, Group0::Amb(_)),
            ParseTree::Token(_) => false,
        }
    }
    #[doc = "Pointer identity of the underlying node, or `None` for tokens (by-value"]
    #[doc = "leaves that are never shared). Two parse trees with the same `node_id` are"]
    #[doc = "the same allocation, i.e. a node shared between parents in the ambiguity DAG."]
    pub fn node_id(&self) -> Option<usize> {
        match self {
            ParseTree::A(a) => Some(*a as *const _ as usize),
            ParseTree::B(b) => Some(*b as *const _ as usize),
            ParseTree::C(c) => Some(*c as *const _ as usize),
            ParseTree::D(d) => Some(*d as *const _ as usize),
            ParseTree::Group0(group_0) => Some(*group_0 as *const _ as usize),
            ParseTree::Token(_) => None,
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        match self {
            ParseTree::A(a) => a.origin(),
            ParseTree::B(b) => b.origin(),
            ParseTree::C(c) => c.origin(),
            ParseTree::D(d) => d.origin(),
            ParseTree::Group0(group_0) => group_0.origin(),
            ParseTree::Token(_) => None,
        }
    }
    fn unwrap_a(self) -> &'a A<'a> {
        match self {
            ParseTree::A(a) => a,
            _ => panic!(),
        }
    }
    fn unwrap_b(self) -> &'a B<'a> {
        match self {
            ParseTree::B(b) => b,
            _ => panic!(),
        }
    }
    fn unwrap_c(self) -> &'a C<'a> {
        match self {
            ParseTree::C(c) => c,
            _ => panic!(),
        }
    }
    fn unwrap_d(self) -> &'a D<'a> {
        match self {
            ParseTree::D(d) => d,
            _ => panic!(),
        }
    }
    fn unwrap_group_0(self) -> &'a Group0<'a> {
        match self {
            ParseTree::Group0(group_0) => group_0,
            _ => panic!(),
        }
    }
    fn unwrap_token(self) -> Token {
        match self {
            ParseTree::Token(t) => t,
            _ => panic!(),
        }
    }
}
pub trait ListNode<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>>;
}
pub trait OptNode {
    type Inner;
    fn value(&self) -> Option<&Self::Inner>;
}
// A = (B C D)
#[derive(Debug)]
pub enum A<'a> {
    Alt0 { group_0: &'a Group0<'a>, span: Span },
    Amb(&'a [&'a A<'a>]),
}
// B = "b"
#[derive(Debug)]
pub enum B<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a B<'a>]),
}
// C = "c"
#[derive(Debug)]
pub enum C<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a C<'a>]),
}
// D = "d"
#[derive(Debug)]
pub enum D<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a D<'a>]),
}
// (B C D)
#[derive(Debug)]
pub enum Group0<'a> {
    Alt0 {
        b: &'a B<'a>,
        c: &'a C<'a>,
        d: &'a D<'a>,
        span: Span,
    },
    Amb(&'a [&'a Group0<'a>]),
}
impl<'a> A<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::A(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            A::Alt0 { group_0, .. } => match index {
                0 => Some(ParseTree::Group0(group_0)),
                _ => None,
            },
            A::Amb(alts) => alts.get(index).copied().map(ParseTree::A),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            A::Alt0 { .. } => 1usize,
            A::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            A::Alt0 { span, .. } => *span,
            A::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            A::Amb(_) => "Amb",
            _ => "A",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn group_0(&self) -> &'a Group0<'a> {
        match self {
            A::Alt0 { group_0, .. } => group_0,
            A::Amb(_) => panic!("A is ambiguous"),
        }
    }
}
impl<'a> B<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::B(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            B::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            B::Amb(alts) => alts.get(index).copied().map(ParseTree::B),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            B::Alt0 { .. } => 1usize,
            B::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            B::Alt0 { span, .. } => *span,
            B::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            B::Amb(_) => "Amb",
            _ => "B",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            B::Alt0 { lit_0, .. } => *lit_0,
            B::Amb(_) => panic!("B is ambiguous"),
        }
    }
}
impl<'a> C<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::C(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            C::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            C::Amb(alts) => alts.get(index).copied().map(ParseTree::C),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            C::Alt0 { .. } => 1usize,
            C::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            C::Alt0 { span, .. } => *span,
            C::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            C::Amb(_) => "Amb",
            _ => "C",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            C::Alt0 { lit_0, .. } => *lit_0,
            C::Amb(_) => panic!("C is ambiguous"),
        }
    }
}
impl<'a> D<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::D(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            D::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            D::Amb(alts) => alts.get(index).copied().map(ParseTree::D),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            D::Alt0 { .. } => 1usize,
            D::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            D::Alt0 { span, .. } => *span,
            D::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            D::Amb(_) => "Amb",
            _ => "D",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        None
    }
    pub fn lit_0(&self) -> Token {
        match self {
            D::Alt0 { lit_0, .. } => *lit_0,
            D::Amb(_) => panic!("D is ambiguous"),
        }
    }
}
impl<'a> Group0<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Group0(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            Group0::Alt0 { b, c, d, .. } => match index {
                0 => Some(ParseTree::B(b)),
                1 => Some(ParseTree::C(c)),
                2 => Some(ParseTree::D(d)),
                _ => None,
            },
            Group0::Amb(alts) => alts.get(index).copied().map(ParseTree::Group0),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            Group0::Alt0 { .. } => 3usize,
            Group0::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            Group0::Alt0 { span, .. } => *span,
            Group0::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            Group0::Amb(_) => "Amb",
            _ => "(B C D)",
        }
    }
    pub fn origin(&self) -> Option<Origin> {
        match self {
            Group0::Amb(_) => None,
            _ => Some(Origin::Group),
        }
    }
    pub fn b(&self) -> &'a B<'a> {
        match self {
            Group0::Alt0 { b, .. } => b,
            Group0::Amb(_) => panic!("Group_0 is ambiguous"),
        }
    }
    pub fn c(&self) -> &'a C<'a> {
        match self {
            Group0::Alt0 { c, .. } => c,
            Group0::Amb(_) => panic!("Group_0 is ambiguous"),
        }
    }
    pub fn d(&self) -> &'a D<'a> {
        match self {
            Group0::Alt0 { d, .. } => d,
            Group0::Amb(_) => panic!("Group_0 is ambiguous"),
        }
    }
}
impl<'a> ListNode<'a> for Group0<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>> {
        match self {
            Group0::Alt0 { b, c, d, .. } => {
                vec![b.as_parse_tree(), c.as_parse_tree(), d.as_parse_tree()].into_iter()
            }
            Group0::Amb(_) => vec![ParseTree::Group0(self)].into_iter(),
        }
    }
}
#[derive(Debug, Clone, Copy)]
pub struct Token {
    pub kind: TokenKind,
    span: Span,
}
impl Token {
    pub fn as_parse_tree<'a>(&self) -> ParseTree<'a> {
        ParseTree::Token(*self)
    }
    pub fn span(&self) -> Span {
        self.span
    }
}
fn token_kind(terminal_id: TerminalId) -> TokenKind {
    match terminal_id {
        // "b"
        TerminalId(0) => TokenKind::T0,
        // "c"
        TerminalId(1) => TokenKind::T1,
        // "d"
        TerminalId(2) => TokenKind::T2,
        _ => unreachable!("Unknown TerminalId: {:?}", terminal_id),
    }
}
pub struct GroupParseTreeBuilder<'a> {
    pub bump: &'a Bump,
}
impl<'a> GroupParseTreeBuilder<'a> {
    pub fn new(ctx: &'a ParseContext) -> Self {
        Self { bump: ctx.bump() }
    }
}
impl<'a> ParseTreeBuilder<ParseTree<'a>> for GroupParseTreeBuilder<'a> {
    fn new_nonterminal_node(
        &self,
        nonterminal_node: &NonterminalNode,
        children: OneOrMany<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match nonterminal_node.nonterminal_id {
            // A
            NonterminalId(0) => match nonterminal_node.return_slot {
                // A : (B C D).
                SlotId(1) => {
                    let [group_0] = children.into_array::<1usize>();
                    ParseTree::A(self.bump.alloc(A::Alt0 {
                        group_0: group_0.unwrap_group_0(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // B
            NonterminalId(1) => match nonterminal_node.return_slot {
                // B : "b".
                SlotId(3) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::B(self.bump.alloc(B::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // C
            NonterminalId(2) => match nonterminal_node.return_slot {
                // C : "c".
                SlotId(5) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::C(self.bump.alloc(C::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // D
            NonterminalId(3) => match nonterminal_node.return_slot {
                // D : "d".
                SlotId(7) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::D(self.bump.alloc(D::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Group_0
            NonterminalId(4) => match nonterminal_node.return_slot {
                // (B C D) : B C D.
                SlotId(11) => {
                    let [b, c, d] = children.into_array::<3usize>();
                    ParseTree::Group0(self.bump.alloc(Group0::Alt0 {
                        b: b.unwrap_b(),
                        c: c.unwrap_c(),
                        d: d.unwrap_d(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            _ => unreachable!(),
        }
    }
    fn new_token(&self, terminal_node: &TerminalNode) -> ParseTree<'a> {
        ParseTree::Token(Token {
            kind: token_kind(terminal_node.terminal_id),
            span: terminal_node.span,
        })
    }
    fn new_ambiguity_node(
        &self,
        parent: NonterminalId,
        alternatives: Vec<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match parent {
            crate::grammar_data::A => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_a()));
                ParseTree::A(self.bump.alloc(A::Amb(slice)))
            }
            crate::grammar_data::B => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_b()));
                ParseTree::B(self.bump.alloc(B::Amb(slice)))
            }
            crate::grammar_data::C => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_c()));
                ParseTree::C(self.bump.alloc(C::Amb(slice)))
            }
            crate::grammar_data::D => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_d()));
                ParseTree::D(self.bump.alloc(D::Amb(slice)))
            }
            crate::grammar_data::GROUP_0 => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_group_0()));
                ParseTree::Group0(self.bump.alloc(Group0::Amb(slice)))
            }
            _ => unreachable!("nonterminal cannot be ambiguous"),
        }
    }
}
pub fn create_parse_tree<'a>(
    root_id: SPPFNodeId,
    nonterminal_id: NonterminalId,
    parser: &GroupParser,
    builder: &GroupParseTreeBuilder<'a>,
) -> ParseTree<'a> {
    match nonterminal_id {
        crate::grammar_data::A => ParseTree::A(create_parse_tree_a(root_id, parser, builder)),
        crate::grammar_data::B => ParseTree::B(create_parse_tree_b(root_id, parser, builder)),
        crate::grammar_data::C => ParseTree::C(create_parse_tree_c(root_id, parser, builder)),
        crate::grammar_data::D => ParseTree::D(create_parse_tree_d(root_id, parser, builder)),
        crate::grammar_data::GROUP_0 => {
            ParseTree::Group0(create_parse_tree_group_0(root_id, parser, builder))
        }
        _ => panic!(),
    }
}
pub fn create_parse_tree_a<'a>(
    root_id: SPPFNodeId,
    parser: &GroupParser,
    builder: &GroupParseTreeBuilder<'a>,
) -> &'a A<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_a()
}
pub fn create_parse_tree_b<'a>(
    root_id: SPPFNodeId,
    parser: &GroupParser,
    builder: &GroupParseTreeBuilder<'a>,
) -> &'a B<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_b()
}
pub fn create_parse_tree_c<'a>(
    root_id: SPPFNodeId,
    parser: &GroupParser,
    builder: &GroupParseTreeBuilder<'a>,
) -> &'a C<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_c()
}
pub fn create_parse_tree_d<'a>(
    root_id: SPPFNodeId,
    parser: &GroupParser,
    builder: &GroupParseTreeBuilder<'a>,
) -> &'a D<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_d()
}
pub fn create_parse_tree_group_0<'a>(
    root_id: SPPFNodeId,
    parser: &GroupParser,
    builder: &GroupParseTreeBuilder<'a>,
) -> &'a Group0<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_group_0()
}
impl<'a> ParseTreeNode for ParseTree<'a> {
    fn children(&self) -> Vec<Self> {
        ParseTree::children(self)
    }
    fn display_name(&self) -> &'static str {
        ParseTree::display_name(self)
    }
    fn span(&self) -> Span {
        ParseTree::span(self)
    }
    fn kind(&self) -> NodeKind {
        if self.is_amb() {
            NodeKind::Amb
        } else if matches!(self, ParseTree::Token(_)) {
            NodeKind::Token
        } else {
            NodeKind::Nonterminal
        }
    }
    fn node_id(&self) -> Option<usize> {
        ParseTree::node_id(self)
    }
    fn origin(&self) -> Option<Origin> {
        ParseTree::origin(self)
    }
}
const LAYOUT_NAME: Option<&str> = None;
pub fn to_sexpr(node: ParseTree<'_>) -> String {
    iguana_runtime::parse_tree::to_sexpr(node, LAYOUT_NAME)
}
pub fn to_sexpr_with(node: ParseTree<'_>, options: SexprOptions) -> String {
    iguana_runtime::parse_tree::to_sexpr_with(node, LAYOUT_NAME, options)
}
/// Converts a parse tree to a JSON string of nodes and edges, for visualization.
pub fn to_json(node: ParseTree<'_>) -> String {
    iguana_runtime::parse_tree::to_json(node, LAYOUT_NAME)
}
