// @generated by iguana. Do not edit manually.

use crate::parser::PrecedeRestrictionLexicalParser;
use core::fmt;
use iguana_runtime::{
    ids::{NonterminalId, SlotId, TerminalId},
    parse_tree::{Bump, OneOrMany, ParseContext, ParseTreeBuilder, visit_sppf},
    parser::Parser,
    sppf::{NonterminalNode, SPPFNodeId, Span, TerminalNode},
};
use std::{fmt::Write, vec::IntoIter};
#[derive(Debug, Clone, Copy)]
pub enum TokenKind {
    // Id
    T0,
    // Char
    T1,
    // WS
    T2,
    // "for"
    T3,
    // "forall"
    T4,
}
impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            TokenKind::T0 => "Id",
            TokenKind::T1 => "Char",
            TokenKind::T2 => "WS",
            TokenKind::T3 => "\"for\"",
            TokenKind::T4 => "\"forall\"",
            _ => unreachable!(),
        }
    }
}
#[derive(Debug, Clone, Copy)]
pub enum ParseTree<'a> {
    S(&'a S<'a>),
    Token(Token),
}
impl<'a> ParseTree<'a> {
    pub fn children(&self) -> Vec<ParseTree<'a>> {
        match self {
            ParseTree::S(s) => (0..s.child_count()).filter_map(|i| s.child(i)).collect(),
            ParseTree::Token(_) => vec![],
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            ParseTree::S(_) => "S",
            ParseTree::Token(token) => token.kind.name(),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            ParseTree::S(s) => s.child_count(),
            ParseTree::Token(_) => 0,
        }
    }
    pub fn span(&self) -> Span {
        match self {
            ParseTree::S(s) => s.span(),
            ParseTree::Token(token) => token.span(),
        }
    }
    fn unwrap_s(self) -> &'a S<'a> {
        match self {
            ParseTree::S(s) => s,
            _ => panic!(),
        }
    }
    fn unwrap_token(self) -> Token {
        match self {
            ParseTree::Token(t) => t,
            _ => panic!(),
        }
    }
}
pub trait ListNode<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>>;
}
pub trait OptNode {
    type Inner;
    fn value(&self) -> Option<&Self::Inner>;
}
#[derive(Debug)]
pub enum S<'a> {
    // "for" WS Id
    Alt0 {
        lit_0: Token,
        ws: Token,
        id: Token,
        span: Span,
    },
    // "forall"
    Alt1 {
        lit_0: Token,
        span: Span,
    },
    Amb(&'a [&'a S<'a>]),
}
impl<'a> S<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::S(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            S::Alt0 { lit_0, ws, id, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                1 => Some(ParseTree::Token(*ws)),
                2 => Some(ParseTree::Token(*id)),
                _ => None,
            },
            S::Alt1 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            S::Amb(_) => None,
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            S::Alt0 { .. } => 3usize,
            S::Alt1 { .. } => 1usize,
            S::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            S::Alt0 { span, .. } => *span,
            S::Alt1 { span, .. } => *span,
            S::Amb(alts) => alts[0].span(),
        }
    }
}
#[derive(Debug, Clone, Copy)]
pub struct Token {
    pub kind: TokenKind,
    span: Span,
}
impl Token {
    pub fn as_parse_tree<'a>(&self) -> ParseTree<'a> {
        ParseTree::Token(*self)
    }
    pub fn span(&self) -> Span {
        self.span
    }
}
fn token_kind(terminal_id: TerminalId) -> TokenKind {
    match terminal_id {
        // Id
        TerminalId(0) => TokenKind::T0,
        // Char
        TerminalId(1) => TokenKind::T1,
        // WS
        TerminalId(2) => TokenKind::T2,
        // "for"
        TerminalId(3) => TokenKind::T3,
        // "forall"
        TerminalId(4) => TokenKind::T4,
        _ => unreachable!("Unknown TerminalId: {:?}", terminal_id),
    }
}
pub struct PrecedeRestrictionLexicalParseTreeBuilder<'a> {
    pub bump: &'a Bump,
}
impl<'a> PrecedeRestrictionLexicalParseTreeBuilder<'a> {
    pub fn new(ctx: &'a ParseContext) -> Self {
        Self { bump: ctx.bump() }
    }
}
impl<'a> ParseTreeBuilder<ParseTree<'a>> for PrecedeRestrictionLexicalParseTreeBuilder<'a> {
    fn new_nonterminal_node(
        &self,
        nonterminal_node: &NonterminalNode,
        children: OneOrMany<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match nonterminal_node.nonterminal_id {
            // S
            NonterminalId(0) => match nonterminal_node.return_slot {
                // S : "for" WS Id.
                SlotId(3) => {
                    let [lit_0, ws, id] = children.into_array::<3usize>();
                    ParseTree::S(self.bump.alloc(S::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        ws: ws.unwrap_token(),
                        id: id.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                // S : "forall".
                SlotId(5) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::S(self.bump.alloc(S::Alt1 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            _ => unreachable!(),
        }
    }
    fn new_token(&self, terminal_node: &TerminalNode) -> ParseTree<'a> {
        ParseTree::Token(Token {
            kind: token_kind(terminal_node.terminal_id),
            span: terminal_node.span,
        })
    }
}
pub fn create_parse_tree<'a>(
    root_id: SPPFNodeId,
    nonterminal_id: NonterminalId,
    parser: &PrecedeRestrictionLexicalParser,
    builder: &PrecedeRestrictionLexicalParseTreeBuilder<'a>,
) -> ParseTree<'a> {
    match nonterminal_id {
        crate::grammar_data::S => ParseTree::S(create_parse_tree_s(root_id, parser, builder)),
        _ => panic!(),
    }
}
pub fn create_parse_tree_s<'a>(
    root_id: SPPFNodeId,
    parser: &PrecedeRestrictionLexicalParser,
    builder: &PrecedeRestrictionLexicalParseTreeBuilder<'a>,
) -> &'a S<'a> {
    let node = parser.sppf_node(root_id);
    visit_sppf(node, parser, builder).unwrap_one().unwrap_s()
}
pub fn to_sexpr(node: ParseTree<'_>) -> String {
    let mut s = String::new();
    node_to_sexpr(node, 0, &mut s).expect("error");
    s
}
fn node_to_sexpr(node: ParseTree<'_>, indent: usize, w: &mut impl Write) -> fmt::Result {
    let children = node.children();
    if children.is_empty() {
        writeln!(w, "{:indent$}{}", "", node.display_name())
    } else {
        writeln!(w, "{:indent$}({}", "", node.display_name())?;
        for child in children {
            node_to_sexpr(child, indent + 2, w)?;
        }
        writeln!(w, "{:indent$})", "")
    }
}
#[doc = r" Converts a parse tree to JSON format for visualization."]
#[doc = r" Returns a JSON string with nodes and edges arrays."]
pub fn to_json(node: ParseTree<'_>) -> String {
    let mut nodes = Vec::new();
    let mut edges = Vec::new();
    let mut next_id = 0u32;
    build_json_graph(node, &mut nodes, &mut edges, &mut next_id);
    let result = serde_json :: json ! ({ "nodes" : nodes , "edges" : edges });
    result.to_string()
}
fn build_json_graph(
    node: ParseTree<'_>,
    nodes: &mut Vec<serde_json::Value>,
    edges: &mut Vec<serde_json::Value>,
    next_id: &mut u32,
) -> u32 {
    let my_id = *next_id;
    *next_id += 1;
    let span = node.span();
    let kind = match node {
        ParseTree::Token(_) => "Token",
        _ => "Nonterminal",
    };
    nodes . push (serde_json :: json ! ({ "id" : my_id , "kind" : kind , "label" : node . display_name () , "start" : span . left_extent , "end" : span . right_extent })) ;
    for child in node.children() {
        let child_id = build_json_graph(child, nodes, edges, next_id);
        edges.push(serde_json :: json ! ({ "src" : my_id , "dest" : child_id }));
    }
    my_id
}
