[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"
test = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
iguana-compiler.workspace = true
proc-macro2.workspace = true
quote.workspace = true
