[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
license.workspace = true
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap.workspace = true
iguana-compiler.workspace = true
proc-macro2.workspace = true
quote.workspace = true
semver = "1"
serde_json.workspace = true
toml_edit = "0.25"
