use std::{
    fs,
    io::{self, Write},
    path::Path,
    time::Instant,
};

use crate::{
    generator::{
        id::{BindingIds, EndSlot, NonterminalIds, SlotIds, TerminalIds},
        parser_gen::ParserGen,
    },
    grammar::{def::Grammar, slot::Slot, symbols::Symbol},
};

fn collect_binding_names(symbol: &Symbol, binding_ids: &mut BindingIds) {
    if let Symbol::Binding { name, .. } = symbol {
        binding_ids.insert(name.clone());
    }
    match symbol {
        Symbol::Labeled { symbol, .. }
        | Symbol::Binding { symbol, .. }
        | Symbol::Except { symbol, .. }
        | Symbol::FollowRestriction { symbol, .. }
        | Symbol::PrecedeRestriction { symbol, .. }
        | Symbol::Exclude { symbol, .. }
        | Symbol::Opt(symbol) => collect_binding_names(symbol, binding_ids),
        Symbol::Group(symbols) | Symbol::Alt(symbols) => {
            for s in symbols {
                collect_binding_names(s, binding_ids);
            }
        }
        Symbol::Star(symbol, sep) | Symbol::Plus(symbol, sep) => {
            collect_binding_names(symbol, binding_ids);
            if let Some(sep) = sep {
                collect_binding_names(sep, binding_ids);
            }
        }
        Symbol::Identifier(_)
        | Symbol::Literal(_)
        | Symbol::Call { .. }
        | Symbol::Condition(_)
        | Symbol::Return(_) => {}
    }
}

#[derive(Clone, Copy)]
pub struct GenConfig {
    pub ll1_optimization: bool,
    pub match_memo: bool,
    /// When true, scaffold a CLI: Cargo.toml + src/main.rs. When false,
    /// the caller owns Cargo.toml and no CLI binary is emitted.
    pub cli: bool,
}

impl Default for GenConfig {
    fn default() -> Self {
        Self {
            ll1_optimization: true,
            match_memo: true,
            cli: true,
        }
    }
}

pub struct GenerateResult {
    pub total_duration_ms: u64,
}

mod cargo_toml_gen;
mod grammar_data_gen;
pub(crate) mod grammar_utils;
mod id;
mod lib_gen;
mod main_gen;
mod parse_tree_gen;
mod parser_gen;
mod scanner_gen;
mod types_gen;

mod post_process;
pub use post_process::post_process;
pub(crate) mod utils;

const GENERATED_HEADER_RUST: &str = "// @generated by iguana. Do not edit manually.\n\n";

/// Generate parser source files into `<output_dir>/src/`.
///
/// Writes lib.rs, parser.rs, scanner.rs, parse_tree.rs, types.rs, and
/// grammar_data.rs. Does not touch Cargo.toml or main.rs — those are
/// scaffolded once by `generate_scaffold` and owned by the user thereafter.
pub fn generate_sources(
    grammar: &Grammar,
    output_dir: &Path,
    config: GenConfig,
) -> io::Result<GenerateResult> {
    let start = Instant::now();
    let mut nonterminal_ids = NonterminalIds::new(grammar.nonterminals().cloned());
    let mut terminal_ids = TerminalIds::default();
    for terminal in grammar.terminals() {
        terminal_ids.insert(terminal.clone());
    }
    let mut binding_ids = BindingIds::default();
    for nt in grammar.nonterminals() {
        for param in &nt.parameters {
            binding_ids.insert(param.name.clone());
        }
        for alternative in grammar.alternatives(nt) {
            for symbol in &alternative.symbols {
                collect_binding_names(symbol, &mut binding_ids);
            }
        }
    }
    let mut slot_ids = SlotIds::new(grammar);
    for nonterminal in grammar.nonterminals() {
        let alternatives = grammar.alternatives(nonterminal);
        for (index, alternative) in alternatives.iter().enumerate() {
            for pos in 0..alternative.symbols.len() {
                let slot = Slot::new(nonterminal, alternative, pos);
                slot_ids.insert(slot);
            }
            let last_symbol_index = alternative.symbols.len();
            let end_slot = Slot::new(nonterminal, alternative, last_symbol_index);
            let end_slot_id = slot_ids.insert(end_slot);
            let nonterminal_id = nonterminal_ids.get_id(nonterminal);
            let end_slot = EndSlot {
                index,
                slot_id: end_slot_id,
            };
            nonterminal_ids.add_end_slot(nonterminal_id, end_slot);
        }
    }

    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    let src_dir = output_dir.join("src");
    if !src_dir.exists() {
        fs::create_dir(&src_dir)?;
    }

    let lib_path = src_dir.join("lib.rs");
    let parser_path = src_dir.join("parser.rs");
    let scanner_path = src_dir.join("scanner.rs");
    let parse_tree_path = src_dir.join("parse_tree.rs");
    let types_path = src_dir.join("types.rs");
    let grammar_data_path = src_dir.join("grammar_data.rs");

    write_rust_file(
        post_process(&lib_gen::generate(grammar).to_string()),
        &lib_path,
    )?;

    let mut parser_gen = ParserGen::new(
        grammar,
        &nonterminal_ids,
        &terminal_ids,
        &slot_ids,
        &binding_ids,
        config,
    );
    let parser_code = parser_gen.generate();
    let grammar_comment = grammar
        .to_string()
        .lines()
        .map(|l| format!("// {l}"))
        .collect::<Vec<_>>()
        .join("\n");
    let parser_source = format!(
        "{grammar_comment}\n{}",
        post_process(&parser_code.to_string())
    );
    write_rust_file(parser_source, &parser_path)?;

    write_rust_file(
        post_process(&scanner_gen::generate(grammar, &terminal_ids, &config).to_string()),
        &scanner_path,
    )?;

    write_rust_file(
        post_process(
            &parse_tree_gen::generate(grammar, &nonterminal_ids, &terminal_ids, &slot_ids)
                .to_string(),
        ),
        &parse_tree_path,
    )?;

    write_rust_file(
        post_process(&types_gen::generate().to_string()),
        &types_path,
    )?;

    write_rust_file(
        post_process(
            &grammar_data_gen::generate(grammar, &nonterminal_ids, &terminal_ids, &slot_ids)
                .to_string(),
        ),
        &grammar_data_path,
    )?;

    Ok(GenerateResult {
        total_duration_ms: start.elapsed().as_millis() as u64,
    })
}

/// Scaffold Cargo.toml and src/main.rs into `output_dir`.
///
/// `config.cli` controls the shape: when true, the Cargo.toml describes a
/// standalone parser crate with a CLI binary (and `src/main.rs` is written);
/// when false, the Cargo.toml is a minimal lib-only shape that assumes a
/// workspace context, and `src/main.rs` is not written.
///
/// Idempotent: each file is written only if it does not already exist.
/// The user owns these files after first creation; subsequent grammar
/// changes do not regenerate them.
pub fn generate_scaffold(
    grammar: &Grammar,
    output_dir: &Path,
    config: GenConfig,
) -> io::Result<()> {
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    let src_dir = output_dir.join("src");
    if !src_dir.exists() {
        fs::create_dir(&src_dir)?;
    }

    let cargo_toml = output_dir.join("Cargo.toml");
    if !cargo_toml.exists() {
        write_plain_file(cargo_toml_gen::generate(grammar, config.cli), &cargo_toml)?;
    }

    if config.cli {
        let main_rs = src_dir.join("main.rs");
        if !main_rs.exists() {
            let main_code = main_gen::generate(grammar);
            write_plain_file(post_process(&main_code.to_string()), &main_rs)?;
        }
    }

    Ok(())
}

fn write_rust_file(content: impl AsRef<str>, path: &Path) -> io::Result<()> {
    let mut file = fs::File::create(path)?;
    file.write_all(GENERATED_HEADER_RUST.as_bytes())?;
    file.write_all(content.as_ref().as_bytes())?;
    file.write_all(b"\n")?;
    Ok(())
}

fn write_plain_file(content: impl AsRef<str>, path: &Path) -> io::Result<()> {
    let mut file = fs::File::create(path)?;
    file.write_all(content.as_ref().as_bytes())?;
    file.write_all(b"\n")?;
    Ok(())
}
