use std::{
    fs,
    io::{self, Write},
    path::Path,
    time::Instant,
};

use crate::{
    generator::{
        id::{BindingIds, EndSlot, NonterminalIds, SlotIds, TerminalIds},
        parser_gen::ParserGen,
        terminal_sets::{SetIds, terminal_sets},
    },
    grammar::{def::Grammar, first_follow::FirstFollowSets, slot::Slot, symbols::Symbol},
};

fn collect_binding_names(symbol: &Symbol, binding_ids: &mut BindingIds) {
    if let Symbol::Binding { name, .. } = symbol {
        binding_ids.insert(name.clone());
    }
    match symbol {
        Symbol::Labeled { symbol, .. }
        | Symbol::Binding { symbol, .. }
        | Symbol::Except { symbol, .. }
        | Symbol::FollowRestriction { symbol, .. }
        | Symbol::PrecedeRestriction { symbol, .. }
        | Symbol::Exclude { symbol, .. }
        | Symbol::Opt(symbol) => collect_binding_names(symbol, binding_ids),
        Symbol::Group(symbols) | Symbol::Alt(symbols) => {
            for s in symbols {
                collect_binding_names(s, binding_ids);
            }
        }
        Symbol::Star(symbol, sep) | Symbol::Plus(symbol, sep) => {
            collect_binding_names(symbol, binding_ids);
            if let Some(sep) = sep {
                collect_binding_names(sep, binding_ids);
            }
        }
        Symbol::Identifier(_)
        | Symbol::Literal(_)
        | Symbol::Call { .. }
        | Symbol::Condition(_)
        | Symbol::Return(_) => {}
    }
}

#[derive(Clone, Copy)]
pub struct GenConfig {
    pub ll1_optimization: bool,
    pub match_memo: bool,
    /// When true, scaffold a CLI: Cargo.toml + src/main.rs. When false,
    /// the caller owns Cargo.toml and no CLI binary is emitted.
    pub cli: bool,
    /// When true, emit a wasm bundle: a standalone lib crate plus a
    /// `wasm-bindgen` wrapper crate under `wasm/` and a `manifest.json`. A
    /// wasm bundle has no CLI, so `wasm` and `cli` are mutually exclusive.
    pub wasm: bool,
}

impl Default for GenConfig {
    fn default() -> Self {
        Self {
            ll1_optimization: true,
            match_memo: true,
            cli: true,
            wasm: false,
        }
    }
}

pub struct GenerateResult {
    pub total_duration_ms: u64,
}

mod cargo_toml_gen;
mod grammar_data_gen;
pub(crate) mod grammar_utils;
mod id;
mod lib_gen;
mod main_gen;
mod manifest_gen;
mod parse_tree_gen;
mod parser_gen;
mod scanner_gen;
mod terminal_sets;
mod types_gen;
mod wasm_gen;

mod post_process;
pub use post_process::post_process;
pub(crate) mod utils;

const GENERATED_HEADER_RUST: &str = "// @generated by iguana. Do not edit manually.\n\n";

/// Generate parser source files into `<output_dir>/src/`.
///
/// Writes lib.rs, parser.rs, scanner.rs, parse_tree.rs, types.rs, and
/// grammar_data.rs. Does not touch Cargo.toml or main.rs — those are
/// scaffolded once by `generate_scaffold` and owned by the user thereafter.
pub fn generate_sources(
    grammar: &Grammar,
    output_dir: &Path,
    config: GenConfig,
) -> io::Result<GenerateResult> {
    let start = Instant::now();
    let mut nonterminal_ids = NonterminalIds::new(grammar.nonterminals().cloned());
    let mut terminal_ids = TerminalIds::default();
    for terminal in grammar.terminals() {
        terminal_ids.insert(terminal.clone());
    }
    let mut binding_ids = BindingIds::default();
    for nt in grammar.nonterminals() {
        for param in &nt.parameters {
            binding_ids.insert(param.name.clone());
        }
        for alternative in grammar.alternatives(nt) {
            for symbol in &alternative.symbols {
                collect_binding_names(symbol, &mut binding_ids);
            }
        }
    }
    let mut slot_ids = SlotIds::new(grammar);
    // `nonterminal_ids.nonterminals()` returns non-parameterized nonterminals
    // first (sorted at construction in `NonterminalIds::new`). Iterating in
    // that order means all slots of non-parameterized nonterminals get lower
    // ids than slots of parameterized ones. The intermediate-node index uses
    // this partition to dispatch between a `Span`-keyed array
    // (non-parameterized) and a `(Span, Option<EnvId>)`-keyed array
    // (parameterized).
    let sorted_nonterminals: Vec<_> = nonterminal_ids.nonterminals().cloned().collect();
    for nonterminal in &sorted_nonterminals {
        let alternatives = grammar.alternatives(nonterminal);
        for (index, alternative) in alternatives.iter().enumerate() {
            for pos in 0..alternative.symbols.len() {
                let slot = Slot::new(nonterminal, alternative, pos);
                slot_ids.insert(slot);
            }
            let last_symbol_index = alternative.symbols.len();
            let end_slot = Slot::new(nonterminal, alternative, last_symbol_index);
            let end_slot_id = slot_ids.insert(end_slot);
            let nonterminal_id = nonterminal_ids.get_id(nonterminal);
            let end_slot = EndSlot {
                index,
                slot_id: end_slot_id,
            };
            nonterminal_ids.add_end_slot(nonterminal_id, end_slot);
        }
    }

    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    let src_dir = output_dir.join("src");
    if !src_dir.exists() {
        fs::create_dir(&src_dir)?;
    }

    let lib_path = src_dir.join("lib.rs");
    let parser_path = src_dir.join("parser.rs");
    let scanner_path = src_dir.join("scanner.rs");
    let parse_tree_path = src_dir.join("parse_tree.rs");
    let types_path = src_dir.join("types.rs");
    let grammar_data_path = src_dir.join("grammar_data.rs");

    write_rust_file(
        post_process(&lib_gen::generate(grammar).to_string()),
        &lib_path,
    )?;

    let ff = FirstFollowSets::new(grammar);
    let terminal_sets = terminal_sets(grammar, &ff);
    let match_any_sets = SetIds::match_any(&terminal_sets, &terminal_ids);
    let longest_match_sets = SetIds::longest_match(&terminal_sets, &terminal_ids);

    let mut parser_gen = ParserGen::new(
        grammar,
        &nonterminal_ids,
        &terminal_ids,
        &slot_ids,
        &binding_ids,
        config,
    );
    let parser_code = parser_gen.generate();
    let grammar_comment = grammar
        .to_string()
        .lines()
        .map(|l| format!("// {l}"))
        .collect::<Vec<_>>()
        .join("\n");
    let parser_source = format!(
        "{grammar_comment}\n{}",
        post_process(&parser_code.to_string())
    );
    write_rust_file(parser_source, &parser_path)?;

    write_rust_file(
        post_process(
            &scanner_gen::generate(grammar, &terminal_ids, &match_any_sets, &config).to_string(),
        ),
        &scanner_path,
    )?;

    write_rust_file(
        post_process(
            &parse_tree_gen::generate(grammar, &nonterminal_ids, &terminal_ids, &slot_ids)
                .to_string(),
        ),
        &parse_tree_path,
    )?;

    write_rust_file(
        post_process(&types_gen::generate().to_string()),
        &types_path,
    )?;

    write_rust_file(
        post_process(
            &grammar_data_gen::generate(
                grammar,
                &nonterminal_ids,
                &terminal_ids,
                &slot_ids,
                &terminal_sets,
                &match_any_sets,
                &longest_match_sets,
            )
            .to_string(),
        ),
        &grammar_data_path,
    )?;

    Ok(GenerateResult {
        total_duration_ms: start.elapsed().as_millis() as u64,
    })
}

/// Scaffold Cargo.toml and, for a CLI parser, src/main.rs into `output_dir`.
///
/// The Cargo.toml shape follows `config`: a wasm lib crate, a standalone CLI
/// parser crate, or a minimal workspace-member lib. `src/main.rs` is written
/// only for the CLI shape (`config.cli` and not `config.wasm`); a wasm bundle
/// and a workspace-member lib have no binary.
///
/// By default each file is written only if it does not already exist, so the
/// user owns them after first creation. When `force` is true, the scaffold
/// step overwrites existing files (useful when the generator's CLI or
/// Cargo.toml template has changed and you want to pick the new shape up).
pub fn generate_scaffold(
    grammar: &Grammar,
    output_dir: &Path,
    config: GenConfig,
    force: bool,
) -> io::Result<()> {
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    let src_dir = output_dir.join("src");
    if !src_dir.exists() {
        fs::create_dir(&src_dir)?;
    }

    let cargo_toml = output_dir.join("Cargo.toml");
    if force || !cargo_toml.exists() {
        write_plain_file(cargo_toml_gen::generate(grammar, config), &cargo_toml)?;
    }

    if config.cli && !config.wasm {
        let main_rs = src_dir.join("main.rs");
        if force || !main_rs.exists() {
            let main_code = main_gen::generate(grammar);
            write_plain_file(post_process(&main_code.to_string()), &main_rs)?;
        }
    }

    Ok(())
}

/// Write the wasm bundle into `output_dir`: the wrapper crate under `wasm/`
/// and `manifest.json`. The parser lib sources and the root crate's Cargo.toml
/// come from `generate_sources` and `generate_scaffold`; this step adds only
/// the wasm-specific files.
///
/// The wrapper `lib.rs` and `manifest.json` are derived from the grammar and
/// always overwritten. The wrapper `Cargo.toml` is scaffolding, so it is
/// written only when absent (or when `force` is set), preserving a hand-edited
/// dependency such as a local path to the runtime.
pub fn generate_wasm(grammar: &Grammar, output_dir: &Path, force: bool) -> io::Result<()> {
    let wasm_src = output_dir.join("wasm").join("src");
    if !wasm_src.exists() {
        fs::create_dir_all(&wasm_src)?;
    }

    write_rust_file(
        post_process(&wasm_gen::generate(grammar).to_string()),
        &wasm_src.join("lib.rs"),
    )?;

    let wasm_cargo = output_dir.join("wasm").join("Cargo.toml");
    if force || !wasm_cargo.exists() {
        write_plain_file(cargo_toml_gen::generate_wasm_wrapper(grammar), &wasm_cargo)?;
    }

    write_plain_file(
        manifest_gen::generate(grammar),
        &output_dir.join("manifest.json"),
    )?;

    Ok(())
}

fn write_rust_file(content: impl AsRef<str>, path: &Path) -> io::Result<()> {
    let mut file = fs::File::create(path)?;
    file.write_all(GENERATED_HEADER_RUST.as_bytes())?;
    file.write_all(content.as_ref().as_bytes())?;
    file.write_all(b"\n")?;
    Ok(())
}

fn write_plain_file(content: impl AsRef<str>, path: &Path) -> io::Result<()> {
    let mut file = fs::File::create(path)?;
    file.write_all(content.as_ref().as_bytes())?;
    file.write_all(b"\n")?;
    Ok(())
}
