// @generated by iguana. Do not edit manually.

#![allow(clippy::collapsible_if)]
use crate::parser::PlusWithSepParser;
use core::fmt;
use iguana_runtime::{
    ids::{NonterminalId, SlotId, TerminalId},
    parse_tree::{Bump, OneOrMany, ParseContext, ParseTreeBuilder, SexprOptions, visit_sppf},
    sppf::{NonterminalNode, SPPFNodeId, Span, TerminalNode},
};
use rustc_hash::{FxHashMap, FxHashSet};
use std::{fmt::Write, vec::IntoIter};
#[derive(Debug, Clone, Copy)]
pub enum TokenKind {
    // ","
    T0,
    // "a"
    T1,
}
impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            TokenKind::T0 => "\",\"",
            TokenKind::T1 => "\"a\"",
        }
    }
}
#[derive(Debug, Clone, Copy)]
pub enum ParseTree<'a> {
    S(&'a S<'a>),
    A(&'a A<'a>),
    // {A ","}+
    Plus0(&'a Plus0<'a>),
    Token(Token),
}
impl<'a> ParseTree<'a> {
    pub fn children(&self) -> Vec<ParseTree<'a>> {
        match self {
            ParseTree::S(s) => (0..s.child_count()).filter_map(|i| s.child(i)).collect(),
            ParseTree::A(a) => (0..a.child_count()).filter_map(|i| a.child(i)).collect(),
            ParseTree::Plus0(plus_0) => match plus_0 {
                Plus0::Amb(alts) => alts.iter().copied().map(ParseTree::Plus0).collect(),
                _ => plus_0.iter().collect(),
            },
            ParseTree::Token(_) => vec![],
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            ParseTree::S(s) => s.display_name(),
            ParseTree::A(a) => a.display_name(),
            ParseTree::Plus0(plus_0) => plus_0.display_name(),
            ParseTree::Token(token) => token.kind.name(),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            ParseTree::S(s) => s.child_count(),
            ParseTree::A(a) => a.child_count(),
            ParseTree::Plus0(plus_0) => plus_0.child_count(),
            ParseTree::Token(_) => 0,
        }
    }
    pub fn span(&self) -> Span {
        match self {
            ParseTree::S(s) => s.span(),
            ParseTree::A(a) => a.span(),
            ParseTree::Plus0(plus_0) => plus_0.span(),
            ParseTree::Token(token) => token.span(),
        }
    }
    #[doc = "True when this node is an ambiguity cluster (any `*::Amb` variant). The"]
    #[doc = "uniform way to detect ambiguity without matching each nonterminal's enum."]
    pub fn is_amb(&self) -> bool {
        match self {
            ParseTree::S(s) => matches!(s, S::Amb(_)),
            ParseTree::A(a) => matches!(a, A::Amb(_)),
            ParseTree::Plus0(plus_0) => matches!(plus_0, Plus0::Amb(_)),
            ParseTree::Token(_) => false,
        }
    }
    #[doc = "Pointer identity of the underlying node, or `None` for tokens (by-value"]
    #[doc = "leaves that are never shared). Two parse trees with the same `node_id` are"]
    #[doc = "the same allocation, i.e. a node shared between parents in the ambiguity DAG."]
    pub fn node_id(&self) -> Option<usize> {
        match self {
            ParseTree::S(s) => Some(*s as *const _ as usize),
            ParseTree::A(a) => Some(*a as *const _ as usize),
            ParseTree::Plus0(plus_0) => Some(*plus_0 as *const _ as usize),
            ParseTree::Token(_) => None,
        }
    }
    fn unwrap_s(self) -> &'a S<'a> {
        match self {
            ParseTree::S(s) => s,
            _ => panic!(),
        }
    }
    fn unwrap_a(self) -> &'a A<'a> {
        match self {
            ParseTree::A(a) => a,
            _ => panic!(),
        }
    }
    fn unwrap_plus_0(self) -> &'a Plus0<'a> {
        match self {
            ParseTree::Plus0(plus_0) => plus_0,
            _ => panic!(),
        }
    }
    fn unwrap_token(self) -> Token {
        match self {
            ParseTree::Token(t) => t,
            _ => panic!(),
        }
    }
}
pub trait ListNode<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>>;
}
pub trait OptNode {
    type Inner;
    fn value(&self) -> Option<&Self::Inner>;
}
// S = {A ","}+
#[derive(Debug)]
pub enum S<'a> {
    Alt0 { r#as: &'a Plus0<'a>, span: Span },
    Amb(&'a [&'a S<'a>]),
}
// A = "a"
#[derive(Debug)]
pub enum A<'a> {
    Alt0 { lit_0: Token, span: Span },
    Amb(&'a [&'a A<'a>]),
}
// {A ","}+
#[derive(Debug)]
pub enum Plus0<'a> {
    // Plus_0 = {A ","}+ "," A
    Alt0 {
        as_0: &'a Plus0<'a>,
        lit_1: Token,
        a_2: &'a A<'a>,
        span: Span,
    },
    // Plus_0 = A
    Alt1 {
        a: &'a A<'a>,
        span: Span,
    },
    Amb(&'a [&'a Plus0<'a>]),
}
impl<'a> S<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::S(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            S::Alt0 { r#as, .. } => match index {
                0 => Some(ParseTree::Plus0(r#as)),
                _ => None,
            },
            S::Amb(alts) => alts.get(index).copied().map(ParseTree::S),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            S::Alt0 { .. } => 1usize,
            S::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            S::Alt0 { span, .. } => *span,
            S::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            S::Amb(_) => "Amb",
            _ => "S",
        }
    }
    pub fn r#as(&self) -> &'a Plus0<'a> {
        match self {
            S::Alt0 { r#as, .. } => r#as,
            S::Amb(_) => panic!("S is ambiguous"),
        }
    }
}
impl<'a> A<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::A(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            A::Alt0 { lit_0, .. } => match index {
                0 => Some(ParseTree::Token(*lit_0)),
                _ => None,
            },
            A::Amb(alts) => alts.get(index).copied().map(ParseTree::A),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            A::Alt0 { .. } => 1usize,
            A::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            A::Alt0 { span, .. } => *span,
            A::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            A::Amb(_) => "Amb",
            _ => "A",
        }
    }
    pub fn lit_0(&self) -> Token {
        match self {
            A::Alt0 { lit_0, .. } => *lit_0,
            A::Amb(_) => panic!("A is ambiguous"),
        }
    }
}
impl<'a> Plus0<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Plus0(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            Plus0::Alt0 {
                as_0, lit_1, a_2, ..
            } => match index {
                0 => Some(ParseTree::Plus0(as_0)),
                1 => Some(ParseTree::Token(*lit_1)),
                2 => Some(ParseTree::A(a_2)),
                _ => None,
            },
            Plus0::Alt1 { a, .. } => match index {
                0 => Some(ParseTree::A(a)),
                _ => None,
            },
            Plus0::Amb(alts) => alts.get(index).copied().map(ParseTree::Plus0),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            Plus0::Alt0 { .. } => 3usize,
            Plus0::Alt1 { .. } => 1usize,
            Plus0::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            Plus0::Alt0 { span, .. } => *span,
            Plus0::Alt1 { span, .. } => *span,
            Plus0::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            Plus0::Amb(_) => "Amb",
            _ => "{A \",\"}+",
        }
    }
    pub fn r#as(&'a self) -> impl Iterator<Item = &'a A<'a>> {
        self.iter().filter_map(|node| match node {
            ParseTree::A(r) => Some(r),
            other if other.is_amb() => panic!("Plus_0 is ambiguous"),
            _ => None,
        })
    }
}
impl<'a> ListNode<'a> for Plus0<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>> {
        let mut items = vec![];
        let mut current = self;
        loop {
            match current {
                Plus0::Alt0 {
                    as_0: rest,
                    lit_1: sep,
                    a_2: item,
                    ..
                } => {
                    items.push(item.as_parse_tree());
                    items.push(sep.as_parse_tree());
                    current = rest;
                }
                Plus0::Alt1 { a: item, .. } => {
                    items.push(item.as_parse_tree());
                    break;
                }
                Plus0::Amb(_) => {
                    items.push(ParseTree::Plus0(current));
                    break;
                }
            }
        }
        items.reverse();
        items.into_iter()
    }
}
#[derive(Debug, Clone, Copy)]
pub struct Token {
    pub kind: TokenKind,
    span: Span,
}
impl Token {
    pub fn as_parse_tree<'a>(&self) -> ParseTree<'a> {
        ParseTree::Token(*self)
    }
    pub fn span(&self) -> Span {
        self.span
    }
}
fn token_kind(terminal_id: TerminalId) -> TokenKind {
    match terminal_id {
        // ","
        TerminalId(0) => TokenKind::T0,
        // "a"
        TerminalId(1) => TokenKind::T1,
        _ => unreachable!("Unknown TerminalId: {:?}", terminal_id),
    }
}
pub struct PlusWithSepParseTreeBuilder<'a> {
    pub bump: &'a Bump,
}
impl<'a> PlusWithSepParseTreeBuilder<'a> {
    pub fn new(ctx: &'a ParseContext) -> Self {
        Self { bump: ctx.bump() }
    }
}
impl<'a> ParseTreeBuilder<ParseTree<'a>> for PlusWithSepParseTreeBuilder<'a> {
    fn new_nonterminal_node(
        &self,
        nonterminal_node: &NonterminalNode,
        children: OneOrMany<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match nonterminal_node.nonterminal_id {
            // S
            NonterminalId(0) => match nonterminal_node.return_slot {
                // S : {A ","}+.
                SlotId(1) => {
                    let [r#as] = children.into_array::<1usize>();
                    ParseTree::S(self.bump.alloc(S::Alt0 {
                        r#as: r#as.unwrap_plus_0(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // A
            NonterminalId(1) => match nonterminal_node.return_slot {
                // A : "a".
                SlotId(3) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::A(self.bump.alloc(A::Alt0 {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Plus_0
            NonterminalId(2) => match nonterminal_node.return_slot {
                // {A ","}+ : {A ","}+ "," A.
                SlotId(7) => {
                    let [as_0, lit_1, a_2] = children.into_array::<3usize>();
                    ParseTree::Plus0(self.bump.alloc(Plus0::Alt0 {
                        as_0: as_0.unwrap_plus_0(),
                        lit_1: lit_1.unwrap_token(),
                        a_2: a_2.unwrap_a(),
                        span: nonterminal_node.span,
                    }))
                }
                // {A ","}+ : A.
                SlotId(9) => {
                    let [a] = children.into_array::<1usize>();
                    ParseTree::Plus0(self.bump.alloc(Plus0::Alt1 {
                        a: a.unwrap_a(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            _ => unreachable!(),
        }
    }
    fn new_token(&self, terminal_node: &TerminalNode) -> ParseTree<'a> {
        ParseTree::Token(Token {
            kind: token_kind(terminal_node.terminal_id),
            span: terminal_node.span,
        })
    }
    fn new_ambiguity_node(
        &self,
        parent: NonterminalId,
        alternatives: Vec<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match parent {
            crate::grammar_data::S => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_s()));
                ParseTree::S(self.bump.alloc(S::Amb(slice)))
            }
            crate::grammar_data::A => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_a()));
                ParseTree::A(self.bump.alloc(A::Amb(slice)))
            }
            crate::grammar_data::PLUS_0 => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_plus_0()));
                ParseTree::Plus0(self.bump.alloc(Plus0::Amb(slice)))
            }
            _ => unreachable!("nonterminal cannot be ambiguous"),
        }
    }
}
pub fn create_parse_tree<'a>(
    root_id: SPPFNodeId,
    nonterminal_id: NonterminalId,
    parser: &PlusWithSepParser,
    builder: &PlusWithSepParseTreeBuilder<'a>,
) -> ParseTree<'a> {
    match nonterminal_id {
        crate::grammar_data::S => ParseTree::S(create_parse_tree_s(root_id, parser, builder)),
        crate::grammar_data::A => ParseTree::A(create_parse_tree_a(root_id, parser, builder)),
        crate::grammar_data::PLUS_0 => {
            ParseTree::Plus0(create_parse_tree_plus_0(root_id, parser, builder))
        }
        _ => panic!(),
    }
}
pub fn create_parse_tree_s<'a>(
    root_id: SPPFNodeId,
    parser: &PlusWithSepParser,
    builder: &PlusWithSepParseTreeBuilder<'a>,
) -> &'a S<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_s()
}
pub fn create_parse_tree_a<'a>(
    root_id: SPPFNodeId,
    parser: &PlusWithSepParser,
    builder: &PlusWithSepParseTreeBuilder<'a>,
) -> &'a A<'a> {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_a()
}
pub fn create_parse_tree_plus_0<'a>(
    root_id: SPPFNodeId,
    parser: &PlusWithSepParser,
    builder: &PlusWithSepParseTreeBuilder<'a>,
) -> &'a Plus0<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_plus_0()
}
const SEXPR_LAYOUT_NAME: Option<&str> = None;
pub fn to_sexpr(node: ParseTree<'_>) -> String {
    to_sexpr_with(node, SexprOptions::default())
}
pub fn to_sexpr_with(node: ParseTree<'_>, options: SexprOptions) -> String {
    let mut indegree = FxHashMap::default();
    count_sexpr_indegree(node, options, &mut FxHashSet::default(), &mut indegree);
    let mut printer = SexprPrinter {
        options,
        indegree,
        labels: FxHashMap::default(),
        next_label: 1,
    };
    let mut s = String::new();
    printer.print(node, 0, &mut s).expect("error");
    s.push('\n');
    s
}
fn sexpr_hidden(node: ParseTree<'_>, options: SexprOptions) -> bool {
    !options.show_layout && SEXPR_LAYOUT_NAME == Some(node.display_name())
}
fn sexpr_children<'a>(node: ParseTree<'a>, options: SexprOptions) -> Vec<ParseTree<'a>> {
    node.children()
        .into_iter()
        .filter(|c| !sexpr_hidden(*c, options))
        .collect()
}
fn count_sexpr_indegree(
    node: ParseTree<'_>,
    options: SexprOptions,
    visited: &mut FxHashSet<usize>,
    indegree: &mut FxHashMap<usize, u32>,
) {
    if let Some(id) = node.node_id() {
        *indegree.entry(id).or_insert(0) += 1;
        if !visited.insert(id) {
            return;
        }
    }
    for child in sexpr_children(node, options) {
        count_sexpr_indegree(child, options, visited, indegree);
    }
}
struct SexprPrinter {
    options: SexprOptions,
    indegree: FxHashMap<usize, u32>,
    labels: FxHashMap<usize, u32>,
    next_label: u32,
}
impl SexprPrinter {
    fn print(&mut self, node: ParseTree<'_>, indent: usize, w: &mut impl Write) -> fmt::Result {
        write!(w, "{:indent$}", "")?;
        self.print_content(node, indent, w)
    }
    fn print_content(
        &mut self,
        node: ParseTree<'_>,
        indent: usize,
        w: &mut impl Write,
    ) -> fmt::Result {
        let mut prefix = String::new();
        if let Some(id) = node.node_id() {
            if self.indegree.get(&id).copied().unwrap_or(0) > 1 {
                if let Some(&label) = self.labels.get(&id) {
                    return write!(w, "#{}#", label);
                }
                let label = self.next_label;
                self.next_label += 1;
                self.labels.insert(id, label);
                prefix = format!("#{}=", label);
            }
        }
        let children = sexpr_children(node, self.options);
        if children.is_empty() {
            write!(w, "{}{}", prefix, node.display_name())
        } else if children
            .iter()
            .all(|c| sexpr_children(*c, self.options).is_empty())
        {
            write!(w, "{}({}", prefix, node.display_name())?;
            for child in children {
                write!(w, " ")?;
                self.print_content(child, indent, w)?;
            }
            write!(w, ")")
        } else {
            write!(w, "{}({}", prefix, node.display_name())?;
            for child in children {
                writeln!(w)?;
                self.print(child, indent + 2, w)?;
            }
            write!(w, ")")
        }
    }
}
/// Converts a parse tree to a JSON string of nodes and edges, for visualization.
pub fn to_json(node: ParseTree<'_>) -> String {
    let mut nodes = Vec::new();
    let mut edges = Vec::new();
    let mut next_id = 0u32;
    let mut seen = FxHashMap::default();
    build_json_graph(node, &mut nodes, &mut edges, &mut next_id, &mut seen);
    let result = serde_json :: json ! ({ "layout_name" : None :: < & str > , "nodes" : nodes , "edges" : edges });
    result.to_string()
}
fn build_json_graph(
    node: ParseTree<'_>,
    nodes: &mut Vec<serde_json::Value>,
    edges: &mut Vec<serde_json::Value>,
    next_id: &mut u32,
    seen: &mut FxHashMap<usize, u32>,
) -> u32 {
    if let Some(id) = node.node_id() {
        if let Some(&existing) = seen.get(&id) {
            return existing;
        }
    }
    let my_id = *next_id;
    *next_id += 1;
    if let Some(id) = node.node_id() {
        seen.insert(id, my_id);
    }
    let span = node.span();
    let kind = if node.is_amb() {
        "Amb"
    } else if matches!(node, ParseTree::Token(_)) {
        "Token"
    } else {
        "Nonterminal"
    };
    nodes . push (serde_json :: json ! ({ "id" : my_id , "kind" : kind , "label" : node . display_name () , "start" : span . left_extent , "end" : span . right_extent })) ;
    for child in node.children() {
        let child_id = build_json_graph(child, nodes, edges, next_id, seen);
        edges.push(serde_json :: json ! ({ "src" : my_id , "dest" : child_id }));
    }
    my_id
}
