// @generated by iguana. Do not edit manually.

use crate::parser::LayoutNonterminalParser;
use core::fmt;
use iguana_runtime::{
    ids::{NonterminalId, SlotId, TerminalId},
    parse_tree::{Bump, OneOrMany, ParseContext, ParseTreeBuilder, visit_sppf},
    parser::Parser,
    sppf::{NonterminalNode, SPPFNodeId, Span, TerminalNode},
};
use std::{fmt::Write, vec::IntoIter};
#[derive(Debug, Clone, Copy)]
pub enum TokenKind {
    // WhiteSpace
    T0,
    // Comment
    T1,
    // "x"
    T2,
}
impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            TokenKind::T0 => "WhiteSpace",
            TokenKind::T1 => "Comment",
            TokenKind::T2 => "\"x\"",
            _ => unreachable!(),
        }
    }
}
#[derive(Debug)]
pub struct Start<T, L> {
    pub before: L,
    pub node: T,
    pub after: L,
    pub span: Span,
}
#[derive(Debug, Clone, Copy)]
pub enum ParseTree<'a> {
    S(&'a S),
    Layout(&'a Layout<'a>),
    // (WhiteSpace | Comment)
    Alt0(&'a Alt0<'a>),
    // (WhiteSpace | Comment)+
    Plus0(&'a Plus0<'a>),
    // (WhiteSpace | Comment)+?
    Opt0(&'a Opt0<'a>),
    // (WhiteSpace | Comment)*
    Star0(&'a Star0<'a>),
    // S
    StartS(&'a Start<&'a S, &'a Layout<'a>>),
    Token(Token),
}
impl<'a> ParseTree<'a> {
    pub fn children(&self) -> Vec<ParseTree<'a>> {
        match self {
            ParseTree::S(s) => (0..s.child_count()).filter_map(|i| s.child(i)).collect(),
            ParseTree::Layout(layout) => (0..layout.child_count())
                .filter_map(|i| layout.child(i))
                .collect(),
            ParseTree::Alt0(alt_0) => (0..alt_0.child_count())
                .filter_map(|i| alt_0.child(i))
                .collect(),
            ParseTree::Plus0(plus_0) => plus_0.iter().collect(),
            ParseTree::Opt0(opt_0) => (0..opt_0.child_count())
                .filter_map(|i| opt_0.child(i))
                .collect(),
            ParseTree::Star0(star_0) => star_0.iter().collect(),
            ParseTree::StartS(start_s) => (0..start_s.child_count())
                .filter_map(|i| start_s.child(i))
                .collect(),
            ParseTree::Token(_) => vec![],
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            ParseTree::S(s) => s.display_name(),
            ParseTree::Layout(layout) => layout.display_name(),
            ParseTree::Alt0(alt_0) => alt_0.display_name(),
            ParseTree::Plus0(plus_0) => plus_0.display_name(),
            ParseTree::Opt0(opt_0) => opt_0.display_name(),
            ParseTree::Star0(star_0) => star_0.display_name(),
            ParseTree::StartS(start_s) => start_s.display_name(),
            ParseTree::Token(token) => token.kind.name(),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            ParseTree::S(s) => s.child_count(),
            ParseTree::Layout(layout) => layout.child_count(),
            ParseTree::Alt0(alt_0) => alt_0.child_count(),
            ParseTree::Plus0(plus_0) => plus_0.child_count(),
            ParseTree::Opt0(opt_0) => opt_0.child_count(),
            ParseTree::Star0(star_0) => star_0.child_count(),
            ParseTree::StartS(start_s) => start_s.child_count(),
            ParseTree::Token(_) => 0,
        }
    }
    pub fn span(&self) -> Span {
        match self {
            ParseTree::S(s) => s.span(),
            ParseTree::Layout(layout) => layout.span(),
            ParseTree::Alt0(alt_0) => alt_0.span(),
            ParseTree::Plus0(plus_0) => plus_0.span(),
            ParseTree::Opt0(opt_0) => opt_0.span(),
            ParseTree::Star0(star_0) => star_0.span(),
            ParseTree::StartS(start_s) => start_s.span(),
            ParseTree::Token(token) => token.span(),
        }
    }
    fn unwrap_s(self) -> &'a S {
        match self {
            ParseTree::S(s) => s,
            _ => panic!(),
        }
    }
    fn unwrap_layout(self) -> &'a Layout<'a> {
        match self {
            ParseTree::Layout(layout) => layout,
            _ => panic!(),
        }
    }
    fn unwrap_alt_0(self) -> &'a Alt0<'a> {
        match self {
            ParseTree::Alt0(alt_0) => alt_0,
            _ => panic!(),
        }
    }
    fn unwrap_plus_0(self) -> &'a Plus0<'a> {
        match self {
            ParseTree::Plus0(plus_0) => plus_0,
            _ => panic!(),
        }
    }
    fn unwrap_opt_0(self) -> &'a Opt0<'a> {
        match self {
            ParseTree::Opt0(opt_0) => opt_0,
            _ => panic!(),
        }
    }
    fn unwrap_star_0(self) -> &'a Star0<'a> {
        match self {
            ParseTree::Star0(star_0) => star_0,
            _ => panic!(),
        }
    }
    fn unwrap_start_s(self) -> &'a Start<&'a S, &'a Layout<'a>> {
        match self {
            ParseTree::StartS(start_s) => start_s,
            _ => panic!(),
        }
    }
    fn unwrap_token(self) -> Token {
        match self {
            ParseTree::Token(t) => t,
            _ => panic!(),
        }
    }
}
pub trait ListNode<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>>;
}
pub trait OptNode {
    type Inner;
    fn value(&self) -> Option<&Self::Inner>;
}
// S = "x"
#[derive(Debug)]
pub struct S {
    pub lit_0: Token,
    pub span: Span,
}
// Layout = (WhiteSpace | Comment)*
#[derive(Debug)]
pub struct Layout<'a> {
    pub star_0: &'a Star0<'a>,
    pub span: Span,
}
// (WhiteSpace | Comment)
#[derive(Debug)]
pub enum Alt0<'a> {
    // Alt_0 = WhiteSpace
    Alt0 { white_space: Token, span: Span },
    // Alt_0 = Comment
    Alt1 { comment: Token, span: Span },
    Amb(&'a [&'a Alt0<'a>]),
}
// (WhiteSpace | Comment)+
#[derive(Debug)]
pub enum Plus0<'a> {
    // Plus_0 = (WhiteSpace | Comment)+ (WhiteSpace | Comment)
    Alt0 {
        plus_0: &'a Plus0<'a>,
        alt_0: &'a Alt0<'a>,
        span: Span,
    },
    // Plus_0 = (WhiteSpace | Comment)
    Alt1 {
        alt_0: &'a Alt0<'a>,
        span: Span,
    },
    Amb(&'a [&'a Plus0<'a>]),
}
// (WhiteSpace | Comment)+?
#[derive(Debug)]
pub enum Opt0<'a> {
    // Opt_0 = (WhiteSpace | Comment)+
    Alt0 { plus_0: &'a Plus0<'a>, span: Span },
    // Opt_0 =
    Alt1 { span: Span },
    Amb(&'a [&'a Opt0<'a>]),
}
// (WhiteSpace | Comment)*
#[derive(Debug)]
pub struct Star0<'a> {
    pub opt_0: &'a Opt0<'a>,
    pub span: Span,
}
impl<'a> S {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::S(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some({
                let lit_0 = &self.lit_0;
                ParseTree::Token(*lit_0)
            }),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "S"
    }
}
impl<'a> Layout<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Layout(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some({
                let star_0 = &self.star_0;
                ParseTree::Star0(star_0)
            }),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "Layout"
    }
    pub fn white_spaces(&self) -> impl Iterator<Item = Token> {
        self.star_0.white_spaces()
    }
    pub fn comments(&self) -> impl Iterator<Item = Token> {
        self.star_0.comments()
    }
}
impl<'a> Alt0<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Alt0(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            Alt0::Alt0 { white_space, .. } => match index {
                0 => Some(ParseTree::Token(*white_space)),
                _ => None,
            },
            Alt0::Alt1 { comment, .. } => match index {
                0 => Some(ParseTree::Token(*comment)),
                _ => None,
            },
            Alt0::Amb(alts) => alts.get(index).copied().map(ParseTree::Alt0),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            Alt0::Alt0 { .. } => 1usize,
            Alt0::Alt1 { .. } => 1usize,
            Alt0::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            Alt0::Alt0 { span, .. } => *span,
            Alt0::Alt1 { span, .. } => *span,
            Alt0::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            Alt0::Amb(_) => "Amb",
            _ => "(WhiteSpace | Comment)",
        }
    }
}
impl<'a> Plus0<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Plus0(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            Plus0::Alt0 { plus_0, alt_0, .. } => match index {
                0 => Some(ParseTree::Plus0(plus_0)),
                1 => Some(ParseTree::Alt0(alt_0)),
                _ => None,
            },
            Plus0::Alt1 { alt_0, .. } => match index {
                0 => Some(ParseTree::Alt0(alt_0)),
                _ => None,
            },
            Plus0::Amb(alts) => alts.get(index).copied().map(ParseTree::Plus0),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            Plus0::Alt0 { .. } => 2usize,
            Plus0::Alt1 { .. } => 1usize,
            Plus0::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            Plus0::Alt0 { span, .. } => *span,
            Plus0::Alt1 { span, .. } => *span,
            Plus0::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            Plus0::Amb(_) => "Amb",
            _ => "(WhiteSpace | Comment)+",
        }
    }
    pub fn white_spaces(&'a self) -> impl Iterator<Item = Token> {
        self.iter().filter_map(|node| match node {
            ParseTree::Alt0(Alt0::Alt0 { white_space, .. }) => Some(*white_space),
            _ => None,
        })
    }
    pub fn comments(&'a self) -> impl Iterator<Item = Token> {
        self.iter().filter_map(|node| match node {
            ParseTree::Alt0(Alt0::Alt1 { comment, .. }) => Some(*comment),
            _ => None,
        })
    }
}
impl<'a> Opt0<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Opt0(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match self {
            Opt0::Alt0 { plus_0, .. } => match index {
                0 => Some(ParseTree::Plus0(plus_0)),
                _ => None,
            },
            Opt0::Alt1 { .. } => match index {
                _ => None,
            },
            Opt0::Amb(alts) => alts.get(index).copied().map(ParseTree::Opt0),
        }
    }
    pub fn child_count(&self) -> usize {
        match self {
            Opt0::Alt0 { .. } => 1usize,
            Opt0::Alt1 { .. } => 0usize,
            Opt0::Amb(alts) => alts.len(),
        }
    }
    pub fn span(&self) -> Span {
        match self {
            Opt0::Alt0 { span, .. } => *span,
            Opt0::Alt1 { span, .. } => *span,
            Opt0::Amb(alts) => alts[0].span(),
        }
    }
    pub fn display_name(&self) -> &'static str {
        match self {
            Opt0::Amb(_) => "Amb",
            _ => "(WhiteSpace | Comment)+?",
        }
    }
    pub fn white_spaces(&'a self) -> impl Iterator<Item = Token> {
        self.value()
            .into_iter()
            .flat_map(|inner| inner.white_spaces())
    }
    pub fn comments(&'a self) -> impl Iterator<Item = Token> {
        self.value().into_iter().flat_map(|inner| inner.comments())
    }
}
impl<'a> Star0<'a> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::Star0(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some({
                let opt_0 = &self.opt_0;
                ParseTree::Opt0(opt_0)
            }),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        1usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "(WhiteSpace | Comment)*"
    }
    pub fn white_spaces(&self) -> impl Iterator<Item = Token> {
        self.opt_0.white_spaces()
    }
    pub fn comments(&self) -> impl Iterator<Item = Token> {
        self.opt_0.comments()
    }
}
impl<'a> Start<&'a S, &'a Layout<'a>> {
    pub fn as_parse_tree(&'a self) -> ParseTree<'a> {
        ParseTree::StartS(self)
    }
    pub fn child(&self, index: usize) -> Option<ParseTree<'a>> {
        match index {
            0 => Some(ParseTree::Layout(self.before)),
            1 => Some(ParseTree::S(self.node)),
            2 => Some(ParseTree::Layout(self.after)),
            _ => None,
        }
    }
    pub fn child_count(&self) -> usize {
        3usize
    }
    pub fn span(&self) -> Span {
        self.span
    }
    pub fn display_name(&self) -> &'static str {
        "S"
    }
}
impl<'a> ListNode<'a> for Plus0<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>> {
        let mut items = vec![];
        let mut current = self;
        loop {
            match current {
                Plus0::Alt0 {
                    plus_0: rest,
                    alt_0: item,
                    ..
                } => {
                    items.push(item.as_parse_tree());
                    current = rest;
                }
                Plus0::Alt1 { alt_0: item, .. } => {
                    items.push(item.as_parse_tree());
                    break;
                }
                Plus0::Amb(_) => panic!("unexpected ambiguity in list node"),
            }
        }
        items.reverse();
        items.into_iter()
    }
}
impl<'a> ListNode<'a> for Star0<'a> {
    fn iter(&'a self) -> IntoIter<ParseTree<'a>> {
        match self.opt_0 {
            Opt0::Alt0 { plus_0: opt_0, .. } => opt_0.iter(),
            Opt0::Alt1 { .. } => vec![].into_iter(),
            Opt0::Amb(_) => panic!("unexpected ambiguity in list node"),
        }
    }
}
impl<'a> OptNode for Opt0<'a> {
    type Inner = Plus0<'a>;
    fn value(&self) -> Option<&Self::Inner> {
        match self {
            Opt0::Alt0 { plus_0, .. } => Some(plus_0),
            Opt0::Alt1 { .. } => None,
            Opt0::Amb(_) => panic!("unexpected ambiguity in optional node"),
        }
    }
}
impl<'a> Alt0<'a> {
    pub fn as_white_space(&self) -> Option<&Token> {
        match self {
            Alt0::Alt0 { white_space, .. } => Some(white_space),
            _ => None,
        }
    }
    pub fn as_comment(&self) -> Option<&Token> {
        match self {
            Alt0::Alt1 { comment, .. } => Some(comment),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy)]
pub struct Token {
    pub kind: TokenKind,
    span: Span,
}
impl Token {
    pub fn as_parse_tree<'a>(&self) -> ParseTree<'a> {
        ParseTree::Token(*self)
    }
    pub fn span(&self) -> Span {
        self.span
    }
}
fn token_kind(terminal_id: TerminalId) -> TokenKind {
    match terminal_id {
        // WhiteSpace
        TerminalId(0) => TokenKind::T0,
        // Comment
        TerminalId(1) => TokenKind::T1,
        // "x"
        TerminalId(2) => TokenKind::T2,
        _ => unreachable!("Unknown TerminalId: {:?}", terminal_id),
    }
}
pub struct LayoutNonterminalParseTreeBuilder<'a> {
    pub bump: &'a Bump,
}
impl<'a> LayoutNonterminalParseTreeBuilder<'a> {
    pub fn new(ctx: &'a ParseContext) -> Self {
        Self { bump: ctx.bump() }
    }
}
impl<'a> ParseTreeBuilder<ParseTree<'a>> for LayoutNonterminalParseTreeBuilder<'a> {
    fn new_nonterminal_node(
        &self,
        nonterminal_node: &NonterminalNode,
        children: OneOrMany<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match nonterminal_node.nonterminal_id {
            // S
            NonterminalId(0) => match nonterminal_node.return_slot {
                // S : "x".
                SlotId(1) => {
                    let [lit_0] = children.into_array::<1usize>();
                    ParseTree::S(self.bump.alloc(S {
                        lit_0: lit_0.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Layout
            NonterminalId(1) => match nonterminal_node.return_slot {
                // Layout : (WhiteSpace | Comment)*.
                SlotId(3) => {
                    let [star_0] = children.into_array::<1usize>();
                    ParseTree::Layout(self.bump.alloc(Layout {
                        star_0: star_0.unwrap_star_0(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Alt_0
            NonterminalId(2) => match nonterminal_node.return_slot {
                // (WhiteSpace | Comment) : WhiteSpace.
                SlotId(5) => {
                    let [white_space] = children.into_array::<1usize>();
                    ParseTree::Alt0(self.bump.alloc(Alt0::Alt0 {
                        white_space: white_space.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                // (WhiteSpace | Comment) : Comment.
                SlotId(7) => {
                    let [comment] = children.into_array::<1usize>();
                    ParseTree::Alt0(self.bump.alloc(Alt0::Alt1 {
                        comment: comment.unwrap_token(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Plus_0
            NonterminalId(3) => match nonterminal_node.return_slot {
                // (WhiteSpace | Comment)+ : (WhiteSpace | Comment)+ (WhiteSpace | Comment).
                SlotId(10) => {
                    let [plus_0, alt_0] = children.into_array::<2usize>();
                    ParseTree::Plus0(self.bump.alloc(Plus0::Alt0 {
                        plus_0: plus_0.unwrap_plus_0(),
                        alt_0: alt_0.unwrap_alt_0(),
                        span: nonterminal_node.span,
                    }))
                }
                // (WhiteSpace | Comment)+ : (WhiteSpace | Comment).
                SlotId(12) => {
                    let [alt_0] = children.into_array::<1usize>();
                    ParseTree::Plus0(self.bump.alloc(Plus0::Alt1 {
                        alt_0: alt_0.unwrap_alt_0(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Opt_0
            NonterminalId(4) => match nonterminal_node.return_slot {
                // (WhiteSpace | Comment)+? : (WhiteSpace | Comment)+.
                SlotId(14) => {
                    let [plus_0] = children.into_array::<1usize>();
                    ParseTree::Opt0(self.bump.alloc(Opt0::Alt0 {
                        plus_0: plus_0.unwrap_plus_0(),
                        span: nonterminal_node.span,
                    }))
                }
                // (WhiteSpace | Comment)+? : .
                SlotId(15) => {
                    let [] = children.into_array::<0usize>();
                    ParseTree::Opt0(self.bump.alloc(Opt0::Alt1 {
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // Star_0
            NonterminalId(5) => match nonterminal_node.return_slot {
                // (WhiteSpace | Comment)* : (WhiteSpace | Comment)+?.
                SlotId(17) => {
                    let [opt_0] = children.into_array::<1usize>();
                    ParseTree::Star0(self.bump.alloc(Star0 {
                        opt_0: opt_0.unwrap_opt_0(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            // StartS
            NonterminalId(6) => match nonterminal_node.return_slot {
                // S : Layout start:S Layout.
                SlotId(21) => {
                    let [layout_0, start, layout_2] = children.into_array::<3usize>();
                    ParseTree::StartS(self.bump.alloc(Start {
                        before: layout_0.unwrap_layout(),
                        node: start.unwrap_s(),
                        after: layout_2.unwrap_layout(),
                        span: nonterminal_node.span,
                    }))
                }
                _ => unreachable!(),
            },
            _ => unreachable!(),
        }
    }
    fn new_token(&self, terminal_node: &TerminalNode) -> ParseTree<'a> {
        ParseTree::Token(Token {
            kind: token_kind(terminal_node.terminal_id),
            span: terminal_node.span,
        })
    }
    fn new_ambiguity_node(
        &self,
        parent: NonterminalId,
        alternatives: Vec<ParseTree<'a>>,
    ) -> ParseTree<'a> {
        match parent {
            crate::grammar_data::ALT_0 => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_alt_0()));
                ParseTree::Alt0(self.bump.alloc(Alt0::Amb(slice)))
            }
            crate::grammar_data::PLUS_0 => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_plus_0()));
                ParseTree::Plus0(self.bump.alloc(Plus0::Amb(slice)))
            }
            crate::grammar_data::OPT_0 => {
                let slice = self
                    .bump
                    .alloc_slice_fill_iter(alternatives.into_iter().map(|a| a.unwrap_opt_0()));
                ParseTree::Opt0(self.bump.alloc(Opt0::Amb(slice)))
            }
            _ => unreachable!("nonterminal cannot be ambiguous"),
        }
    }
}
pub fn create_parse_tree<'a>(
    root_id: SPPFNodeId,
    nonterminal_id: NonterminalId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> ParseTree<'a> {
    match nonterminal_id {
        crate::grammar_data::S => ParseTree::S(create_parse_tree_s(root_id, parser, builder)),
        crate::grammar_data::LAYOUT => {
            ParseTree::Layout(create_parse_tree_layout(root_id, parser, builder))
        }
        crate::grammar_data::ALT_0 => {
            ParseTree::Alt0(create_parse_tree_alt_0(root_id, parser, builder))
        }
        crate::grammar_data::PLUS_0 => {
            ParseTree::Plus0(create_parse_tree_plus_0(root_id, parser, builder))
        }
        crate::grammar_data::OPT_0 => {
            ParseTree::Opt0(create_parse_tree_opt_0(root_id, parser, builder))
        }
        crate::grammar_data::STAR_0 => {
            ParseTree::Star0(create_parse_tree_star_0(root_id, parser, builder))
        }
        crate::grammar_data::START_S => {
            ParseTree::StartS(create_parse_tree_start_s(root_id, parser, builder))
        }
        _ => panic!(),
    }
}
pub fn create_parse_tree_s<'a>(
    root_id: SPPFNodeId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> &'a S {
    visit_sppf(root_id, parser, builder).unwrap_one().unwrap_s()
}
pub fn create_parse_tree_layout<'a>(
    root_id: SPPFNodeId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> &'a Layout<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_layout()
}
pub fn create_parse_tree_alt_0<'a>(
    root_id: SPPFNodeId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> &'a Alt0<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_alt_0()
}
pub fn create_parse_tree_plus_0<'a>(
    root_id: SPPFNodeId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> &'a Plus0<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_plus_0()
}
pub fn create_parse_tree_opt_0<'a>(
    root_id: SPPFNodeId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> &'a Opt0<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_opt_0()
}
pub fn create_parse_tree_star_0<'a>(
    root_id: SPPFNodeId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> &'a Star0<'a> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_star_0()
}
pub fn create_parse_tree_start_s<'a>(
    root_id: SPPFNodeId,
    parser: &LayoutNonterminalParser,
    builder: &LayoutNonterminalParseTreeBuilder<'a>,
) -> &'a Start<&'a S, &'a Layout<'a>> {
    visit_sppf(root_id, parser, builder)
        .unwrap_one()
        .unwrap_start_s()
}
pub fn to_sexpr(node: ParseTree<'_>) -> String {
    let mut s = String::new();
    node_to_sexpr(node, 0, &mut s).expect("error");
    s
}
fn node_to_sexpr(node: ParseTree<'_>, indent: usize, w: &mut impl Write) -> fmt::Result {
    let children = node.children();
    if children.is_empty() {
        writeln!(w, "{:indent$}{}", "", node.display_name())
    } else {
        writeln!(w, "{:indent$}({}", "", node.display_name())?;
        for child in children {
            node_to_sexpr(child, indent + 2, w)?;
        }
        writeln!(w, "{:indent$})", "")
    }
}
/// Converts a parse tree to JSON format for visualization.

/// Returns a JSON string with nodes and edges arrays.
pub fn to_json(node: ParseTree<'_>) -> String {
    let mut nodes = Vec::new();
    let mut edges = Vec::new();
    let mut next_id = 0u32;
    build_json_graph(node, &mut nodes, &mut edges, &mut next_id);
    let result = serde_json :: json ! ({ "layout_name" : Some ("Layout") , "nodes" : nodes , "edges" : edges });
    result.to_string()
}
fn build_json_graph(
    node: ParseTree<'_>,
    nodes: &mut Vec<serde_json::Value>,
    edges: &mut Vec<serde_json::Value>,
    next_id: &mut u32,
) -> u32 {
    let my_id = *next_id;
    *next_id += 1;
    let span = node.span();
    let kind = match node {
        ParseTree::Token(_) => "Token",
        ParseTree::Alt0(e) if matches!(e, Alt0::Amb(_)) => "Amb",
        ParseTree::Plus0(e) if matches!(e, Plus0::Amb(_)) => "Amb",
        ParseTree::Opt0(e) if matches!(e, Opt0::Amb(_)) => "Amb",
        _ => "Nonterminal",
    };
    nodes . push (serde_json :: json ! ({ "id" : my_id , "kind" : kind , "label" : node . display_name () , "start" : span . left_extent , "end" : span . right_extent })) ;
    for child in node.children() {
        let child_id = build_json_graph(child, nodes, edges, next_id);
        edges.push(serde_json :: json ! ({ "src" : my_id , "dest" : child_id }));
    }
    my_id
}
