// @generated by iguana. Do not edit manually.

use iguana_runtime::{
    dfa::{Dfa, State},
    ids::TerminalId,
    input::Input,
    scanner::{Lookup, MatchMemo, Scanner},
};
const MATCH_MEMO_WORDS: usize = 1;
static DFA_0: Dfa = Dfa::new(&[
    State::new(&[(' ', ' ', 1)], Some(TerminalId(0))),
    State::new(&[(' ', ' ', 1)], Some(TerminalId(0))),
]);
static DFA_1: Dfa = Dfa::new(&[
    State::new(&[('a', 'a', 1)], None),
    State::new(&[], Some(TerminalId(1))),
]);
static DFA_2: Dfa = Dfa::new(&[
    State::new(&[('-', '-', 1)], None),
    State::new(&[], Some(TerminalId(2))),
]);
static DFA_3: Dfa = Dfa::new(&[
    State::new(&[('+', '+', 1)], None),
    State::new(&[], Some(TerminalId(3))),
]);
pub struct PrefixAboveBinaryScanner<'i> {
    pub input: &'i Input,
    memo: MatchMemo<MATCH_MEMO_WORDS>,
}
impl<'i> PrefixAboveBinaryScanner<'i> {
    pub fn new(input: &'i Input) -> Self {
        let memo = MatchMemo::new(input.len() as usize);
        Self { input, memo }
    }
    // WS = ([ ]*)
    pub fn match_terminal_0(&self, input_index: u32) -> Option<u32> {
        self.scan(&DFA_0, input_index)
    }
    // "a" = a
    pub fn match_terminal_1(&self, input_index: u32) -> Option<u32> {
        self.scan(&DFA_1, input_index)
    }
    // "-" = -
    pub fn match_terminal_2(&self, input_index: u32) -> Option<u32> {
        self.scan(&DFA_2, input_index)
    }
    // "+" = +
    pub fn match_terminal_3(&self, input_index: u32) -> Option<u32> {
        self.scan(&DFA_3, input_index)
    }
}
impl Scanner for PrefixAboveBinaryScanner<'_> {
    fn match_token(&mut self, terminal_id: TerminalId, input_index: u32) -> Option<u32> {
        if let Some(lookup) = self.memo.get(terminal_id, input_index) {
            return match lookup {
                Lookup::Match(end) => Some(end),
                Lookup::Fail => None,
            };
        }
        let result = match terminal_id {
            TerminalId(0) => self.match_terminal_0(input_index),
            TerminalId(1) => self.match_terminal_1(input_index),
            TerminalId(2) => self.match_terminal_2(input_index),
            TerminalId(3) => self.match_terminal_3(input_index),
            TerminalId(5) => {
                if input_index == self.input.len() {
                    Some(input_index)
                } else {
                    None
                }
            }
            _ => {
                unreachable!("Unknown token type: {terminal_id}");
            }
        };
        match result {
            Some(end) => self.memo.insert_match(terminal_id, input_index, end),
            None => self.memo.insert_fail(terminal_id, input_index),
        }
        result
    }
    fn char_at(&self, i: u32) -> Option<char> {
        self.input.char_at(i)
    }
}
