use std::{
    fs,
    io::{self, Write},
    path::Path,
    time::Instant,
};

use crate::{
    generator::{
        id::{BindingIds, EndSlot, NonterminalIds, SlotIds, TerminalIds},
        parse_tree_gen::ParseTreeGen,
        parser_gen::ParserGen,
        terminal_sets::{SetIds, terminal_sets},
    },
    grammar::{
        def::Grammar,
        first_follow::FirstFollowSets,
        slot::Slot,
        symbols::{Definition, Symbol},
    },
};

/// Rejects a `!>>>` restriction whose layout the generated parser cannot
/// measure.
///
/// The restriction is checked at the end of the layout that follows a symbol,
/// so generating it means finding that end. The parser finds it with a scanner
/// match when the layout is a terminal, and with one deterministic parse when
/// the layout is LL(1). Any other layout can end at several positions, which
/// takes a GLL recognizer the generator does not have.
///
/// The generated parser checks postconditions only on rule references.
/// Restrictions on other symbols do not require a layout probe.
fn check_layout_aware_follow(
    grammar: &Grammar,
    ff: &FirstFollowSets,
    config: GenConfig,
) -> io::Result<()> {
    let uses_probe = grammar.nonterminals().any(|nonterminal| {
        grammar.alternatives(nonterminal).iter().any(|alternative| {
            alternative.symbols.iter().any(|symbol| {
                symbol.as_identifier().is_some()
                    && !symbol.restrictions().layout_aware_follow.is_empty()
            })
        })
    });
    if !uses_probe {
        return Ok(());
    }

    // Layout insertion turns a `!>>>` into a plain `!>>` in a rule without
    // layout, so every restriction reaching this point has a layout to
    // measure.
    let layout = grammar
        .layout
        .as_ref()
        .and_then(Symbol::as_identifier)
        .expect("a `!>>>` restriction survives only in a rule with layout");
    // A terminal layout is a scanner match, which always has one end.
    let Definition::Nonterminal(nonterminal) = grammar.definition(layout.resolve()) else {
        return Ok(());
    };
    let is_ll1 = ff.is_ll1(nonterminal);
    if config.ll1_optimization && is_ll1 {
        return Ok(());
    }
    let name = &nonterminal.name;
    let message = if is_ll1 {
        format!("`!>>>` requires the `ll1` option when layout `{name}` is an LL(1) syntax rule")
    } else {
        format!("`!>>>` requires layout `{name}` to be a lexical rule or an LL(1) syntax rule")
    };
    Err(io::Error::other(message))
}

fn collect_binding_names(symbol: &Symbol, binding_ids: &mut BindingIds) {
    if let Symbol::Binding { name, .. } = symbol {
        binding_ids.insert(name.clone());
    }
    match symbol {
        Symbol::Labeled { symbol, .. }
        | Symbol::Binding { symbol, .. }
        | Symbol::Restricted { symbol, .. }
        | Symbol::Exclude { symbol, .. }
        | Symbol::Opt(symbol) => collect_binding_names(symbol, binding_ids),
        Symbol::Group(symbols) | Symbol::Alt(symbols) => {
            for s in symbols {
                collect_binding_names(s, binding_ids);
            }
        }
        Symbol::Star(symbol, sep) | Symbol::Plus(symbol, sep) => {
            collect_binding_names(symbol, binding_ids);
            if let Some(sep) = sep {
                collect_binding_names(sep, binding_ids);
            }
        }
        Symbol::Identifier(_)
        | Symbol::Literal(_)
        | Symbol::Call { .. }
        | Symbol::Condition(_)
        | Symbol::Return(_) => {}
    }
}

#[derive(Clone, Copy)]
pub struct GenConfig {
    pub ll1_optimization: bool,
    pub match_memo: bool,
    /// When true, scaffold a CLI: Cargo.toml + src/main.rs. When false,
    /// the caller owns Cargo.toml and no CLI binary is emitted.
    pub cli: bool,
    /// When true, emit a wasm bundle: a standalone lib crate plus a
    /// `wasm-bindgen` wrapper crate under `wasm/` and a `manifest.json`. A
    /// wasm bundle has no CLI, so `wasm` and `cli` are mutually exclusive.
    pub wasm: bool,
    /// When true, the generated parser runs in the unsafe mode; see
    /// [`iguana_runtime::parser::Parser::UNSAFE`].
    pub unsafe_mode: bool,
}

impl Default for GenConfig {
    fn default() -> Self {
        Self {
            ll1_optimization: true,
            match_memo: true,
            cli: true,
            wasm: false,
            unsafe_mode: false,
        }
    }
}

pub struct GenerateResult {
    pub total_duration_ms: u64,
}

mod cargo_toml_gen;
pub use cargo_toml_gen::git_runtime_dependency;
mod gen_config_file;
pub use gen_config_file::GenConfigFile;
mod grammar_data_gen;
pub(crate) mod grammar_utils;
mod id;
mod lib_gen;
mod main_gen;
mod manifest_gen;
mod parse_tree_gen;
mod parser_gen;
mod scanner_gen;
mod terminal_sets;
mod types_gen;
mod wasm_gen;

mod post_process;
pub use post_process::post_process;
pub(crate) mod utils;

const GENERATED_HEADER_RUST: &str = "// @generated by iguana. Do not edit manually.\n";

/// Generate parser source files into `<output_dir>/src/`.
///
/// Writes lib.rs, parser.rs, scanner.rs, parse_tree.rs, types.rs, and
/// grammar_data.rs. Does not touch Cargo.toml or main.rs; those belong to
/// `generate_scaffold`.
pub fn generate_sources(
    grammar: &Grammar,
    output_dir: &Path,
    config: GenConfig,
) -> io::Result<GenerateResult> {
    let start = Instant::now();
    let mut nonterminal_ids = NonterminalIds::new(grammar.nonterminals().cloned());
    let mut terminal_ids = TerminalIds::default();
    for terminal in grammar.terminals() {
        terminal_ids.insert(terminal.clone());
    }
    let mut binding_ids = BindingIds::default();
    for nt in grammar.nonterminals() {
        for param in &nt.parameters {
            binding_ids.insert(param.name.clone());
        }
        for alternative in grammar.alternatives(nt) {
            for symbol in &alternative.symbols {
                collect_binding_names(symbol, &mut binding_ids);
            }
        }
    }
    let mut slot_ids = SlotIds::new(grammar);
    // `nonterminal_ids.nonterminals()` returns non-parameterized nonterminals
    // first (sorted at construction in `NonterminalIds::new`). Iterating in
    // that order means all slots of non-parameterized nonterminals get lower
    // ids than slots of parameterized ones. The intermediate-node index uses
    // this partition to dispatch between a `Span`-keyed array
    // (non-parameterized) and a `(Span, Option<EnvId>)`-keyed array
    // (parameterized).
    let sorted_nonterminals: Vec<_> = nonterminal_ids.nonterminals().cloned().collect();
    for nonterminal in &sorted_nonterminals {
        let alternatives = grammar.alternatives(nonterminal);
        for (index, alternative) in alternatives.iter().enumerate() {
            for pos in 0..alternative.symbols.len() {
                let slot = Slot::new(nonterminal, alternative, pos);
                slot_ids.insert(slot);
            }
            let last_symbol_index = alternative.symbols.len();
            let end_slot = Slot::new(nonterminal, alternative, last_symbol_index);
            let end_slot_id = slot_ids.insert(end_slot);
            let nonterminal_id = nonterminal_ids.get_id(nonterminal);
            let end_slot = EndSlot {
                index,
                slot_id: end_slot_id,
            };
            nonterminal_ids.add_end_slot(nonterminal_id, end_slot);
        }
    }

    let ff = FirstFollowSets::new(grammar);
    // Checked before the first write, so a rejected grammar leaves no
    // half-written sources behind.
    check_layout_aware_follow(grammar, &ff, config)?;

    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    let src_dir = output_dir.join("src");
    if !src_dir.exists() {
        fs::create_dir(&src_dir)?;
    }

    let lib_path = src_dir.join("lib.rs");
    let parser_path = src_dir.join("parser.rs");
    let scanner_path = src_dir.join("scanner.rs");
    let parse_tree_path = src_dir.join("parse_tree.rs");
    let types_path = src_dir.join("types.rs");
    let grammar_data_path = src_dir.join("grammar_data.rs");

    write_rust_file(
        post_process(&lib_gen::generate(grammar, config).to_string()),
        &lib_path,
    )?;

    let terminal_sets = terminal_sets(grammar, &ff);
    let match_any_sets = SetIds::match_any(&terminal_sets, &terminal_ids);
    let longest_match_sets = SetIds::longest_match(&terminal_sets, &terminal_ids);

    let mut parser_gen = ParserGen::new(
        grammar,
        &nonterminal_ids,
        &terminal_ids,
        &slot_ids,
        &binding_ids,
        config,
    );
    let parser_code = parser_gen.generate();
    write_rust_file(post_process(&parser_code.to_string()), &parser_path)?;

    write_rust_file(
        post_process(
            &scanner_gen::generate(grammar, &terminal_ids, &match_any_sets, &config).to_string(),
        ),
        &scanner_path,
    )?;

    let parse_tree_gen =
        ParseTreeGen::new(grammar, &nonterminal_ids, &terminal_ids, &slot_ids, config);
    write_rust_file(
        post_process(&parse_tree_gen.generate().to_string()),
        &parse_tree_path,
    )?;

    write_rust_file(
        post_process(&types_gen::generate().to_string()),
        &types_path,
    )?;

    write_rust_file(
        post_process(
            &grammar_data_gen::generate(
                grammar,
                &nonterminal_ids,
                &terminal_ids,
                &slot_ids,
                &terminal_sets,
                &match_any_sets,
                &longest_match_sets,
            )
            .to_string(),
        ),
        &grammar_data_path,
    )?;

    Ok(GenerateResult {
        total_duration_ms: start.elapsed().as_millis() as u64,
    })
}

/// Scaffold Cargo.toml and, for a CLI parser, src/main.rs into `output_dir`.
///
/// The Cargo.toml shape follows `config`: a wasm lib crate, a standalone CLI
/// parser crate, or a minimal workspace-member lib. `src/main.rs` is written
/// only for the CLI shape (`config.cli` and not `config.wasm`); a wasm bundle
/// and a workspace-member lib have no binary.
///
/// `src/main.rs` is generated output and is rewritten on every run, like the
/// lib sources. Cargo.toml is configuration the user owns (dependencies,
/// license, versions), so an existing one is preserved; `force` overwrites it
/// (useful when the Cargo.toml template has changed and you want the new
/// shape). The generator does not create or modify license or notice files;
/// those belong to the generated project.
pub fn generate_scaffold(
    grammar: &Grammar,
    output_dir: &Path,
    config: GenConfig,
    runtime_path: Option<&Path>,
    bin_name: Option<&str>,
    force: bool,
) -> io::Result<()> {
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    let src_dir = output_dir.join("src");
    if !src_dir.exists() {
        fs::create_dir(&src_dir)?;
    }

    let cargo_toml = output_dir.join("Cargo.toml");
    if force || !cargo_toml.exists() {
        write_plain_file(
            cargo_toml_gen::generate(grammar, config, runtime_path, bin_name),
            &cargo_toml,
        )?;
    }

    if config.cli && !config.wasm {
        let main_code = main_gen::generate(grammar);
        write_rust_file(
            post_process(&main_code.to_string()),
            &src_dir.join("main.rs"),
        )?;
    }

    Ok(())
}

/// Write the wasm wrapper crate under `output_dir/wasm/` and the bundle's
/// `manifest.json`. The parser lib sources and the root crate's Cargo.toml come
/// from `generate_sources` and `generate_scaffold`.
///
/// The wrapper `lib.rs` and `manifest.json` are derived from the grammar and
/// always overwritten. The wrapper `Cargo.toml` is scaffolding, so it is
/// written only when absent (or when `force` is set), preserving a hand-edited
/// dependency such as a local path to the runtime.
pub fn generate_wasm(
    grammar: &Grammar,
    output_dir: &Path,
    runtime_path: Option<&Path>,
    force: bool,
) -> io::Result<()> {
    let wasm_dir = output_dir.join("wasm");
    let wasm_src = wasm_dir.join("src");
    if !wasm_src.exists() {
        fs::create_dir_all(&wasm_src)?;
    }

    write_rust_file(
        post_process(&wasm_gen::generate(grammar).to_string()),
        &wasm_src.join("lib.rs"),
    )?;

    let wasm_cargo = wasm_dir.join("Cargo.toml");
    if force || !wasm_cargo.exists() {
        write_plain_file(
            cargo_toml_gen::generate_wasm_wrapper(grammar, runtime_path),
            &wasm_cargo,
        )?;
    }

    write_plain_file(
        manifest_gen::generate(grammar),
        &output_dir.join("manifest.json"),
    )?;

    Ok(())
}

fn write_rust_file(content: impl AsRef<str>, path: &Path) -> io::Result<()> {
    let mut file = fs::File::create(path)?;
    file.write_all(GENERATED_HEADER_RUST.as_bytes())?;
    file.write_all(b"\n")?;
    file.write_all(content.as_ref().as_bytes())?;
    file.write_all(b"\n")?;
    Ok(())
}

fn write_plain_file(content: impl AsRef<str>, path: &Path) -> io::Result<()> {
    let mut file = fs::File::create(path)?;
    file.write_all(content.as_ref().as_bytes())?;
    file.write_all(b"\n")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::iggy::parse_grammar;
    use std::{
        env, process,
        time::{SystemTime, UNIX_EPOCH},
    };

    #[test]
    fn force_preserves_project_license_and_notice_files() {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock should be after the Unix epoch")
            .as_nanos();
        let dir = env::temp_dir().join(format!("iguana-project-license-{}-{nonce}", process::id()));
        fs::create_dir(&dir).expect("temporary directory should be created");
        let project_license = dir.join("LICENSE-MIT");
        let project_notice = dir.join("NOTICE");

        fs::write(&project_license, "Copyright Acme Corp")
            .expect("project license should be written");
        fs::write(&project_notice, "Acme Parser").expect("project notice should be written");

        let grammar: Grammar = parse_grammar("grammar G\n\nS = \"x\"\n")
            .expect("grammar should parse")
            .try_into()
            .expect("grammar should build");
        generate_scaffold(&grammar, &dir, GenConfig::default(), None, None, true)
            .expect("forced scaffolding should succeed");

        assert_eq!(
            fs::read_to_string(&project_license).expect("project license should be readable"),
            "Copyright Acme Corp"
        );
        assert_eq!(
            fs::read_to_string(&project_notice).expect("project notice should be readable"),
            "Acme Parser"
        );
        fs::remove_dir_all(dir).expect("temporary directory should be removed");
    }

    fn grammar_with_layout(layout_body: &str) -> Grammar {
        let source = format!(
            r#"grammar G

S = Id !>>> Semi

@Regex
Id = [a-z]+

@Regex
Semi = ";"

@Layout
Layout = {layout_body}

@Regex
WS = [\ ]+
"#
        );
        parse_grammar(&source)
            .expect("the grammar should be valid")
            .try_into()
            .expect("the grammar should build")
    }

    #[test]
    fn rejects_layout_aware_follow_with_a_non_ll1_layout() {
        let grammar = grammar_with_layout("WS | WS WS");
        let ff = FirstFollowSets::new(&grammar);
        let error = check_layout_aware_follow(&grammar, &ff, GenConfig::default())
            .expect_err("the layout is not LL(1)");

        assert_eq!(
            error.to_string(),
            "`!>>>` requires layout `Layout` to be a lexical rule or an LL(1) syntax rule"
        );
    }

    #[test]
    fn rejects_layout_aware_follow_when_ll1_generation_is_disabled() {
        let grammar = grammar_with_layout("WS*");
        let ff = FirstFollowSets::new(&grammar);
        let config = GenConfig {
            ll1_optimization: false,
            ..GenConfig::default()
        };
        let error = check_layout_aware_follow(&grammar, &ff, config)
            .expect_err("LL(1) generation is disabled");

        assert_eq!(
            error.to_string(),
            "`!>>>` requires the `ll1` option when layout `Layout` is an LL(1) syntax rule"
        );
    }
}
