
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getParserName(directory: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_parser_name", { directory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async buildParser(directory: string) : Promise<void> {
    await TAURI_INVOKE("build_parser", { directory });
},
async generateParser(directory: string) : Promise<void> {
    await TAURI_INVOKE("generate_parser", { directory });
},
async parse(directory: string, input: string, startNonterminal: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse", { directory, input, startNonterminal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSppf() : Promise<Result<SPPF, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sppf") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGss() : Promise<Result<GSS, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gss") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNonterminals(directory: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_nonterminals", { directory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadDebugTrace(directory: string, input: string, startNonterminal: string) : Promise<Result<DebugInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_debug_trace", { directory, input, startNonterminal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async debugStepForward() : Promise<Result<DebugInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_step_forward") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async debugStepTo(target: number) : Promise<Result<DebugInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_step_to", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDebugInfo() : Promise<Result<DebugInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_debug_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStackTrace() : Promise<Result<StackFrame[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stack_trace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Debug info returned to the frontend.
 */
export type DebugInfo = { current_step: number; total_steps: number }
export type GSS = { nodes: GSSDotNode[]; edges: GSSDotEdge[] }
export type GSSDotEdge = { src: GssNodeId; dest: GssNodeId; label: string }
export type GSSDotNode = { id: GssNodeId; label: string }
/**
 * A unique identifier for a GSS node.
 * 
 * This is a type-safe wrapper around an index into the parser's GSS node list.
 * Uses `u32` since GSS nodes are of the form (nonterminal_id, input_index), which
 * is bounded by the input length (u32).
 */
export type GssNodeId = number
export type NodeKind = "Nonterminal" | "Intermediate" | "Terminal" | "Packed"
export type SPPF = { nodes: SPPFDotNode[]; edges: SPPFDotEdge[] }
export type SPPFDotEdge = { src: SPPFNodeId; dest: SPPFNodeId }
export type SPPFDotNode = { id: SPPFNodeId; kind: NodeKind; label: string }
/**
 * A unique identifier for an SPPF node.
 * 
 * This is a type-safe wrapper around an index into the parser's SPPF nodes list.
 * Uses `u32` since real-world grammars rarely exceed 2^32 - 1 nodes.
 */
export type SPPFNodeId = number
/**
 * A stack frame in the GLL call stack.
 */
export type StackFrame = { slot_name: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
