// @generated by iguana. Do not edit manually.

use iguana_runtime::{
    grammar::{Grammar, Nonterminal, Slot, Terminal},
    ids::{NonterminalId, TerminalId},
    scanner::TerminalSet,
};
pub const E: NonterminalId = NonterminalId(0);
pub const EXPR: NonterminalId = NonterminalId(1);
pub const START_E: NonterminalId = NonterminalId(2);
pub const START_EXPR: NonterminalId = NonterminalId(3);
pub struct Ll1PrefixAmbiguityGrammar;
impl Grammar for Ll1PrefixAmbiguityGrammar {
    const NAME: &'static str = "Ll1PrefixAmbiguity";
    const NONTERMINALS: &'static [Nonterminal] = &[
        Nonterminal {
            name: "E",
            display_name: "E",
        },
        Nonterminal {
            name: "Expr",
            display_name: "Expr",
        },
        Nonterminal {
            name: "StartE",
            display_name: "E",
        },
        Nonterminal {
            name: "StartExpr",
            display_name: "Expr",
        },
    ];
    const DISPLAY_ORDER: &'static [&'static str] = &["E", "Expr"];
    const TERMINALS: &'static [Terminal] = &[
        Terminal { name: "Int" },
        Terminal { name: "Float" },
        Terminal { name: "Id" },
        Terminal { name: "\".\"" },
        Terminal { name: "Epsilon" },
        Terminal { name: "EOF" },
    ];
    const SLOTS: &'static [Slot] = &[
        Slot {
            display_name: "E : . Expr",
        },
        Slot {
            display_name: "E : Expr.",
        },
        Slot {
            display_name: "Expr : . Int \".\" Id",
        },
        Slot {
            display_name: "Expr : Int . \".\" Id",
        },
        Slot {
            display_name: "Expr : Int \".\" . Id",
        },
        Slot {
            display_name: "Expr : Int \".\" Id.",
        },
        Slot {
            display_name: "Expr : . Float",
        },
        Slot {
            display_name: "Expr : Float.",
        },
        Slot {
            display_name: "E : . start:E",
        },
        Slot {
            display_name: "E : start:E.",
        },
        Slot {
            display_name: "Expr : . start:Expr",
        },
        Slot {
            display_name: "Expr : start:Expr.",
        },
    ];
    const LAYOUT_NAME: Option<&'static str> = None;
    const LAYOUT_TERMINALS: &'static [TerminalId] = &[];
    // A failed terminal match refers to a static terminal set like every other failure, so the
    // error reporting path needs to reach a terminal set from a terminal id. This slice, indexed
    // by terminal id, serves only that.
    const SINGLE_TERMINAL_SETS: &'static [TerminalSet] = &[
        TerminalSet {
            id: 5,
            terminals: &[TerminalId(0)],
        },
        TerminalSet {
            id: 6,
            terminals: &[TerminalId(1)],
        },
        TerminalSet {
            id: 7,
            terminals: &[TerminalId(2)],
        },
        TerminalSet {
            id: 8,
            terminals: &[TerminalId(3)],
        },
        TerminalSet {
            id: 9,
            terminals: &[TerminalId(4)],
        },
        TerminalSet {
            id: 10,
            terminals: &[TerminalId(5)],
        },
    ];
    fn nonterminal_id(name: &str) -> Option<NonterminalId> {
        match name {
            "E" => Some(E),
            "Expr" => Some(EXPR),
            "StartE" => Some(START_E),
            "StartExpr" => Some(START_EXPR),
            _ => None,
        }
    }
}
// E { EOF }
pub static FOLLOW_SET_E: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(5)],
};
// E : . Expr { Int, Float }
pub static FIRST_SET_E_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(0), TerminalId(1)],
};
// Expr { EOF }
pub static FOLLOW_SET_EXPR: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(5)],
};
// Expr : . Int "." Id { Int }
pub static FIRST_SET_EXPR_ALT0: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[TerminalId(0)],
};
// Expr : . Float { Float }
pub static FIRST_SET_EXPR_ALT1: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(1)],
};
// StartE { EOF }
pub static FOLLOW_SET_START_E: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(5)],
};
// StartE : . start:E { Int, Float }
pub static FIRST_SET_START_E_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(0), TerminalId(1)],
};
// StartExpr { EOF }
pub static FOLLOW_SET_START_EXPR: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(5)],
};
// StartExpr : . start:Expr { Int, Float }
pub static FIRST_SET_START_EXPR_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(0), TerminalId(1)],
};
// E { Int, Float }
pub static FIRST_SET_E: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(0), TerminalId(1)],
};
// Expr { Int, Float }
pub static FIRST_SET_EXPR: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(0), TerminalId(1)],
};
// StartE { Int, Float }
pub static FIRST_SET_START_E: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(0), TerminalId(1)],
};
// StartExpr { Int, Float }
pub static FIRST_SET_START_EXPR: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(0), TerminalId(1)],
};
