// @generated by iguana. Do not edit manually.
use iguana_runtime::ids::{NonterminalId, TerminalId};
use crate::types::{EbnfKind, Nonterminal, Slot, Terminal};
use phf::phf_map;
pub const NONTERMINALS: [Nonterminal; 3] = [
    Nonterminal {
        name: "S",
        display: "S",
        kind: None,
    },
    Nonterminal {
        name: "Id",
        display: "Id",
        kind: None,
    },
    Nonterminal {
        name: "Id_Plus_0",
        display: "Char+",
        kind: Some(EbnfKind::Plus),
    },
];
pub static NONTERMINAL_IDS: phf::Map<&'static str, NonterminalId> = phf_map! {
    "S" => NonterminalId(0), "Id" => NonterminalId(1), "Id_Plus_0" => NonterminalId(2)
};
pub const TERMINALS: [Terminal; 4] = [
    Terminal { name: "Char" },
    Terminal { name: "WS" },
    Terminal { name: "Epsilon" },
    Terminal { name: "EOF" },
];
pub const SLOTS: [Slot; 9] = [
    Slot { display_name: "S : . Id" },
    Slot { display_name: "S : Id." },
    Slot {
        display_name: "Id : . Char+",
    },
    Slot {
        display_name: "Id : Char+.",
    },
    Slot {
        display_name: "Char+ : . Char+ Char",
    },
    Slot {
        display_name: "Char+ : Char+ . Char",
    },
    Slot {
        display_name: "Char+ : Char+ Char.",
    },
    Slot {
        display_name: "Char+ : . Char",
    },
    Slot {
        display_name: "Char+ : Char.",
    },
];
//S { EOF }
pub static FOLLOW_SET_S: &[TerminalId] = &[TerminalId(3)];
//S { Char }
pub static FIRST_SET_S: &[TerminalId] = &[TerminalId(0)];
//S : . Id { Char }
pub static PREDICTION_SET_S_ALT0: &[TerminalId] = &[TerminalId(0)];
//Id { EOF }
pub static FOLLOW_SET_ID: &[TerminalId] = &[TerminalId(3)];
//Id { Char }
pub static FIRST_SET_ID: &[TerminalId] = &[TerminalId(0)];
//Id : . Id_Plus_0 { Char }
pub static PREDICTION_SET_ID_ALT0: &[TerminalId] = &[TerminalId(0)];
//Id_Plus_0 { Char, EOF }
pub static FOLLOW_SET_ID_PLUS_0: &[TerminalId] = &[TerminalId(0), TerminalId(3)];
//Id_Plus_0 { Char }
pub static FIRST_SET_ID_PLUS_0: &[TerminalId] = &[TerminalId(0)];
//Id_Plus_0 : . Id_Plus_0 Char { Char }
pub static PREDICTION_SET_ID_PLUS_0_ALT0: &[TerminalId] = &[TerminalId(0)];
//Id_Plus_0 : . Char { Char }
pub static PREDICTION_SET_ID_PLUS_0_ALT1: &[TerminalId] = &[TerminalId(0)];

