// @generated by iguana. Do not edit manually.
use iguana_runtime::ids::TerminalId;
//E { "+", "*", EOF }
pub static FOLLOW_SET_E: &[TerminalId] = &[TerminalId(1), TerminalId(0), TerminalId(4)];
//E { "a" }
pub static FIRST_SET_E: &[TerminalId] = &[TerminalId(2)];
//E : . E "*" E { "a" }
pub static PREDICTION_SET_E_ALT0: &[TerminalId] = &[TerminalId(2)];
//E : . E "+" E { "a" }
pub static PREDICTION_SET_E_ALT1: &[TerminalId] = &[TerminalId(2)];
//E : . "a" { "a" }
pub static PREDICTION_SET_E_ALT2: &[TerminalId] = &[TerminalId(2)];

