// @generated by iguana. Do not edit manually.

use except_longest_match::ExceptLongestMatchParser;
use iguana_runtime::cli;
use std::process::ExitCode;
fn main() -> ExitCode {
    cli::main::<ExceptLongestMatchParser>()
}
