// @generated by iguana. Do not edit manually.

use iguana_runtime::{
    grammar::{Grammar, Nonterminal, Slot, Terminal},
    ids::{NonterminalId, TerminalId},
    scanner::TerminalSet,
};
pub const S: NonterminalId = NonterminalId(0);
pub const STATEMENT: NonterminalId = NonterminalId(1);
pub const LAYOUT: NonterminalId = NonterminalId(2);
pub const PLUS_0: NonterminalId = NonterminalId(3);
pub const ALT_0: NonterminalId = NonterminalId(4);
pub const PLUS_1: NonterminalId = NonterminalId(5);
pub const OPT_0: NonterminalId = NonterminalId(6);
pub const STAR_0: NonterminalId = NonterminalId(7);
pub const START_S: NonterminalId = NonterminalId(8);
pub const START_STATEMENT: NonterminalId = NonterminalId(9);
pub struct DanglingElseUnsafeGrammar;
impl Grammar for DanglingElseUnsafeGrammar {
    const NAME: &'static str = "DanglingElseUnsafe";
    const NONTERMINALS: &'static [Nonterminal] = &[
        Nonterminal {
            name: "S",
            display_name: "S",
        },
        Nonterminal {
            name: "Statement",
            display_name: "Statement",
        },
        Nonterminal {
            name: "Layout",
            display_name: "Layout",
        },
        Nonterminal {
            name: "Plus_0",
            display_name: "Statement+",
        },
        Nonterminal {
            name: "Alt_0",
            display_name: "(WhiteSpace | Comment)",
        },
        Nonterminal {
            name: "Plus_1",
            display_name: "(WhiteSpace | Comment)+",
        },
        Nonterminal {
            name: "Opt_0",
            display_name: "(WhiteSpace | Comment)+?",
        },
        Nonterminal {
            name: "Star_0",
            display_name: "(WhiteSpace | Comment)*",
        },
        Nonterminal {
            name: "StartS",
            display_name: "S",
        },
        Nonterminal {
            name: "StartStatement",
            display_name: "Statement",
        },
    ];
    const DISPLAY_ORDER: &'static [&'static str] = &["S", "Statement"];
    const TERMINALS: &'static [Terminal] = &[
        Terminal { name: "Cond" },
        Terminal { name: "Id" },
        Terminal { name: "Else" },
        Terminal { name: "Letter" },
        Terminal { name: "WhiteSpace" },
        Terminal { name: "Comment" },
        Terminal { name: "\"if\"" },
        Terminal { name: "\"(\"" },
        Terminal { name: "\")\"" },
        Terminal { name: "\";\"" },
        Terminal { name: "Epsilon" },
        Terminal { name: "EOF" },
    ];
    const SLOTS: &'static [Slot] = &[
        Slot {
            display_name: "S : . Statement+",
        },
        Slot {
            display_name: "S : Statement+.",
        },
        Slot {
            display_name: "Statement : . \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" . Layout \"(\" Layout Cond Layout \")\" Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout . \"(\" Layout Cond Layout \")\" Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" . Layout Cond Layout \")\" Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout . Cond Layout \")\" Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond . Layout \")\" Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout . \")\" Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" . Layout Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout . Statement !>>> Else",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement !>>> Else.",
        },
        Slot {
            display_name: "Statement : . \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" . Layout \"(\" Layout Cond Layout \")\" Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout . \"(\" Layout Cond Layout \")\" Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" . Layout Cond Layout \")\" Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout . Cond Layout \")\" Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond . Layout \")\" Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout . \")\" Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" . Layout Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout . Statement Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement . Layout Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement Layout . Else Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement Layout Else . Layout Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement Layout Else Layout . Statement",
        },
        Slot {
            display_name: "Statement : \"if\" Layout \"(\" Layout Cond Layout \")\" Layout Statement Layout Else Layout Statement.",
        },
        Slot {
            display_name: "Statement : . Id Layout \";\"",
        },
        Slot {
            display_name: "Statement : Id . Layout \";\"",
        },
        Slot {
            display_name: "Statement : Id Layout . \";\"",
        },
        Slot {
            display_name: "Statement : Id Layout \";\".",
        },
        Slot {
            display_name: "Layout : . (WhiteSpace | Comment)*",
        },
        Slot {
            display_name: "Layout : (WhiteSpace | Comment)*.",
        },
        Slot {
            display_name: "Statement+ : . Statement+ Layout Statement",
        },
        Slot {
            display_name: "Statement+ : Statement+ . Layout Statement",
        },
        Slot {
            display_name: "Statement+ : Statement+ Layout . Statement",
        },
        Slot {
            display_name: "Statement+ : Statement+ Layout Statement.",
        },
        Slot {
            display_name: "Statement+ : . Statement",
        },
        Slot {
            display_name: "Statement+ : Statement.",
        },
        Slot {
            display_name: "(WhiteSpace | Comment) : . WhiteSpace",
        },
        Slot {
            display_name: "(WhiteSpace | Comment) : WhiteSpace.",
        },
        Slot {
            display_name: "(WhiteSpace | Comment) : . Comment",
        },
        Slot {
            display_name: "(WhiteSpace | Comment) : Comment.",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+ : . (WhiteSpace | Comment)+ (WhiteSpace | Comment)",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+ : (WhiteSpace | Comment)+ . (WhiteSpace | Comment)",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+ : (WhiteSpace | Comment)+ (WhiteSpace | Comment).",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+ : . (WhiteSpace | Comment)",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+ : (WhiteSpace | Comment).",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+? : . (WhiteSpace | Comment)+",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+? : (WhiteSpace | Comment)+.",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)+? : .",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)* : . (WhiteSpace | Comment)+?",
        },
        Slot {
            display_name: "(WhiteSpace | Comment)* : (WhiteSpace | Comment)+?.",
        },
        Slot {
            display_name: "S : . Layout start:S Layout",
        },
        Slot {
            display_name: "S : Layout . start:S Layout",
        },
        Slot {
            display_name: "S : Layout start:S . Layout",
        },
        Slot {
            display_name: "S : Layout start:S Layout.",
        },
        Slot {
            display_name: "Statement : . Layout start:Statement Layout",
        },
        Slot {
            display_name: "Statement : Layout . start:Statement Layout",
        },
        Slot {
            display_name: "Statement : Layout start:Statement . Layout",
        },
        Slot {
            display_name: "Statement : Layout start:Statement Layout.",
        },
    ];
    const LAYOUT_NAME: Option<&'static str> = Some("Layout");
    const LAYOUT_TERMINALS: &'static [TerminalId] = &[TerminalId(4), TerminalId(5)];
    // A failed terminal match refers to a static terminal set like every other failure, so the
    // error reporting path needs to reach a terminal set from a terminal id. This slice, indexed
    // by terminal id, serves only that.
    const SINGLE_TERMINAL_SETS: &'static [TerminalSet] = &[
        TerminalSet {
            id: 19,
            terminals: &[TerminalId(0)],
        },
        TerminalSet {
            id: 20,
            terminals: &[TerminalId(1)],
        },
        TerminalSet {
            id: 21,
            terminals: &[TerminalId(2)],
        },
        TerminalSet {
            id: 22,
            terminals: &[TerminalId(3)],
        },
        TerminalSet {
            id: 23,
            terminals: &[TerminalId(4)],
        },
        TerminalSet {
            id: 24,
            terminals: &[TerminalId(5)],
        },
        TerminalSet {
            id: 25,
            terminals: &[TerminalId(6)],
        },
        TerminalSet {
            id: 26,
            terminals: &[TerminalId(7)],
        },
        TerminalSet {
            id: 27,
            terminals: &[TerminalId(8)],
        },
        TerminalSet {
            id: 28,
            terminals: &[TerminalId(9)],
        },
        TerminalSet {
            id: 29,
            terminals: &[TerminalId(10)],
        },
        TerminalSet {
            id: 30,
            terminals: &[TerminalId(11)],
        },
    ];
    fn nonterminal_id(name: &str) -> Option<NonterminalId> {
        match name {
            "S" => Some(S),
            "Statement" => Some(STATEMENT),
            "Layout" => Some(LAYOUT),
            "Plus_0" => Some(PLUS_0),
            "Alt_0" => Some(ALT_0),
            "Plus_1" => Some(PLUS_1),
            "Opt_0" => Some(OPT_0),
            "Star_0" => Some(STAR_0),
            "StartS" => Some(START_S),
            "StartStatement" => Some(START_STATEMENT),
            _ => None,
        }
    }
}
// S { WhiteSpace, Comment, EOF }
pub static FOLLOW_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(4), TerminalId(5), TerminalId(11)],
};
// S : . Plus_0 { Id, "if" }
pub static FIRST_SET_S_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(1), TerminalId(6)],
};
// Statement { Id, Else, WhiteSpace, Comment, "if", EOF }
pub static FOLLOW_SET_STATEMENT: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[
        TerminalId(1),
        TerminalId(2),
        TerminalId(4),
        TerminalId(5),
        TerminalId(6),
        TerminalId(11),
    ],
};
// Statement : . "if" Layout "(" Layout Cond Layout ")" Layout Statement !>>> Else { "if" }
pub static FIRST_SET_STATEMENT_ALT0: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(6)],
};
// Statement : "if" Layout "(" Layout Cond Layout ")" Layout . Statement !>>> Else !>>> {
// Else }
pub static LAYOUT_AWARE_FOLLOW_RESTRICTION_STATEMENT_ALT0_POS8: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(2)],
};
// Statement : . "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
// Statement { "if" }
pub static FIRST_SET_STATEMENT_ALT1: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(6)],
};
// Statement : . Id Layout ";" { Id }
pub static FIRST_SET_STATEMENT_ALT2: TerminalSet = TerminalSet {
    id: 5,
    terminals: &[TerminalId(1)],
};
// Layout { Cond, Id, Else, "if", "(", ")", ";", EOF }
pub static FOLLOW_SET_LAYOUT: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[
        TerminalId(0),
        TerminalId(1),
        TerminalId(2),
        TerminalId(6),
        TerminalId(7),
        TerminalId(8),
        TerminalId(9),
        TerminalId(11),
    ],
};
// Layout : . Star_0 { WhiteSpace, Comment }
pub static FIRST_SET_LAYOUT_ALT0: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Plus_0 { Id, WhiteSpace, Comment, "if", EOF }
pub static FOLLOW_SET_PLUS_0: TerminalSet = TerminalSet {
    id: 8,
    terminals: &[
        TerminalId(1),
        TerminalId(4),
        TerminalId(5),
        TerminalId(6),
        TerminalId(11),
    ],
};
// Plus_0 : . Plus_0 Layout Statement { Id, "if" }
pub static FIRST_SET_PLUS_0_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(1), TerminalId(6)],
};
// Plus_0 : . Statement { Id, "if" }
pub static FIRST_SET_PLUS_0_ALT1: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(1), TerminalId(6)],
};
// Alt_0 { Cond, Id, Else, WhiteSpace, Comment, "if", "(", ")", ";", EOF }
pub static FOLLOW_SET_ALT_0: TerminalSet = TerminalSet {
    id: 9,
    terminals: &[
        TerminalId(0),
        TerminalId(1),
        TerminalId(2),
        TerminalId(4),
        TerminalId(5),
        TerminalId(6),
        TerminalId(7),
        TerminalId(8),
        TerminalId(9),
        TerminalId(11),
    ],
};
// Alt_0 : . WhiteSpace { WhiteSpace }
pub static FIRST_SET_ALT_0_ALT0: TerminalSet = TerminalSet {
    id: 10,
    terminals: &[TerminalId(4)],
};
// Alt_0 : . Comment { Comment }
pub static FIRST_SET_ALT_0_ALT1: TerminalSet = TerminalSet {
    id: 11,
    terminals: &[TerminalId(5)],
};
// Plus_1 { Cond, Id, Else, WhiteSpace, Comment, "if", "(", ")", ";", EOF }
pub static FOLLOW_SET_PLUS_1: TerminalSet = TerminalSet {
    id: 9,
    terminals: &[
        TerminalId(0),
        TerminalId(1),
        TerminalId(2),
        TerminalId(4),
        TerminalId(5),
        TerminalId(6),
        TerminalId(7),
        TerminalId(8),
        TerminalId(9),
        TerminalId(11),
    ],
};
// Plus_1 : . Plus_1 Alt_0 { WhiteSpace, Comment }
pub static FIRST_SET_PLUS_1_ALT0: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Plus_1 : . Alt_0 { WhiteSpace, Comment }
pub static FIRST_SET_PLUS_1_ALT1: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Opt_0 { Cond, Id, Else, "if", "(", ")", ";", EOF }
pub static FOLLOW_SET_OPT_0: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[
        TerminalId(0),
        TerminalId(1),
        TerminalId(2),
        TerminalId(6),
        TerminalId(7),
        TerminalId(8),
        TerminalId(9),
        TerminalId(11),
    ],
};
// Opt_0 : . Plus_1 { WhiteSpace, Comment }
pub static FIRST_SET_OPT_0_ALT0: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Opt_0 : . { }
pub static FIRST_SET_OPT_0_ALT1: TerminalSet = TerminalSet {
    id: 12,
    terminals: &[],
};
// Star_0 { Cond, Id, Else, "if", "(", ")", ";", EOF }
pub static FOLLOW_SET_STAR_0: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[
        TerminalId(0),
        TerminalId(1),
        TerminalId(2),
        TerminalId(6),
        TerminalId(7),
        TerminalId(8),
        TerminalId(9),
        TerminalId(11),
    ],
};
// Star_0 : . Opt_0 { WhiteSpace, Comment }
pub static FIRST_SET_STAR_0_ALT0: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// StartS { EOF }
pub static FOLLOW_SET_START_S: TerminalSet = TerminalSet {
    id: 13,
    terminals: &[TerminalId(11)],
};
// StartS : . Layout start:S Layout { Id, WhiteSpace, Comment, "if" }
pub static FIRST_SET_START_S_ALT0: TerminalSet = TerminalSet {
    id: 14,
    terminals: &[TerminalId(1), TerminalId(4), TerminalId(5), TerminalId(6)],
};
// StartStatement { EOF }
pub static FOLLOW_SET_START_STATEMENT: TerminalSet = TerminalSet {
    id: 13,
    terminals: &[TerminalId(11)],
};
// StartStatement : . Layout start:Statement Layout { Id, WhiteSpace, Comment, "if" }
pub static FIRST_SET_START_STATEMENT_ALT0: TerminalSet = TerminalSet {
    id: 14,
    terminals: &[TerminalId(1), TerminalId(4), TerminalId(5), TerminalId(6)],
};
// S { Id, "if" }
pub static FIRST_SET_S: TerminalSet = TerminalSet {
    id: 15,
    terminals: &[TerminalId(1), TerminalId(6)],
};
// Statement { Id, "if" }
pub static FIRST_SET_STATEMENT: TerminalSet = TerminalSet {
    id: 15,
    terminals: &[TerminalId(1), TerminalId(6)],
};
// Layout { WhiteSpace, Comment }
pub static FIRST_SET_LAYOUT: TerminalSet = TerminalSet {
    id: 16,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Plus_0 { Id, "if" }
pub static FIRST_SET_PLUS_0: TerminalSet = TerminalSet {
    id: 15,
    terminals: &[TerminalId(1), TerminalId(6)],
};
// Alt_0 { WhiteSpace, Comment }
pub static FIRST_SET_ALT_0: TerminalSet = TerminalSet {
    id: 16,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Plus_1 { WhiteSpace, Comment }
pub static FIRST_SET_PLUS_1: TerminalSet = TerminalSet {
    id: 16,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Opt_0 prediction { WhiteSpace, Comment, Cond, Id, Else, "if", "(", ")", ";", EOF }
pub static PREDICTION_SET_OPT_0: TerminalSet = TerminalSet {
    id: 17,
    terminals: &[
        TerminalId(4),
        TerminalId(5),
        TerminalId(0),
        TerminalId(1),
        TerminalId(2),
        TerminalId(6),
        TerminalId(7),
        TerminalId(8),
        TerminalId(9),
        TerminalId(11),
    ],
};
// Opt_0 { WhiteSpace, Comment }
pub static FIRST_SET_OPT_0: TerminalSet = TerminalSet {
    id: 16,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// Star_0 { WhiteSpace, Comment }
pub static FIRST_SET_STAR_0: TerminalSet = TerminalSet {
    id: 16,
    terminals: &[TerminalId(4), TerminalId(5)],
};
// StartS { Id, WhiteSpace, Comment, "if" }
pub static FIRST_SET_START_S: TerminalSet = TerminalSet {
    id: 18,
    terminals: &[TerminalId(1), TerminalId(4), TerminalId(5), TerminalId(6)],
};
// StartStatement { Id, WhiteSpace, Comment, "if" }
pub static FIRST_SET_START_STATEMENT: TerminalSet = TerminalSet {
    id: 18,
    terminals: &[TerminalId(1), TerminalId(4), TerminalId(5), TerminalId(6)],
};
