// @generated by iguana. Do not edit manually.

use crate::{
    grammar::*,
    parse_tree::{self, DanglingElseUnsafeParseTreeBuilder, ParseTree, create_parse_tree},
    scanner::DanglingElseUnsafeScanner,
};
#[cfg(feature = "instrument")]
use iguana_runtime::grammar::Grammar;
#[allow(unused_imports)]
use iguana_runtime::input::Span;
#[cfg(feature = "debug-trace")]
use iguana_runtime::trace::TraceEvent;
use iguana_runtime::{
    arena::{Arena, ArenaVec},
    descriptor::Descriptor,
    env::{Env, EnvId},
    gss::GSSNode,
    ids::{BindingId, GssNodeId, NonterminalId, SlotId, TerminalId},
    input::Input,
    parser::{
        DESCRIPTORS_CAPACITY_DIVISOR, DESCRIPTORS_CAPACITY_FLOOR, GLLFailure, GLLFailureKind,
        GSS_CAPACITY_MULTIPLIER, Parser, SPPF_CAPACITY_MULTIPLIER, init_logger,
    },
    record,
    result::{ParseError, ParseSuccess},
    scanner::{Scanner, TerminalSet},
    sppf::{IntermediateNode, NonterminalNode, SPPFNode, SPPFNodeId, TerminalNode},
    utils::{inline_map::InlineMap, inline_vec::InlineVec},
};
impl<'i, 'arena> Parser<'i, 'arena> for DanglingElseUnsafeParser<'i, 'arena> {
    type Grammar = DanglingElseUnsafeGrammar;
    type ConcreteParser<'input, 'parser_arena> = DanglingElseUnsafeParser<'input, 'parser_arena>;
    fn new(input: &'i Input, parser_arena: &'arena Arena) -> Self {
        DanglingElseUnsafeParser::new(input, parser_arena)
    }
    type Tree<'a> = ParseTree<'a>;
    fn build_tree<'a>(&self, root: SPPFNodeId, tree_arena: &'a Arena) -> ParseTree<'a> {
        let builder = DanglingElseUnsafeParseTreeBuilder::new(tree_arena);
        create_parse_tree(root, self, &builder)
    }
    const UNSAFE: bool = true;
    // The GLL main loop. Each descriptor starts at its slot. A slot that reaches the next slot
    // of its alternative sets `next`, so a descriptor runs through its alternative as far as it
    // can before the loop takes the next descriptor. The GSS node and the environment are fixed
    // for the whole alternative.
    fn execute(&mut self) {
        while let Some(descriptor) = self.next_descriptor() {
            let mut input_index = descriptor.input_index;
            let mut result = descriptor.sppf_node_id();
            let gss_node_id = descriptor.gss_node_id;
            let env = descriptor.env_id();
            let mut next = Some(descriptor.slot_id);
            while let Some(slot_id) = next {
                next = None;
                record!(
                    self,
                    ProcessingDescriptor,
                    input_index,
                    slot_id,
                    result,
                    gss_node_id
                );
                match slot_id {
                    // S : . Plus_0
                    SlotId(0) => {
                        self.create(NonterminalId(3), result, gss_node_id, SlotId(1), env);
                    }
                    // S : Plus_0.
                    SlotId(1) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(0),
                            SlotId(1),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(1), nonterminal_node_id, None);
                    }
                    // Statement : . "if" Layout "(" Layout Cond Layout ")" Layout Statement !>>> Else
                    SlotId(2) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(6),
                            input_index,
                            SlotId(2),
                            Some(gss_node_id),
                        ) {
                            // Statement : "if" . Layout "(" Layout Cond Layout ")" Layout Statement !>>> Else
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(3));
                        }
                    }
                    // Statement : "if" . Layout "(" Layout Cond Layout ")" Layout Statement !>>> Else
                    SlotId(3) => {
                        if let Some(right_child) =
                            self.parse_layout_ll1(input_index, Some((SlotId(3), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(4), env)
                            {
                                // Statement : "if" Layout . "(" Layout Cond Layout ")" Layout Statement !>>> Else
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(4));
                            }
                        }
                    }
                    // Statement : "if" Layout . "(" Layout Cond Layout ")" Layout Statement !>>> Else
                    SlotId(4) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(7),
                            input_index,
                            SlotId(4),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(5), env)
                            {
                                // Statement : "if" Layout "(" . Layout Cond Layout ")" Layout Statement !>>> Else
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(5));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" . Layout Cond Layout ")" Layout Statement !>>> Else
                    SlotId(5) => {
                        if let Some(right_child) =
                            self.parse_layout_ll1(input_index, Some((SlotId(5), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(6), env)
                            {
                                // Statement : "if" Layout "(" Layout . Cond Layout ")" Layout Statement !>>> Else
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(6));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout . Cond Layout ")" Layout Statement !>>> Else
                    SlotId(6) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(0),
                            input_index,
                            SlotId(6),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(7), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond . Layout ")" Layout Statement !>>> Else
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(7));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond . Layout ")" Layout Statement !>>> Else
                    SlotId(7) => {
                        if let Some(right_child) =
                            self.parse_layout_ll1(input_index, Some((SlotId(7), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(8), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout . ")" Layout Statement !>>> Else
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(8));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout . ")" Layout Statement !>>> Else
                    SlotId(8) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(8),
                            input_index,
                            SlotId(8),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(9), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout ")" . Layout Statement !>>> Else
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(9));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" . Layout Statement !>>> Else
                    SlotId(9) => {
                        if let Some(right_child) =
                            self.parse_layout_ll1(input_index, Some((SlotId(9), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(10), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout ")" Layout . Statement !>>> Else
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(10));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout . Statement !>>> Else
                    SlotId(10) => {
                        self.create(NonterminalId(1), result, gss_node_id, SlotId(11), env);
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement !>>> Else.
                    SlotId(11) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(1),
                            SlotId(11),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(11), nonterminal_node_id, None);
                    }
                    // Statement : . "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
                    // Statement
                    SlotId(12) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(6),
                            input_index,
                            SlotId(12),
                            Some(gss_node_id),
                        ) {
                            // Statement : "if" . Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
                            // Statement
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(13));
                        }
                    }
                    // Statement : "if" . Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
                    // Statement
                    SlotId(13) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(13), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(14), env)
                            {
                                // Statement : "if" Layout . "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(14));
                            }
                        }
                    }
                    // Statement : "if" Layout . "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
                    // Statement
                    SlotId(14) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(7),
                            input_index,
                            SlotId(14),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(15), env)
                            {
                                // Statement : "if" Layout "(" . Layout Cond Layout ")" Layout Statement Layout Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(15));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" . Layout Cond Layout ")" Layout Statement Layout Else Layout
                    // Statement
                    SlotId(15) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(15), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(16), env)
                            {
                                // Statement : "if" Layout "(" Layout . Cond Layout ")" Layout Statement Layout Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(16));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout . Cond Layout ")" Layout Statement Layout Else Layout
                    // Statement
                    SlotId(16) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(0),
                            input_index,
                            SlotId(16),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(17), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond . Layout ")" Layout Statement Layout Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(17));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond . Layout ")" Layout Statement Layout Else Layout
                    // Statement
                    SlotId(17) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(17), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(18), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout . ")" Layout Statement Layout Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(18));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout . ")" Layout Statement Layout Else Layout
                    // Statement
                    SlotId(18) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(8),
                            input_index,
                            SlotId(18),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(19), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout ")" . Layout Statement Layout Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(19));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" . Layout Statement Layout Else Layout
                    // Statement
                    SlotId(19) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(19), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(20), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout ")" Layout . Statement Layout Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(20));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout . Statement Layout Else Layout
                    // Statement
                    SlotId(20) => {
                        self.create(NonterminalId(1), result, gss_node_id, SlotId(21), env);
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement . Layout Else Layout
                    // Statement
                    SlotId(21) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(21), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(22), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout . Else Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(22));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout . Else Layout
                    // Statement
                    SlotId(22) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(2),
                            input_index,
                            SlotId(22),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(23), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else . Layout
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(23));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else . Layout
                    // Statement
                    SlotId(23) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(23), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(24), env)
                            {
                                // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout .
                                // Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(24));
                            }
                        }
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout .
                    // Statement
                    SlotId(24) => {
                        self.create(NonterminalId(1), result, gss_node_id, SlotId(25), env);
                    }
                    // Statement : "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
                    // Statement.
                    SlotId(25) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(1),
                            SlotId(25),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(25), nonterminal_node_id, None);
                    }
                    // Statement : . Id Layout ";"
                    SlotId(26) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(1),
                            input_index,
                            SlotId(26),
                            Some(gss_node_id),
                        ) {
                            // Statement : Id . Layout ";"
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(27));
                        }
                    }
                    // Statement : Id . Layout ";"
                    SlotId(27) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(27), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(28), env)
                            {
                                // Statement : Id Layout . ";"
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(28));
                            }
                        }
                    }
                    // Statement : Id Layout . ";"
                    SlotId(28) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(9),
                            input_index,
                            SlotId(28),
                            Some(gss_node_id),
                        ) {
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(29), env)
                            {
                                // Statement : Id Layout ";".
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(29));
                            }
                        }
                    }
                    // Statement : Id Layout ";".
                    SlotId(29) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(1),
                            SlotId(29),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(29), nonterminal_node_id, None);
                    }
                    // Layout : . Star_0
                    SlotId(30) => {
                        if let Some(right_child) = self
                            .parse_star_0_ll1(input_index, Some((SlotId(30), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            // Layout : Star_0.
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(31));
                        }
                    }
                    // Layout : Star_0.
                    SlotId(31) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(2),
                            SlotId(31),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(31), nonterminal_node_id, None);
                    }
                    // Plus_0 : . Plus_0 Layout Statement
                    SlotId(32) => {
                        self.create(NonterminalId(3), result, gss_node_id, SlotId(33), env);
                    }
                    // Plus_0 : Plus_0 . Layout Statement
                    SlotId(33) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(33), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(34), env)
                            {
                                // Plus_0 : Plus_0 Layout . Statement
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(34));
                            }
                        }
                    }
                    // Plus_0 : Plus_0 Layout . Statement
                    SlotId(34) => {
                        self.create(NonterminalId(1), result, gss_node_id, SlotId(35), env);
                    }
                    // Plus_0 : Plus_0 Layout Statement.
                    SlotId(35) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(3),
                            SlotId(35),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(35), nonterminal_node_id, None);
                    }
                    // Plus_0 : . Statement
                    SlotId(36) => {
                        self.create(NonterminalId(1), result, gss_node_id, SlotId(37), env);
                    }
                    // Plus_0 : Statement.
                    SlotId(37) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(3),
                            SlotId(37),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(37), nonterminal_node_id, None);
                    }
                    // Alt_0 : . WhiteSpace
                    SlotId(38) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(4),
                            input_index,
                            SlotId(38),
                            Some(gss_node_id),
                        ) {
                            // Alt_0 : WhiteSpace.
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(39));
                        }
                    }
                    // Alt_0 : WhiteSpace.
                    SlotId(39) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(4),
                            SlotId(39),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(39), nonterminal_node_id, None);
                    }
                    // Alt_0 : . Comment
                    SlotId(40) => {
                        if let Some((j, right_child)) = self.match_terminal(
                            TerminalId(5),
                            input_index,
                            SlotId(40),
                            Some(gss_node_id),
                        ) {
                            // Alt_0 : Comment.
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(41));
                        }
                    }
                    // Alt_0 : Comment.
                    SlotId(41) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(4),
                            SlotId(41),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(41), nonterminal_node_id, None);
                    }
                    // Plus_1 : . Plus_1 Alt_0
                    SlotId(42) => {
                        if let Some(right_child) = self
                            .parse_plus_1_ll1(input_index, Some((SlotId(42), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            // Plus_1 : Plus_1 . Alt_0
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(43));
                        }
                    }
                    // Plus_1 : Plus_1 . Alt_0
                    SlotId(43) => {
                        if let Some(right_child) =
                            self.parse_alt_0_ll1(input_index, Some((SlotId(43), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(44), env)
                            {
                                // Plus_1 : Plus_1 Alt_0.
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(44));
                            }
                        }
                    }
                    // Plus_1 : Plus_1 Alt_0.
                    SlotId(44) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(5),
                            SlotId(44),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(44), nonterminal_node_id, None);
                    }
                    // Plus_1 : . Alt_0
                    SlotId(45) => {
                        if let Some(right_child) =
                            self.parse_alt_0_ll1(input_index, Some((SlotId(45), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            // Plus_1 : Alt_0.
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(46));
                        }
                    }
                    // Plus_1 : Alt_0.
                    SlotId(46) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(5),
                            SlotId(46),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(46), nonterminal_node_id, None);
                    }
                    // Opt_0 : . Plus_1
                    SlotId(47) => {
                        if let Some(right_child) = self
                            .parse_plus_1_ll1(input_index, Some((SlotId(47), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            // Opt_0 : Plus_1.
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(48));
                        }
                    }
                    // Opt_0 : Plus_1.
                    SlotId(48) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(6),
                            SlotId(48),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(48), nonterminal_node_id, None);
                    }
                    // Opt_0 : .
                    SlotId(49) => {
                        let epsilon_node_id = self.get_or_create_epsilon_node(input_index);
                        let nonterminal_node_id = self.get_or_create_nonterminal_node(
                            NonterminalId(6),
                            SlotId(49),
                            input_index,
                            input_index,
                            epsilon_node_id,
                            gss_node_id,
                            None,
                        );
                        self.pop(gss_node_id, SlotId(49), nonterminal_node_id, None);
                    }
                    // Star_0 : . Opt_0
                    SlotId(50) => {
                        if let Some(right_child) =
                            self.parse_opt_0_ll1(input_index, Some((SlotId(50), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            // Star_0 : Opt_0.
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(51));
                        }
                    }
                    // Star_0 : Opt_0.
                    SlotId(51) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(7),
                            SlotId(51),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(51), nonterminal_node_id, None);
                    }
                    // StartS : . Layout start:S Layout
                    SlotId(52) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(52), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            // StartS : Layout . start:S Layout
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(53));
                        }
                    }
                    // StartS : Layout . start:S Layout
                    SlotId(53) => {
                        self.create(NonterminalId(0), result, gss_node_id, SlotId(54), env);
                    }
                    // StartS : Layout start:S . Layout
                    SlotId(54) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(54), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(55), env)
                            {
                                // StartS : Layout start:S Layout.
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(55));
                            }
                        }
                    }
                    // StartS : Layout start:S Layout.
                    SlotId(55) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(8),
                            SlotId(55),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(55), nonterminal_node_id, None);
                    }
                    // StartStatement : . Layout start:Statement Layout
                    SlotId(56) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(56), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            // StartStatement : Layout . start:Statement Layout
                            input_index = j;
                            result = Some(right_child);
                            next = Some(SlotId(57));
                        }
                    }
                    // StartStatement : Layout . start:Statement Layout
                    SlotId(57) => {
                        self.create(NonterminalId(1), result, gss_node_id, SlotId(58), env);
                    }
                    // StartStatement : Layout start:Statement . Layout
                    SlotId(58) => {
                        if let Some(right_child) = self
                            .parse_layout_ll1(input_index, Some((SlotId(58), Some(gss_node_id))))
                        {
                            let j = self.sppf_node(right_child).right_extent();
                            if let Some(new_node) =
                                self.create_intermediate_node(result, right_child, SlotId(59), env)
                            {
                                // StartStatement : Layout start:Statement Layout.
                                input_index = j;
                                result = Some(new_node);
                                next = Some(SlotId(59));
                            }
                        }
                    }
                    // StartStatement : Layout start:Statement Layout.
                    SlotId(59) => {
                        let nonterminal_node_id = self.create_nonterminal_node(
                            result,
                            NonterminalId(9),
                            SlotId(59),
                            gss_node_id,
                        );
                        self.pop(gss_node_id, SlotId(59), nonterminal_node_id, None);
                    }
                    _ => {
                        panic!("Unknown grammar slot id: {slot_id}");
                    }
                }
            }
        }
    }
    fn add_first_descriptors(
        &mut self,
        nonterminal_id: NonterminalId,
        input_index: u32,
        gss_node_id: GssNodeId,
        env: Option<EnvId>,
    ) {
        match nonterminal_id {
            // S : . Plus_0
            NonterminalId(0) => {
                self.add_first_descriptor(SlotId(0), input_index, gss_node_id, env);
            }
            // Statement
            NonterminalId(1) => {
                let mut matched = false;
                // Statement : . "if" Layout "(" Layout Cond Layout ")" Layout Statement !>>> Else
                if self
                    .scanner
                    .match_any(&FIRST_SET_STATEMENT_ALT0, input_index)
                {
                    matched = true;
                    self.add_first_descriptor(SlotId(2), input_index, gss_node_id, env);
                }
                // Statement : . "if" Layout "(" Layout Cond Layout ")" Layout Statement Layout Else Layout
                // Statement
                if self
                    .scanner
                    .match_any(&FIRST_SET_STATEMENT_ALT1, input_index)
                {
                    matched = true;
                    self.add_first_descriptor(SlotId(12), input_index, gss_node_id, env);
                }
                // Statement : . Id Layout ";"
                if self
                    .scanner
                    .match_any(&FIRST_SET_STATEMENT_ALT2, input_index)
                {
                    matched = true;
                    self.add_first_descriptor(SlotId(26), input_index, gss_node_id, env);
                }
                if !matched {
                    self.add_failure(
                        input_index,
                        SlotId(2),
                        Some(gss_node_id),
                        GLLFailureKind::UnexpectedToken(&FIRST_SET_STATEMENT),
                    );
                }
            }
            // Layout : . Star_0
            NonterminalId(2) => {
                self.add_first_descriptor(SlotId(30), input_index, gss_node_id, env);
            }
            // Plus_0
            NonterminalId(3) => {
                let mut matched = false;
                // Plus_0 : . Plus_0 Layout Statement
                if self.scanner.match_any(&FIRST_SET_PLUS_0_ALT0, input_index) {
                    matched = true;
                    self.add_first_descriptor(SlotId(32), input_index, gss_node_id, env);
                }
                // Plus_0 : . Statement
                if self.scanner.match_any(&FIRST_SET_PLUS_0_ALT1, input_index) {
                    matched = true;
                    self.add_first_descriptor(SlotId(36), input_index, gss_node_id, env);
                }
                if !matched {
                    self.add_failure(
                        input_index,
                        SlotId(32),
                        Some(gss_node_id),
                        GLLFailureKind::UnexpectedToken(&FIRST_SET_PLUS_0),
                    );
                }
            }
            // Alt_0
            NonterminalId(4) => {
                let mut matched = false;
                // Alt_0 : . WhiteSpace
                if self.scanner.match_any(&FIRST_SET_ALT_0_ALT0, input_index) {
                    matched = true;
                    self.add_first_descriptor(SlotId(38), input_index, gss_node_id, env);
                }
                // Alt_0 : . Comment
                if self.scanner.match_any(&FIRST_SET_ALT_0_ALT1, input_index) {
                    matched = true;
                    self.add_first_descriptor(SlotId(40), input_index, gss_node_id, env);
                }
                if !matched {
                    self.add_failure(
                        input_index,
                        SlotId(38),
                        Some(gss_node_id),
                        GLLFailureKind::UnexpectedToken(&FIRST_SET_ALT_0),
                    );
                }
            }
            // Plus_1
            NonterminalId(5) => {
                let mut matched = false;
                // Plus_1 : . Plus_1 Alt_0
                if self.scanner.match_any(&FIRST_SET_PLUS_1_ALT0, input_index) {
                    matched = true;
                    self.add_first_descriptor(SlotId(42), input_index, gss_node_id, env);
                }
                // Plus_1 : . Alt_0
                if self.scanner.match_any(&FIRST_SET_PLUS_1_ALT1, input_index) {
                    matched = true;
                    self.add_first_descriptor(SlotId(45), input_index, gss_node_id, env);
                }
                if !matched {
                    self.add_failure(
                        input_index,
                        SlotId(42),
                        Some(gss_node_id),
                        GLLFailureKind::UnexpectedToken(&FIRST_SET_PLUS_1),
                    );
                }
            }
            // Opt_0
            NonterminalId(6) => {
                let mut matched = false;
                // Opt_0 : . Plus_1
                if self.scanner.match_any(&FIRST_SET_OPT_0_ALT0, input_index) {
                    matched = true;
                    self.add_first_descriptor(SlotId(47), input_index, gss_node_id, env);
                }
                // Opt_0 : .
                if self.scanner.match_any(&FIRST_SET_OPT_0_ALT1, input_index)
                    || self.scanner.match_any(&FOLLOW_SET_OPT_0, input_index)
                {
                    matched = true;
                    self.add_first_descriptor(SlotId(49), input_index, gss_node_id, env);
                }
                if !matched {
                    self.add_failure(
                        input_index,
                        SlotId(47),
                        Some(gss_node_id),
                        GLLFailureKind::UnexpectedToken(&PREDICTION_SET_OPT_0),
                    );
                }
            }
            // Star_0 : . Opt_0
            NonterminalId(7) => {
                self.add_first_descriptor(SlotId(50), input_index, gss_node_id, env);
            }
            // StartS : . Layout start:S Layout
            NonterminalId(8) => {
                self.add_first_descriptor(SlotId(52), input_index, gss_node_id, env);
            }
            // StartStatement : . Layout start:Statement Layout
            NonterminalId(9) => {
                self.add_first_descriptor(SlotId(56), input_index, gss_node_id, env);
            }
            _ => {
                panic!("Unknown nonterminal id: {nonterminal_id}");
            }
        }
    }
    fn get_gss_node(&self, nonterminal_id: NonterminalId, input_index: u32) -> Option<GssNodeId> {
        self.gss_nodes_index[nonterminal_id.index()]
            .get(&input_index)
            .copied()
    }
    fn add_gss_node(
        &mut self,
        nonterminal_id: NonterminalId,
        input_index: u32,
        gss_node_id: GssNodeId,
    ) {
        let arena = self.vec_arena;
        self.gss_nodes_index[nonterminal_id.index()].insert(input_index, gss_node_id, arena);
    }
    fn new_gss_node(&mut self, nonterminal_id: NonterminalId, input_index: u32) -> GssNodeId {
        let gss_node_id = GssNodeId(self.gss_nodes.len() as u32);
        let gss_node = GSSNode::new(gss_node_id, nonterminal_id, input_index);
        record!(self, GSSNodeCreated, nonterminal_id, input_index);
        self.gss_nodes.push(gss_node);
        gss_node_id
    }
    fn gss_node(&self, id: GssNodeId) -> &GSSNode<'arena> {
        &self.gss_nodes[id.index()]
    }
    fn gss_node_mut(&mut self, id: GssNodeId) -> &mut GSSNode<'arena> {
        self.gss_nodes
            .get_mut(id.index())
            .expect("GSS node id should be valid")
    }
    fn sppf_node(&self, id: SPPFNodeId) -> &SPPFNode {
        &self.sppf_nodes[id.index()]
    }
    fn sppf_node_mut(&mut self, id: SPPFNodeId) -> &mut SPPFNode {
        &mut self.sppf_nodes[id.index()]
    }
    fn add_descriptor(&mut self, descriptor: Descriptor) {
        record!(
            self,
            DescriptorAdded,
            descriptor.input_index,
            descriptor.slot_id,
            descriptor.sppf_node_id(),
            descriptor.gss_node_id
        );
        #[cfg(feature = "instrument")]
        self.increment_descriptor_count();
        self.descriptors.push(descriptor);
        #[cfg(feature = "instrument")]
        {
            if self.descriptors.len() > self.descriptors_peak {
                self.descriptors_peak = self.descriptors.len();
            }
        }
    }
    fn next_descriptor(&mut self) -> Option<Descriptor> {
        self.descriptors.pop()
    }
    fn clear_descriptors(&mut self) {
        self.descriptors.clear();
    }
    fn add_terminal_node(&mut self, terminal_node: TerminalNode) -> SPPFNodeId {
        let terminal_node_id = SPPFNodeId(self.sppf_nodes.len() as u32);
        record!(
            self,
            TerminalNodeCreated,
            terminal_node.terminal_id,
            terminal_node.span
        );
        self.sppf_nodes.push(SPPFNode::Terminal(terminal_node));
        terminal_node_id
    }
    fn add_nonterminal_node(&mut self, nonterminal_node: NonterminalNode) -> SPPFNodeId {
        let nonterminal_node_id = SPPFNodeId(self.sppf_nodes.len() as u32);
        record!(
            self,
            NonterminalNodeCreated,
            nonterminal_node.nonterminal_id,
            nonterminal_node.span,
            nonterminal_node.child
        );
        self.sppf_nodes
            .push(SPPFNode::Nonterminal(nonterminal_node));
        nonterminal_node_id
    }
    fn add_intermediate_node(
        &mut self,
        intermediate_node: IntermediateNode,
        _env: Option<EnvId>,
        _add_to_index: bool,
    ) -> SPPFNodeId {
        let intermediate_node_id = SPPFNodeId(self.sppf_nodes.len() as u32);
        record!(
            self,
            IntermediateNodeCreated,
            intermediate_node.slot_id,
            intermediate_node.span,
            intermediate_node.child.0,
            intermediate_node.child.1
        );
        self.sppf_nodes
            .push(SPPFNode::Intermediate(intermediate_node));
        intermediate_node_id
    }
    fn input(&self) -> &'i Input {
        self.scanner.input
    }
    fn sppf_nodes(&self) -> &[SPPFNode] {
        &self.sppf_nodes
    }
    #[cfg(feature = "instrument")]
    fn increment_descriptor_count(&mut self) {
        self.descriptors_count += 1;
    }
    #[cfg(feature = "instrument")]
    fn count_descriptors(&self) -> usize {
        self.descriptors_count
    }
    #[cfg(feature = "instrument")]
    fn count_gss_nodes(&self) -> usize {
        self.gss_nodes.len()
    }
    #[cfg(feature = "instrument")]
    fn count_gss_edges(&self) -> usize {
        self.gss_nodes.iter().map(|n| n.edges().len()).sum()
    }
    #[cfg(feature = "instrument")]
    fn count_nonterminal_nodes(&self) -> usize {
        self.sppf_nodes
            .iter()
            .filter(|n| matches!(n, SPPFNode::Nonterminal(_)))
            .count()
    }
    #[cfg(feature = "instrument")]
    fn count_intermediate_nodes(&self) -> usize {
        self.sppf_nodes
            .iter()
            .filter(|n| matches!(n, SPPFNode::Intermediate(_)))
            .count()
    }
    #[cfg(feature = "instrument")]
    fn count_terminal_nodes(&self) -> usize {
        self.sppf_nodes
            .iter()
            .filter(|n| matches!(n, SPPFNode::Terminal(_)))
            .count()
    }
    #[cfg(feature = "instrument")]
    fn count_ambiguous_nodes(&self) -> usize {
        self.sppf_nodes
            .iter()
            .filter(|n| match n {
                SPPFNode::Nonterminal(nn) => nn.ambiguous,
                SPPFNode::Intermediate(in_) => in_.ambiguous,
                SPPFNode::Terminal(_) => false,
            })
            .count()
    }
    fn gss_nodes<'p>(&'p self) -> impl Iterator<Item = &'p GSSNode<'arena>>
    where
        'arena: 'p,
    {
        self.gss_nodes.iter()
    }
    #[cfg(feature = "debug-trace")]
    fn enable_trace(&mut self) {
        self.trace_events = Some(Vec::new());
    }
    #[cfg(feature = "debug-trace")]
    fn add_trace_event(&mut self, event: TraceEvent) {
        if let Some(trace_events) = &mut self.trace_events {
            trace_events.push(event);
        }
    }
    #[cfg(feature = "debug-trace")]
    fn trace_events(&self) -> &[TraceEvent] {
        self.trace_events.as_deref().unwrap_or(&[])
    }
    fn start_env(&mut self, _start: NonterminalId) -> Option<EnvId> {
        None
    }
    // True if a local ambiguity node was added during parsing. This does not guarantee the
    // ambiguity is reachable from the root, so a tree walk is still needed to confirm it.
    fn ambiguity_node_added(&self) -> bool {
        false
    }
    fn add_start_gss_node(
        &mut self,
        nonterminal_id: NonterminalId,
        input_index: u32,
        gss_node_id: GssNodeId,
    ) {
        self.add_gss_node(nonterminal_id, input_index, gss_node_id);
    }
    fn new_env(&mut self) -> (EnvId, &mut Env<'arena>) {
        let id = EnvId(self.envs.len() as u32);
        self.envs.push(Env::default());
        (id, &mut self.envs[id.index()])
    }
    fn lookup(&self, name: BindingId, env_id: EnvId) -> i32 {
        let env = &self.envs[env_id.index()];
        env.get(name)
    }
    fn clone_env(&mut self, source: EnvId) -> (EnvId, &mut Env<'arena>) {
        let bindings = self.envs[source.0 as usize].bindings.clone();
        let (new_id, new_env) = self.new_env();
        new_env.bindings = bindings;
        (new_id, new_env)
    }
    fn envs(&self) -> &[Env<'arena>] {
        &self.envs
    }
    #[cfg(feature = "instrument")]
    fn record_stats(&self) -> iguana_runtime::instrument::Stats {
        let mut stats = iguana_runtime::instrument::Stats::new();
        stats.descriptors_count = self.count_descriptors();
        stats.descriptors_peak = self.descriptors_peak;
        stats.envs_count = self.envs.len();
        stats.gss_nodes_count = self.count_gss_nodes();
        stats.gss_edges_count = self.count_gss_edges();
        stats.nonterminal_nodes_count = self.count_nonterminal_nodes();
        stats.intermediate_nodes_count = self.count_intermediate_nodes();
        stats.terminal_nodes_count = self.count_terminal_nodes();
        stats.ambiguous_nodes_count = self.count_ambiguous_nodes();
        for node in self.gss_nodes() {
            stats.record("GssNode::edges: InlineVec", node.edges().len());
            stats.record(
                "GssNode::popped_elements: InlineMap",
                node.popped_elements().len(),
            );
        }
        for env in self.envs() {
            stats.record("Env::bindings: Bindings", env.bindings.len());
        }
        for m in self.gss_nodes_index.iter() {
            stats.record("Parser::gss_nodes_index: InlineMap", m.len());
        }
        for (nt_id, pos) in &self.ll1_call_log {
            let name = Self::Grammar::nonterminal_display_name(*nt_id);
            stats.record_ll1_call(name, *pos);
        }
        stats
    }
    fn post_conditions(
        &mut self,
        slot: SlotId,
        _left_extent: u32,
        right_extent: u32,
    ) -> Option<GLLFailureKind> {
        match slot {
            SlotId(11) => {
                if ({
                    self.suppress_failures = true;
                    let node = self.parse_layout_ll1(right_extent, None);
                    self.suppress_failures = false;
                    node.map(|node| self.sppf_node(node).right_extent())
                })
                .is_some_and(|end| {
                    self.scanner
                        .match_any(&LAYOUT_AWARE_FOLLOW_RESTRICTION_STATEMENT_ALT0_POS8, end)
                }) {
                    Some(GLLFailureKind::ForbiddenFollow(
                        &LAYOUT_AWARE_FOLLOW_RESTRICTION_STATEMENT_ALT0_POS8,
                    ))
                } else {
                    None
                }
            }
            _ => None,
        }
    }
    fn follow_set_check(&mut self, nonterminal_id: NonterminalId, input_index: u32) -> bool {
        match nonterminal_id {
            NonterminalId(0) => self.scanner.match_any(&FOLLOW_SET_S, input_index),
            NonterminalId(1) => self.scanner.match_any(&FOLLOW_SET_STATEMENT, input_index),
            NonterminalId(2) => self.scanner.match_any(&FOLLOW_SET_LAYOUT, input_index),
            NonterminalId(3) => self.scanner.match_any(&FOLLOW_SET_PLUS_0, input_index),
            NonterminalId(4) => self.scanner.match_any(&FOLLOW_SET_ALT_0, input_index),
            NonterminalId(5) => self.scanner.match_any(&FOLLOW_SET_PLUS_1, input_index),
            NonterminalId(6) => self.scanner.match_any(&FOLLOW_SET_OPT_0, input_index),
            NonterminalId(7) => self.scanner.match_any(&FOLLOW_SET_STAR_0, input_index),
            NonterminalId(8) => self.scanner.match_any(&FOLLOW_SET_START_S, input_index),
            NonterminalId(9) => self
                .scanner
                .match_any(&FOLLOW_SET_START_STATEMENT, input_index),
            _ => true,
        }
    }
    fn follow_set(&self, nonterminal_id: NonterminalId) -> &'static TerminalSet {
        match nonterminal_id {
            NonterminalId(0) => &FOLLOW_SET_S,
            NonterminalId(1) => &FOLLOW_SET_STATEMENT,
            NonterminalId(2) => &FOLLOW_SET_LAYOUT,
            NonterminalId(3) => &FOLLOW_SET_PLUS_0,
            NonterminalId(4) => &FOLLOW_SET_ALT_0,
            NonterminalId(5) => &FOLLOW_SET_PLUS_1,
            NonterminalId(6) => &FOLLOW_SET_OPT_0,
            NonterminalId(7) => &FOLLOW_SET_STAR_0,
            NonterminalId(8) => &FOLLOW_SET_START_S,
            NonterminalId(9) => &FOLLOW_SET_START_STATEMENT,
            _ => unreachable!("no FOLLOW set for nonterminal {nonterminal_id}"),
        }
    }
    fn failures(&self) -> impl Iterator<Item = &GLLFailure> {
        self.failures.iter()
    }
    #[inline(never)]
    fn add_failure(
        &mut self,
        input_index: u32,
        slot_id: SlotId,
        gss_node_id: Option<GssNodeId>,
        kind: GLLFailureKind,
    ) {
        if self.suppress_failures {
            return;
        }
        let level = self.failures.first().map_or(0, |e| e.input_index);
        record!(self, GLLFailure, input_index, slot_id, gss_node_id, kind);
        if input_index < level {
            return;
        }
        if input_index > level {
            self.failures.clear();
        }
        self.failures.push(
            GLLFailure {
                input_index,
                slot_id,
                gss_node_id,
                kind,
            },
            self.vec_arena,
        );
    }
    fn match_token(&mut self, terminal_id: TerminalId, input_index: u32) -> Option<u32> {
        self.scanner.match_token(terminal_id, input_index)
    }
    fn vec_arena(&self) -> &'arena Arena {
        self.vec_arena
    }
}
pub struct DanglingElseUnsafeParser<'i, 'arena> {
    // Arena backing the parser's internal collections; reset in bulk after the parse.
    vec_arena: &'arena Arena,
    scanner: DanglingElseUnsafeScanner<'i, 'arena>,
    descriptors: ArenaVec<'arena, Descriptor>,
    gss_nodes: ArenaVec<'arena, GSSNode<'arena>>,
    // Per-nonterminal GSS-node index keyed by input position.
    gss_nodes_index: [InlineMap<'arena, u32, GssNodeId>; 10],
    sppf_nodes: ArenaVec<'arena, SPPFNode>,
    #[cfg(feature = "instrument")]
    descriptors_count: usize,
    #[cfg(feature = "instrument")]
    descriptors_peak: usize,
    #[cfg(feature = "instrument")]
    ll1_call_log: Vec<(NonterminalId, u32)>,
    // Epsilon nodes keyed by input position; SPPFNodeId::NONE marks an empty slot.
    epsilon_nodes: ArenaVec<'arena, SPPFNodeId>,
    envs: ArenaVec<'arena, Env<'arena>>,
    failures: InlineVec<'arena, GLLFailure, 8>,
    // When true, `add_failure` is a no-op. The one user is the layout match of a `!>>>`
    // restriction: that parse is speculative, so its failure must not become the reported error.
    suppress_failures: bool,
    layout_memo: ArenaVec<'arena, Option<SPPFNodeId>>,
    #[cfg(feature = "debug-trace")]
    pub trace_events: Option<Vec<TraceEvent>>,
}
impl<'i, 'arena> DanglingElseUnsafeParser<'i, 'arena> {
    /// Creates a new parser.
    /// A reference to `input` is stored in the parser for scanning.
    /// `parser_arena` is where the parser's internal objects (GSS, SPPF nodes,
    /// etc.) are allocated.
    pub fn new(input: &'i Input, parser_arena: &'arena Arena) -> Self {
        init_logger();
        let vec_arena = parser_arena;
        Self {
            vec_arena,
            scanner: DanglingElseUnsafeScanner::new(input, vec_arena),
            gss_nodes_index: [const { InlineMap::Empty }; 10],
            descriptors: vec_arena.vec_with_capacity(
                input.len() as usize / DESCRIPTORS_CAPACITY_DIVISOR + DESCRIPTORS_CAPACITY_FLOOR,
            ),
            gss_nodes: vec_arena.vec_with_capacity(input.len() as usize * GSS_CAPACITY_MULTIPLIER),
            sppf_nodes: vec_arena
                .vec_with_capacity(input.len() as usize * SPPF_CAPACITY_MULTIPLIER),
            epsilon_nodes: {
                let mut v = vec_arena.vec_with_capacity(input.len() as usize + 1);
                v.resize(input.len() as usize + 1, SPPFNodeId::NONE);
                v
            },
            #[cfg(feature = "instrument")]
            descriptors_count: 0,
            #[cfg(feature = "instrument")]
            descriptors_peak: 0,
            #[cfg(feature = "instrument")]
            ll1_call_log: vec![],
            envs: vec_arena.vec(),
            failures: InlineVec::Empty,
            suppress_failures: false,
            layout_memo: {
                let mut v = vec_arena.vec_with_capacity(input.len() as usize + 1);
                v.resize(input.len() as usize + 1, None);
                v
            },
            #[cfg(feature = "debug-trace")]
            trace_events: None,
        }
    }
    /// Parses the input from `start` and builds the parse tree in the given
    /// `tree_arena`. The parser is consumed. The tree lives as long as the
    /// arena lives. `start` is normally the start wrapper of a declared
    /// nonterminal, `grammar::START_<NAME>`, which allows layout around the
    /// input; a bare nonterminal id parses without it.
    pub fn parse<'a>(
        self,
        start: NonterminalId,
        tree_arena: &'a Arena,
    ) -> Result<ParseSuccess<ParseTree<'a>>, ParseError> {
        Parser::parse(self, start, tree_arena)
    }
    pub fn parse_s(
        self,
        tree_arena: &Arena,
    ) -> Result<ParseSuccess<&parse_tree::StartS<'_>>, ParseError> {
        Ok(self
            .parse(START_S, tree_arena)?
            .map(ParseTree::unwrap_start_s))
    }
    pub fn parse_statement(
        self,
        tree_arena: &Arena,
    ) -> Result<ParseSuccess<&parse_tree::StartStatement<'_>>, ParseError> {
        Ok(self
            .parse(START_STATEMENT, tree_arena)?
            .map(ParseTree::unwrap_start_statement))
    }
    pub fn parse_layout(
        self,
        tree_arena: &Arena,
    ) -> Result<ParseSuccess<&parse_tree::Layout<'_>>, ParseError> {
        Ok(self
            .parse(LAYOUT, tree_arena)?
            .map(ParseTree::unwrap_layout))
    }
    fn parse_layout_ll1(
        &mut self,
        i: u32,
        _failure_context: Option<(SlotId, Option<GssNodeId>)>,
    ) -> Option<SPPFNodeId> {
        #[cfg(feature = "instrument")]
        self.ll1_call_log.push((NonterminalId(2), i));
        if let Some(memo) = self.layout_memo[i as usize] {
            return Some(memo);
        }
        let result = (|| -> Option<SPPFNodeId> {
            let mut j = i;
            let right_child = {
                let start = j;
                let node = self.parse_star_0_ll1(start, Some((SlotId(31), None)))?;
                let end = self.sppf_node(node).right_extent();
                j = end;
                node
            };
            let left_extent = self.sppf_node(right_child).left_extent();
            let current = right_child;
            Some(self.add_nonterminal_node(NonterminalNode {
                nonterminal_id: NonterminalId(2),
                return_slot: SlotId(31),
                span: Span {
                    left_extent,
                    right_extent: j,
                },
                child: current,
                ambiguous: false,
            }))
        })();
        if let Some(node) = result {
            self.layout_memo[i as usize] = Some(node);
        }
        result
    }
    fn parse_alt_0_ll1(
        &mut self,
        i: u32,
        failure_context: Option<(SlotId, Option<GssNodeId>)>,
    ) -> Option<SPPFNodeId> {
        #[cfg(feature = "instrument")]
        self.ll1_call_log.push((NonterminalId(4), i));
        let result = (|| -> Option<SPPFNodeId> {
            let matched = self.scanner.longest_match(&FIRST_SET_ALT_0, i)?;
            match matched {
                TerminalId(4) => {
                    let mut j = i;
                    let right_child = {
                        let start = j;
                        let (end, node) =
                            self.match_terminal(TerminalId(4), start, SlotId(39), None)?;
                        j = end;
                        node
                    };
                    let left_extent = self.sppf_node(right_child).left_extent();
                    let current = right_child;
                    Some(self.add_nonterminal_node(NonterminalNode {
                        nonterminal_id: NonterminalId(4),
                        return_slot: SlotId(39),
                        span: Span {
                            left_extent,
                            right_extent: j,
                        },
                        child: current,
                        ambiguous: false,
                    }))
                }
                TerminalId(5) => {
                    let mut j = i;
                    let right_child = {
                        let start = j;
                        let (end, node) =
                            self.match_terminal(TerminalId(5), start, SlotId(41), None)?;
                        j = end;
                        node
                    };
                    let left_extent = self.sppf_node(right_child).left_extent();
                    let current = right_child;
                    Some(self.add_nonterminal_node(NonterminalNode {
                        nonterminal_id: NonterminalId(4),
                        return_slot: SlotId(41),
                        span: Span {
                            left_extent,
                            right_extent: j,
                        },
                        child: current,
                        ambiguous: false,
                    }))
                }
                _ => unreachable!("LL(1) dispatch covers every terminal in FIRST_SET"),
            }
        })();
        if result.is_none() {
            if let Some((slot_id, gss_node_id)) = failure_context {
                self.add_failure(
                    i,
                    slot_id,
                    gss_node_id,
                    GLLFailureKind::UnexpectedToken(&FIRST_SET_ALT_0),
                );
            }
        }
        result
    }
    fn parse_plus_1_ll1(
        &mut self,
        i: u32,
        failure_context: Option<(SlotId, Option<GssNodeId>)>,
    ) -> Option<SPPFNodeId> {
        #[cfg(feature = "instrument")]
        self.ll1_call_log.push((NonterminalId(5), i));
        let result = (|| -> Option<SPPFNodeId> {
            let mut j = i;
            let (body_node, body_end) = (self.parse_alt_0_ll1(j, None).map(|node| {
                let end = self.sppf_node(node).right_extent();
                (node, end)
            }))?;
            j = body_end;
            let left_extent = i;
            let mut current = self.add_nonterminal_node(NonterminalNode {
                nonterminal_id: NonterminalId(5),
                return_slot: SlotId(46),
                span: Span {
                    left_extent,
                    right_extent: j,
                },
                child: body_node,
                ambiguous: false,
            });
            #[allow(clippy::while_let_loop)]
            loop {
                let Some((node_0, pos_0)) = self.parse_alt_0_ll1(j, None).map(|node| {
                    let end = self.sppf_node(node).right_extent();
                    (node, end)
                }) else {
                    break;
                };
                j = pos_0;
                current = self.create_intermediate_node_ll1(
                    SlotId(44),
                    left_extent,
                    pos_0,
                    current,
                    node_0,
                );
                current = self.add_nonterminal_node(NonterminalNode {
                    nonterminal_id: NonterminalId(5),
                    return_slot: SlotId(44),
                    span: Span {
                        left_extent,
                        right_extent: j,
                    },
                    child: current,
                    ambiguous: false,
                });
            }
            Some(current)
        })();
        if result.is_none() {
            if let Some((slot_id, gss_node_id)) = failure_context {
                self.add_failure(
                    i,
                    slot_id,
                    gss_node_id,
                    GLLFailureKind::UnexpectedToken(&FIRST_SET_PLUS_1),
                );
            }
        }
        result
    }
    fn parse_opt_0_ll1(
        &mut self,
        i: u32,
        _failure_context: Option<(SlotId, Option<GssNodeId>)>,
    ) -> Option<SPPFNodeId> {
        #[cfg(feature = "instrument")]
        self.ll1_call_log.push((NonterminalId(6), i));
        let Some(matched) = self.scanner.longest_match(&FIRST_SET_OPT_0, i) else {
            return {
                let epsilon_node_id = self.get_or_create_epsilon_node(i);
                Some(self.add_nonterminal_node(NonterminalNode {
                    nonterminal_id: NonterminalId(6),
                    return_slot: SlotId(49),
                    span: Span {
                        left_extent: i,
                        right_extent: i,
                    },
                    child: epsilon_node_id,
                    ambiguous: false,
                }))
            };
        };
        match matched {
            TerminalId(5) | TerminalId(4) => {
                let mut j = i;
                let right_child = {
                    let start = j;
                    let node = self.parse_plus_1_ll1(start, Some((SlotId(48), None)))?;
                    let end = self.sppf_node(node).right_extent();
                    j = end;
                    node
                };
                let left_extent = self.sppf_node(right_child).left_extent();
                let current = right_child;
                Some(self.add_nonterminal_node(NonterminalNode {
                    nonterminal_id: NonterminalId(6),
                    return_slot: SlotId(48),
                    span: Span {
                        left_extent,
                        right_extent: j,
                    },
                    child: current,
                    ambiguous: false,
                }))
            }
            _ => unreachable!("LL(1) dispatch covers every terminal in FIRST_SET"),
        }
    }
    fn parse_star_0_ll1(
        &mut self,
        i: u32,
        _failure_context: Option<(SlotId, Option<GssNodeId>)>,
    ) -> Option<SPPFNodeId> {
        #[cfg(feature = "instrument")]
        self.ll1_call_log.push((NonterminalId(7), i));
        let mut j = i;
        let right_child = {
            let start = j;
            let node = self.parse_opt_0_ll1(start, Some((SlotId(51), None)))?;
            let end = self.sppf_node(node).right_extent();
            j = end;
            node
        };
        let left_extent = self.sppf_node(right_child).left_extent();
        let current = right_child;
        Some(self.add_nonterminal_node(NonterminalNode {
            nonterminal_id: NonterminalId(7),
            return_slot: SlotId(51),
            span: Span {
                left_extent,
                right_extent: j,
            },
            child: current,
            ambiguous: false,
        }))
    }
    fn get_or_create_epsilon_node(&mut self, i: u32) -> SPPFNodeId {
        let existing = self.epsilon_nodes[i as usize];
        if existing != SPPFNodeId::NONE {
            record!(self, TerminalNodeFound, existing);
            return existing;
        }
        let span = Span::new(i, i);
        let terminal_id = TerminalId(10);
        let node_id = SPPFNodeId(self.sppf_nodes.len() as u32);
        record!(self, TerminalNodeCreated, terminal_id, span);
        self.sppf_nodes
            .push(SPPFNode::Terminal(TerminalNode { terminal_id, span }));
        self.epsilon_nodes[i as usize] = node_id;
        node_id
    }
}
