// @generated by iguana. Do not edit manually.

use crate::types::{Nonterminal, Slot, Terminal};
use iguana_runtime::ids::{NonterminalId, TerminalId};
use iguana_runtime::scanner::TerminalSet;
pub const NONTERMINALS: [Nonterminal; 4] = [
    Nonterminal {
        name: "S",
        display: "S",
        derived: false,
    },
    Nonterminal {
        name: "StartS",
        display: "S",
        derived: true,
    },
    Nonterminal {
        name: "StartE",
        display: "E(0)",
        derived: true,
    },
    Nonterminal {
        name: "E",
        display: "E",
        derived: false,
    },
];
// User-declared nonterminals in `.iggy` source order. Used by `--list-nonterminals`.
pub const NONTERMINAL_DISPLAY_ORDER: [&str; 2] = ["S", "E"];
pub const S: NonterminalId = NonterminalId(0);
pub const START_S: NonterminalId = NonterminalId(1);
pub const START_E: NonterminalId = NonterminalId(2);
pub const E: NonterminalId = NonterminalId(3);
pub fn nonterminal_id(name: &str) -> Option<NonterminalId> {
    match name {
        "S" => Some(S),
        "StartS" => Some(START_S),
        "StartE" => Some(START_E),
        "E" => Some(E),
        _ => None,
    }
}
pub const TERMINALS: [Terminal; 8] = [
    Terminal { name: "WS" },
    Terminal { name: "\"a\"" },
    Terminal { name: "\"+\"" },
    Terminal { name: "\"if\"" },
    Terminal { name: "\"then\"" },
    Terminal { name: "\"else\"" },
    Terminal { name: "Epsilon" },
    Terminal { name: "EOF" },
];
pub const SLOTS: [Slot; 35] = [
    Slot {
        display_name: "S : . E(0)",
    },
    Slot {
        display_name: "S : E(0).",
    },
    Slot {
        display_name: "S : . WS start:S WS",
    },
    Slot {
        display_name: "S : WS . start:S WS",
    },
    Slot {
        display_name: "S : WS start:S . WS",
    },
    Slot {
        display_name: "S : WS start:S WS.",
    },
    Slot {
        display_name: "E(0) : . WS start:E(0) WS",
    },
    Slot {
        display_name: "E(0) : WS . start:E(0) WS",
    },
    Slot {
        display_name: "E(0) : WS start:E(0) . WS",
    },
    Slot {
        display_name: "E(0) : WS start:E(0) WS.",
    },
    Slot {
        display_name: "E : . \"a\" return 0",
    },
    Slot {
        display_name: "E : \"a\" . return 0",
    },
    Slot {
        display_name: "E : \"a\" return 0.",
    },
    Slot {
        display_name: "E : . [2 >= p] l=E(p) [(l == 0) || (l >= 2)] WS \"+\" WS r=E(2) return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] . l=E(p) [(l == 0) || (l >= 2)] WS \"+\" WS r=E(2) return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] l=E(p) . [(l == 0) || (l >= 2)] WS \"+\" WS r=E(2) return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] l=E(p) [(l == 0) || (l >= 2)] . WS \"+\" WS r=E(2) return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] l=E(p) [(l == 0) || (l >= 2)] WS . \"+\" WS r=E(2) return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] l=E(p) [(l == 0) || (l >= 2)] WS \"+\" . WS r=E(2) return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] l=E(p) [(l == 0) || (l >= 2)] WS \"+\" WS . r=E(2) return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] l=E(p) [(l == 0) || (l >= 2)] WS \"+\" WS r=E(2) . return (r == 0) ? 2 : min(r, 2)",
    },
    Slot {
        display_name: "E : [2 >= p] l=E(p) [(l == 0) || (l >= 2)] WS \"+\" WS r=E(2) return (r == 0) ? 2 : min(r, 2).",
    },
    Slot {
        display_name: "E : . \"if\" WS E(0) WS \"then\" WS E(0) WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" . WS E(0) WS \"then\" WS E(0) WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS . E(0) WS \"then\" WS E(0) WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) . WS \"then\" WS E(0) WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS . \"then\" WS E(0) WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" . WS E(0) WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" WS . E(0) WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" WS E(0) . WS \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" WS E(0) WS . \"else\" WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" WS E(0) WS \"else\" . WS E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" WS E(0) WS \"else\" WS . E(1) return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" WS E(0) WS \"else\" WS E(1) . return 1",
    },
    Slot {
        display_name: "E : \"if\" WS E(0) WS \"then\" WS E(0) WS \"else\" WS E(1) return 1.",
    },
];
// S { WS, EOF }
pub static FOLLOW_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(0), TerminalId(7)],
};
// S { "a", "if" }
pub static FIRST_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(1), TerminalId(3)],
};
// S : . E(0) { "a", "if" }
pub static FIRST_SET_S_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(1), TerminalId(3)],
};
// E { "+", EOF, "else", "then", WS }
pub static FOLLOW_SET_E: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[
        TerminalId(2),
        TerminalId(7),
        TerminalId(5),
        TerminalId(4),
        TerminalId(0),
    ],
};
// E { "a", "if" }
pub static FIRST_SET_E: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(1), TerminalId(3)],
};
// E(p: i32) : . "a" return 0 { "a" }
pub static FIRST_SET_E_ALT0: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(1)],
};
// E(p: i32) : . [2 >= p] l=E(p) [(l == 0) || (l >= 2)] WS "+" WS r=E(2) return (r == 0) ? 2
// : min(r, 2) { "a", "if" }
pub static FIRST_SET_E_ALT1: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(1), TerminalId(3)],
};
// E(p: i32) : . "if" WS E(0) WS "then" WS E(0) WS "else" WS E(1) return 1 { "if" }
pub static FIRST_SET_E_ALT2: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(3)],
};
// StartS { EOF }
pub static FOLLOW_SET_START_S: TerminalSet = TerminalSet {
    id: 5,
    terminals: &[TerminalId(7)],
};
// StartS { "a", WS, "if" }
pub static FIRST_SET_START_S: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(1), TerminalId(0), TerminalId(3)],
};
// StartS : . WS start:S WS { "a", "if", WS }
pub static FIRST_SET_START_S_ALT0: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[TerminalId(1), TerminalId(3), TerminalId(0)],
};
// StartE { EOF }
pub static FOLLOW_SET_START_E: TerminalSet = TerminalSet {
    id: 5,
    terminals: &[TerminalId(7)],
};
// StartE { "a", WS, "if" }
pub static FIRST_SET_START_E: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(1), TerminalId(0), TerminalId(3)],
};
// StartE : . WS start:E(0) WS { "a", "if", WS }
pub static FIRST_SET_START_E_ALT0: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[TerminalId(1), TerminalId(3), TerminalId(0)],
};
