// @generated by iguana. Do not edit manually.

use iguana_runtime::{
    grammar::{Grammar, Nonterminal, Slot, Terminal},
    ids::{NonterminalId, TerminalId},
    scanner::TerminalSet,
};
pub const S: NonterminalId = NonterminalId(0);
pub const E: NonterminalId = NonterminalId(1);
pub const START_S: NonterminalId = NonterminalId(2);
pub const START_E: NonterminalId = NonterminalId(3);
pub struct AmbiguousExprGrammar;
impl Grammar for AmbiguousExprGrammar {
    const NONTERMINALS: &'static [Nonterminal] = &[
        Nonterminal {
            name: "S",
            display_name: "S",
        },
        Nonterminal {
            name: "E",
            display_name: "E",
        },
        Nonterminal {
            name: "StartS",
            display_name: "S",
        },
        Nonterminal {
            name: "StartE",
            display_name: "E",
        },
    ];
    const DISPLAY_ORDER: &'static [&'static str] = &["S", "E"];
    const TERMINALS: &'static [Terminal] = &[
        Terminal { name: "WS" },
        Terminal { name: "\".\"" },
        Terminal { name: "\"f\"" },
        Terminal { name: "\"*\"" },
        Terminal { name: "\"+\"" },
        Terminal { name: "\"-\"" },
        Terminal { name: "\"if\"" },
        Terminal { name: "\"then\"" },
        Terminal { name: "\"else\"" },
        Terminal { name: "\";\"" },
        Terminal { name: "\"(\"" },
        Terminal { name: "\")\"" },
        Terminal { name: "\"a\"" },
        Terminal { name: "Epsilon" },
        Terminal { name: "EOF" },
    ];
    const SLOTS: &'static [Slot] = &[
        Slot {
            display_name: "S : . E",
        },
        Slot {
            display_name: "S : E.",
        },
        Slot {
            display_name: "E : . E WS \".\" WS \"f\"",
        },
        Slot {
            display_name: "E : E . WS \".\" WS \"f\"",
        },
        Slot {
            display_name: "E : E WS . \".\" WS \"f\"",
        },
        Slot {
            display_name: "E : E WS \".\" . WS \"f\"",
        },
        Slot {
            display_name: "E : E WS \".\" WS . \"f\"",
        },
        Slot {
            display_name: "E : E WS \".\" WS \"f\".",
        },
        Slot {
            display_name: "E : . E WS E",
        },
        Slot {
            display_name: "E : E . WS E",
        },
        Slot {
            display_name: "E : E WS . E",
        },
        Slot {
            display_name: "E : E WS E.",
        },
        Slot {
            display_name: "E : . E WS \"*\" WS E",
        },
        Slot {
            display_name: "E : E . WS \"*\" WS E",
        },
        Slot {
            display_name: "E : E WS . \"*\" WS E",
        },
        Slot {
            display_name: "E : E WS \"*\" . WS E",
        },
        Slot {
            display_name: "E : E WS \"*\" WS . E",
        },
        Slot {
            display_name: "E : E WS \"*\" WS E.",
        },
        Slot {
            display_name: "E : . E WS \"+\" WS E",
        },
        Slot {
            display_name: "E : E . WS \"+\" WS E",
        },
        Slot {
            display_name: "E : E WS . \"+\" WS E",
        },
        Slot {
            display_name: "E : E WS \"+\" . WS E",
        },
        Slot {
            display_name: "E : E WS \"+\" WS . E",
        },
        Slot {
            display_name: "E : E WS \"+\" WS E.",
        },
        Slot {
            display_name: "E : . E WS \"-\" WS E",
        },
        Slot {
            display_name: "E : E . WS \"-\" WS E",
        },
        Slot {
            display_name: "E : E WS . \"-\" WS E",
        },
        Slot {
            display_name: "E : E WS \"-\" . WS E",
        },
        Slot {
            display_name: "E : E WS \"-\" WS . E",
        },
        Slot {
            display_name: "E : E WS \"-\" WS E.",
        },
        Slot {
            display_name: "E : . \"-\" WS E",
        },
        Slot {
            display_name: "E : \"-\" . WS E",
        },
        Slot {
            display_name: "E : \"-\" WS . E",
        },
        Slot {
            display_name: "E : \"-\" WS E.",
        },
        Slot {
            display_name: "E : . \"if\" WS E WS \"then\" WS E WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" . WS E WS \"then\" WS E WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS . E WS \"then\" WS E WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E . WS \"then\" WS E WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS . \"then\" WS E WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS \"then\" . WS E WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS \"then\" WS . E WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS \"then\" WS E . WS \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS \"then\" WS E WS . \"else\" WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS \"then\" WS E WS \"else\" . WS E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS \"then\" WS E WS \"else\" WS . E",
        },
        Slot {
            display_name: "E : \"if\" WS E WS \"then\" WS E WS \"else\" WS E.",
        },
        Slot {
            display_name: "E : . E WS \";\" WS E",
        },
        Slot {
            display_name: "E : E . WS \";\" WS E",
        },
        Slot {
            display_name: "E : E WS . \";\" WS E",
        },
        Slot {
            display_name: "E : E WS \";\" . WS E",
        },
        Slot {
            display_name: "E : E WS \";\" WS . E",
        },
        Slot {
            display_name: "E : E WS \";\" WS E.",
        },
        Slot {
            display_name: "E : . \"(\" WS E WS \")\"",
        },
        Slot {
            display_name: "E : \"(\" . WS E WS \")\"",
        },
        Slot {
            display_name: "E : \"(\" WS . E WS \")\"",
        },
        Slot {
            display_name: "E : \"(\" WS E . WS \")\"",
        },
        Slot {
            display_name: "E : \"(\" WS E WS . \")\"",
        },
        Slot {
            display_name: "E : \"(\" WS E WS \")\".",
        },
        Slot {
            display_name: "E : . \"a\"",
        },
        Slot {
            display_name: "E : \"a\".",
        },
        Slot {
            display_name: "S : . WS start:S WS",
        },
        Slot {
            display_name: "S : WS . start:S WS",
        },
        Slot {
            display_name: "S : WS start:S . WS",
        },
        Slot {
            display_name: "S : WS start:S WS.",
        },
        Slot {
            display_name: "E : . WS start:E WS",
        },
        Slot {
            display_name: "E : WS . start:E WS",
        },
        Slot {
            display_name: "E : WS start:E . WS",
        },
        Slot {
            display_name: "E : WS start:E WS.",
        },
    ];
    const LAYOUT_NAME: Option<&'static str> = Some("WS");
    const LAYOUT_TERMINALS: &'static [TerminalId] = &[TerminalId(0)];
    fn nonterminal_id(name: &str) -> Option<NonterminalId> {
        match name {
            "S" => Some(S),
            "E" => Some(E),
            "StartS" => Some(START_S),
            "StartE" => Some(START_E),
            _ => None,
        }
    }
}
// S { WS, EOF }
pub static FOLLOW_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(0), TerminalId(14)],
};
// S { "(", "if", "a", "-" }
pub static FIRST_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// S : . E { "(", "if", "a", "-" }
pub static FIRST_SET_S_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E { ".", "if", "a", "*", ";", EOF, "-", "+", "(", "else", ")", "then", WS }
pub static FOLLOW_SET_E: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[
        TerminalId(1),
        TerminalId(6),
        TerminalId(12),
        TerminalId(3),
        TerminalId(9),
        TerminalId(14),
        TerminalId(5),
        TerminalId(4),
        TerminalId(10),
        TerminalId(8),
        TerminalId(11),
        TerminalId(7),
        TerminalId(0),
    ],
};
// E { "(", "if", "a", "-" }
pub static FIRST_SET_E: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E : . E WS "." WS "f" { "(", "if", "a", "-" }
pub static FIRST_SET_E_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E : . E WS E { "(", "if", "a", "-" }
pub static FIRST_SET_E_ALT1: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E : . E WS "*" WS E { "(", "if", "a", "-" }
pub static FIRST_SET_E_ALT2: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E : . E WS "+" WS E { "(", "if", "a", "-" }
pub static FIRST_SET_E_ALT3: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E : . E WS "-" WS E { "(", "if", "a", "-" }
pub static FIRST_SET_E_ALT4: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E : . "-" WS E { "-" }
pub static FIRST_SET_E_ALT5: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(5)],
};
// E : . "if" WS E WS "then" WS E WS "else" WS E { "if" }
pub static FIRST_SET_E_ALT6: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(6)],
};
// E : . E WS ";" WS E { "(", "if", "a", "-" }
pub static FIRST_SET_E_ALT7: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(10), TerminalId(6), TerminalId(12), TerminalId(5)],
};
// E : . "(" WS E WS ")" { "(" }
pub static FIRST_SET_E_ALT8: TerminalSet = TerminalSet {
    id: 5,
    terminals: &[TerminalId(10)],
};
// E : . "a" { "a" }
pub static FIRST_SET_E_ALT9: TerminalSet = TerminalSet {
    id: 6,
    terminals: &[TerminalId(12)],
};
// StartS { EOF }
pub static FOLLOW_SET_START_S: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(14)],
};
// StartS { WS, "(", "if", "a", "-" }
pub static FIRST_SET_START_S: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[
        TerminalId(0),
        TerminalId(10),
        TerminalId(6),
        TerminalId(12),
        TerminalId(5),
    ],
};
// StartS : . WS start:S WS { "-", "(", "if", "a", WS }
pub static FIRST_SET_START_S_ALT0: TerminalSet = TerminalSet {
    id: 8,
    terminals: &[
        TerminalId(5),
        TerminalId(10),
        TerminalId(6),
        TerminalId(12),
        TerminalId(0),
    ],
};
// StartE { EOF }
pub static FOLLOW_SET_START_E: TerminalSet = TerminalSet {
    id: 7,
    terminals: &[TerminalId(14)],
};
// StartE { WS, "(", "if", "a", "-" }
pub static FIRST_SET_START_E: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[
        TerminalId(0),
        TerminalId(10),
        TerminalId(6),
        TerminalId(12),
        TerminalId(5),
    ],
};
// StartE : . WS start:E WS { "-", "(", "if", "a", WS }
pub static FIRST_SET_START_E_ALT0: TerminalSet = TerminalSet {
    id: 8,
    terminals: &[
        TerminalId(5),
        TerminalId(10),
        TerminalId(6),
        TerminalId(12),
        TerminalId(0),
    ],
};
