// @generated by iguana. Do not edit manually.

use crate::types::{Nonterminal, Slot, Terminal};
use iguana_runtime::ids::{NonterminalId, TerminalId};
use iguana_runtime::scanner::TerminalSet;
pub const NONTERMINALS: [Nonterminal; 2] = [
    Nonterminal {
        name: "S",
        display: "S",
        derived: false,
    },
    Nonterminal {
        name: "StartS",
        display: "S",
        derived: true,
    },
];
// User-declared nonterminals in `.iggy` source order. Used by `--list-nonterminals`.
pub const NONTERMINAL_DISPLAY_ORDER: [&str; 1] = ["S"];
pub const S: NonterminalId = NonterminalId(0);
pub const START_S: NonterminalId = NonterminalId(1);
pub fn nonterminal_id(name: &str) -> Option<NonterminalId> {
    match name {
        "S" => Some(S),
        "StartS" => Some(START_S),
        _ => None,
    }
}
pub const TERMINALS: [Terminal; 6] = [
    Terminal { name: "Id" },
    Terminal { name: "Excl" },
    Terminal { name: "Semi" },
    Terminal { name: "WS" },
    Terminal { name: "Epsilon" },
    Terminal { name: "EOF" },
];
pub const SLOTS: [Slot; 6] = [
    Slot {
        display_name: "S : . Id !>> Excl !>>> Semi",
    },
    Slot {
        display_name: "S : Id !>> Excl !>>> Semi.",
    },
    Slot {
        display_name: "S : . WS start:S WS",
    },
    Slot {
        display_name: "S : WS . start:S WS",
    },
    Slot {
        display_name: "S : WS start:S . WS",
    },
    Slot {
        display_name: "S : WS start:S WS.",
    },
];
// S { WS, EOF }
pub static FOLLOW_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(3), TerminalId(5)],
};
// S { Id }
pub static FIRST_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(0)],
};
// S : . Id !>> Excl !>>> Semi { Id }
pub static FIRST_SET_S_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(0)],
};
// S : . Id !>> Excl !>>> Semi !>> { Excl }
pub static FOLLOW_RESTRICTION_S_ALT0_POS0: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[TerminalId(1)],
};
// S : . Id !>> Excl !>>> Semi !>>> { Semi }
pub static LAYOUT_AWARE_FOLLOW_RESTRICTION_S_ALT0_POS0: TerminalSet = TerminalSet {
    id: 3,
    terminals: &[TerminalId(2)],
};
// StartS { EOF }
pub static FOLLOW_SET_START_S: TerminalSet = TerminalSet {
    id: 4,
    terminals: &[TerminalId(5)],
};
// StartS { WS, Id }
pub static FIRST_SET_START_S: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(3), TerminalId(0)],
};
// StartS : . WS start:S WS { Id, WS }
pub static FIRST_SET_START_S_ALT0: TerminalSet = TerminalSet {
    id: 5,
    terminals: &[TerminalId(0), TerminalId(3)],
};
