[package]
name = "iguana-lsp"
version.workspace = true
edition = "2024"
license = "GPL-3.0-or-later"
description = "The language server for iggy grammars"
repository.workspace = true
readme = "README.md"
keywords = ["lsp", "language-server", "grammar", "iggy", "parser"]
categories = ["development-tools"]

[lints]
workspace = true

[[bin]]
name = "iguana-lsp"
path = "src/main.rs"
test = false

[dependencies]
by_address = "1.2.1"
iggy.workspace = true
iguana-compiler.workspace = true
iguana-runtime.workspace = true
rustc-hash = "2.1.1"
lsp-server.workspace = true
serde.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
