// @generated by iguana. Do not edit manually.
use std::{
    fs::File, io::{self, BufWriter, Write},
    path::PathBuf,
};
use clap::Parser as ClapParser;
use iguana_runtime::{
    input::Input, parser::{ParseResult, ParseErrorKind, Parser},
    visualization::{
        dot::write_svg, gss::{build_gss_dot_graph, render_gss},
        sppf::{build_sppf_graph, write_sppf_dot},
    },
};
#[cfg(feature = "profile")]
use pprof::ProfilerGuardBuilder;
use except_terminal::{
    parse_tree::{ExceptTerminalParseTreeBuilder, create_parse_tree, to_json, to_sexpr},
    grammar_data::{nonterminal_id, NONTERMINALS, SLOTS, TERMINALS},
    parser::ExceptTerminalParser, types::{Nonterminal, Slot, Terminal},
};
#[cfg(feature = "debug-trace")]
use iguana_runtime::trace::TraceEvent;
#[derive(Clone, Copy, Default, clap::ValueEnum)]
enum TraceFormat {
    #[default]
    Text,
    Json,
}
#[derive(Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
enum VisTarget {
    Sppf,
    Gss,
}
#[derive(ClapParser)]
#[command(name = "parser")]
#[command(about = "Parse a file and generate visualization")]
#[command(arg_required_else_help = true)]
struct Cli {
    /// Input file to parse (required unless --list-nonterminals is used)
    file: Option<PathBuf>,
    /// The nonterminal to start parsing from (required unless --list-nonterminals is used)
    #[arg(long = "start")]
    start_nonterminal: Option<String>,
    /// List simple nonterminals (one per line) and exit
    #[arg(long)]
    list_nonterminals: bool,
    /// Write symbol table (all nonterminals) as JSON to the specified file
    #[arg(long, value_name = "FILE")]
    write_symbols: Option<PathBuf>,
    /// Enable trace output (writes to stdout or specified file)
    #[arg(long, value_name = "FILE")]
    trace: Option<Option<PathBuf>>,
    /// Output format for trace (text or json)
    #[arg(long, value_enum, default_value_t = TraceFormat::Text, requires = "trace")]
    format: TraceFormat,
    /// Generate visualization as SVG (sppf or gss)
    #[arg(long, value_enum)]
    vis: Option<VisTarget>,
    /// Write SPPF as JSON to the specified file
    #[arg(long, value_name = "FILE")]
    write_sppf: Option<PathBuf>,
    /// Write GSS graph as JSON for visualization (nodes with labels + edges).
    /// Used by Terrarium for Cytoscape.js graph rendering.
    #[arg(long, value_name = "FILE")]
    write_gss: Option<PathBuf>,
    /// Write GSS nodes as JSON for trace replay (normalized with IDs).
    /// Used by Terrarium debugger to resolve GssNodeId to (nonterminal, input_index).
    #[arg(long, value_name = "FILE")]
    write_gss_nodes: Option<PathBuf>,
    /// Write parse tree as JSON for visualization.
    /// Used by Terrarium for parse tree rendering.
    #[arg(long, value_name = "FILE")]
    write_parse_tree: Option<PathBuf>,
    /// Profile the parser by running it N times in a loop under a
    /// sampling profiler, then write a flamegraph SVG.
    /// Requires the "profile" feature: cargo build --features profile
    #[arg(long, value_name = "N")]
    profile: Option<u32>,
    /// Output path for the flamegraph SVG (used with --profile).
    #[arg(long, value_name = "FILE", default_value = "flamegraph.svg")]
    profile_output: PathBuf,
    /// Write parser stats (counters + histograms) as JSON.
    /// Requires the "instrument" feature.
    #[arg(long, value_name = "FILE")]
    write_stats: Option<PathBuf>,
    /// Write parse + tree construction timings as JSON.
    #[arg(long, value_name = "FILE")]
    write_timings: Option<PathBuf>,
}
#[cfg(feature = "dhat-heap")]
#[global_allocator]
static ALLOC: dhat::Alloc = dhat::Alloc;
fn main() -> Result<(), io::Error> {
    #[cfg(feature = "dhat-heap")]
    let _profiler = dhat::Profiler::new_heap();
    let cli = Cli::parse();
    if cli.list_nonterminals {
        for nt in NONTERMINALS.iter() {
            if !nt.is_ebnf() && !nt.is_start() {
                println!("{}", nt.name);
            }
        }
        return Ok(());
    }
    if let Some(ref path) = cli.write_symbols {
        let nonterminals: Vec<&str> = NONTERMINALS.iter().map(|nt| nt.display).collect();
        let terminals: Vec<&str> = TERMINALS.iter().map(|t| t.name).collect();
        let slots: Vec<&str> = SLOTS.iter().map(|s| s.display_name).collect();
        let symbols = serde_json::json!(
            { "nonterminals" : nonterminals, "terminals" : terminals, "slots" : slots }
        );
        let file = File::create(path)?;
        let mut writer = BufWriter::new(file);
        writeln!(writer, "{}", serde_json::to_string_pretty(& symbols).unwrap())?;
        return Ok(());
    }
    let file = cli
        .file
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidInput,
                "Input file is required for parsing",
            )
        })?;
    let start_nonterminal_name = cli
        .start_nonterminal
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidInput,
                "--start is required for parsing",
            )
        })?;
    #[cfg(not(feature = "debug-trace"))]
    if cli.trace.is_some() {
        eprintln!(
            "Warning: --trace flag ignored. Recompile with `--features debug-trace` to enable tracing."
        );
    }
    let input = Input::try_from(file.as_path())?;
    let start_nonterminal_id = nonterminal_id(&start_nonterminal_name)
        .ok_or_else(|| io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("Unknown nonterminal: '{}'", start_nonterminal_name),
        ))?;
    #[cfg(feature = "profile")]
    if let Some(iterations) = cli.profile {
        let parse_tree_builder = ExceptTerminalParseTreeBuilder;
        let guard = ProfilerGuardBuilder::default().frequency(999).build().unwrap();
        for _ in 0..iterations {
            let mut parser = ExceptTerminalParser::new(&input, start_nonterminal_id);
            let result = parser.run();
            if let ParseResult::Success(success) = result {
                let _ = create_parse_tree(
                    success.sppf_node_id,
                    start_nonterminal_id,
                    &parser,
                    &parse_tree_builder,
                );
            }
        }
        let report = guard.report().build().unwrap();
        let file = File::create(&cli.profile_output)?;
        report.flamegraph(&file).unwrap();
        eprintln!("Flamegraph written to {}", cli.profile_output.display());
        return Ok(());
    }
    #[cfg(not(feature = "profile"))]
    if cli.profile.is_some() {
        eprintln!(
            "Warning: --profile flag ignored. Recompile with `--features profile` to enable profiling."
        );
    }
    let mut parser = ExceptTerminalParser::new(&input, start_nonterminal_id);
    #[cfg(feature = "debug-trace")]
    if cli.trace.is_some() {
        parser.trace_events = Some(vec![]);
    }
    let parse_tree_builder = ExceptTerminalParseTreeBuilder;
    let result = parser.run();
    #[cfg(feature = "debug-trace")]
    if let Some(ref trace_events) = parser.trace_events {
        write_trace_events(trace_events, &parser, &cli.trace, cli.format)?;
    }
    match result {
        ParseResult::Success(parse_success) => {
            let node_id = parse_success.sppf_node_id;
            if let Some(ref path) = cli.write_sppf {
                let sppf = build_sppf_graph(&parser, node_id);
                let file = File::create(path)?;
                let mut writer = BufWriter::new(file);
                writeln!(writer, "{}", serde_json::to_string(& sppf).unwrap())?;
            }
            if let Some(ref path) = cli.write_gss {
                let gss = build_gss_dot_graph(&parser);
                let file = File::create(path)?;
                let mut writer = BufWriter::new(file);
                writeln!(writer, "{}", serde_json::to_string(& gss).unwrap())?;
            }
            if let Some(ref path) = cli.write_gss_nodes {
                let gss_nodes: Vec<_> = parser.gss_nodes().collect();
                let file = File::create(path)?;
                let mut writer = BufWriter::new(file);
                writeln!(writer, "{}", serde_json::to_string(& gss_nodes).unwrap())?;
            }
            let tc_start = std::time::Instant::now();
            let parse_tree_opt = if cli.write_parse_tree.is_some()
                || cli.write_timings.is_some()
                || (cli.write_sppf.is_none() && cli.write_gss.is_none()
                    && cli.vis.is_none() && cli.trace.is_none())
            {
                Some(
                    create_parse_tree(
                        node_id,
                        start_nonterminal_id,
                        &parser,
                        &parse_tree_builder,
                    ),
                )
            } else {
                None
            };
            let tree_construction_ms = parse_tree_opt
                .as_ref()
                .map(|_| tc_start.elapsed().as_millis());
            if let (Some(path), Some(parse_tree)) = (
                cli.write_parse_tree.as_ref(),
                parse_tree_opt.as_ref(),
            ) {
                let json = to_json(parse_tree.as_parse_tree_ref());
                let file = File::create(path)?;
                let mut writer = BufWriter::new(file);
                writeln!(writer, "{}", json)?;
            }
            if let Some(ref path) = cli.write_timings {
                let timings = serde_json::json!(
                    { "parse_ms" : parse_success.duration.as_millis(),
                    "tree_construction_ms" : tree_construction_ms, }
                );
                let file = File::create(path)?;
                let mut writer = BufWriter::new(file);
                writeln!(writer, "{}", serde_json::to_string(& timings).unwrap())?;
            }
            match cli.vis {
                Some(VisTarget::Gss) => {
                    let path = std::path::Path::new("gss.dot");
                    render_gss(&parser, path)?;
                    write_svg(path)?;
                    println!("GSS visualization generated: gss.svg");
                }
                Some(VisTarget::Sppf) => {
                    let path = std::path::Path::new("sppf.dot");
                    write_sppf_dot(&parser, node_id, path)?;
                    write_svg(path)?;
                    println!("SPPF visualization generated: sppf.svg");
                }
                None => {}
            }
            println!("Parse success in {}ms", parse_success.duration.as_millis());
            if cli.write_sppf.is_none() && cli.write_gss.is_none() && cli.vis.is_none()
                && cli.trace.is_none()
            {
                if let Some(ref parse_tree) = parse_tree_opt {
                    println!("{}", to_sexpr(parse_tree.as_parse_tree_ref()));
                }
            }
        }
        ParseResult::Failure(error) => {
            let (line, column) = input.line_column(error.input_index);
            match &error.kind {
                ParseErrorKind::UnexpectedToken { expected } => {
                    let names: Vec<_> = expected
                        .iter()
                        .map(|t| ExceptTerminalParser::terminal_name(*t))
                        .collect();
                    println!(
                        "Parse failed at line {line}, column {column}: expected {}",
                        names.join(", ")
                    );
                }
                ParseErrorKind::ExcludedMatch { excluded_by } => {
                    let names: Vec<_> = excluded_by
                        .iter()
                        .map(|t| ExceptTerminalParser::terminal_name(*t))
                        .collect();
                    println!(
                        "Parse failed at line {line}, column {column}: matched token is excluded by {}",
                        names.join(", ")
                    );
                }
                ParseErrorKind::ForbiddenFollow { forbidden } => {
                    let names: Vec<_> = forbidden
                        .iter()
                        .map(|t| ExceptTerminalParser::terminal_name(*t))
                        .collect();
                    println!(
                        "Parse failed at line {line}, column {column}: forbidden follow {}",
                        names.join(", ")
                    );
                }
            }
        }
    }
    #[cfg(feature = "instrument")]
    {
        let stats = parser.record_stats();
        if let Some(ref path) = cli.write_stats {
            let file = File::create(path)?;
            let mut writer = BufWriter::new(file);
            writeln!(writer, "{}", serde_json::to_string(& stats).unwrap())?;
        } else {
            eprintln!("{}", stats);
        }
    }
    #[cfg(not(feature = "instrument"))]
    if cli.write_stats.is_some() {
        eprintln!(
            "Warning: --write-stats flag ignored. Recompile with `--features instrument` to enable stats."
        );
    }
    Ok(())
}
#[cfg(feature = "debug-trace")]
fn write_trace_events<'i>(
    trace_events: &[TraceEvent],
    parser: &impl Parser<'i>,
    trace_option: &Option<Option<PathBuf>>,
    format: TraceFormat,
) -> io::Result<()> {
    match trace_option {
        Some(Some(path)) => {
            let file = File::create(path)?;
            let mut writer = BufWriter::new(file);
            match format {
                TraceFormat::Text => {
                    for event in trace_events {
                        writeln!(writer, "{}", event.message(parser))?;
                    }
                }
                TraceFormat::Json => {
                    writeln!(
                        writer, "{}", serde_json::to_string(trace_events).unwrap()
                    )?;
                }
            }
        }
        Some(None) => {
            match format {
                TraceFormat::Text => {
                    for event in trace_events {
                        println!("{}", event.message(parser));
                    }
                }
                TraceFormat::Json => {
                    println!("{}", serde_json::to_string(trace_events).unwrap());
                }
            }
        }
        None => {}
    }
    Ok(())
}

