[package]
name = "iguana"
version = "0.1.0"
edition = "2024"

[features]
debug-trace = ["iguana-runtime/debug-trace", "iggy/debug-trace"]

[lib]
path = "src/lib.rs"

[dependencies]
iguana-runtime.workspace = true
iggy.workspace = true
clap.workspace = true
proc-macro2.workspace = true
quote.workspace = true
rustc-hash.workspace = true
serde.workspace = true
specta.workspace = true
syn = { version = "2.0.108", features = ["full", "parsing"] }
indexmap = "2.12.1"
itertools = "0.14.0"
insta = "1.44.3"
prettyplease = "0.2.37"
