// @generated by iguana. Do not edit manually.

use iguana_runtime::{
    grammar::{Grammar, Nonterminal, Slot, Terminal},
    ids::{NonterminalId, TerminalId},
    scanner::TerminalSet,
};
pub const S: NonterminalId = NonterminalId(0);
pub const START_S: NonterminalId = NonterminalId(1);
pub struct ExceptRegexReferenceGrammar;
impl Grammar for ExceptRegexReferenceGrammar {
    const NAME: &'static str = "ExceptRegexReference";
    const NONTERMINALS: &'static [Nonterminal] = &[
        Nonterminal {
            name: "S",
            display_name: "S",
        },
        Nonterminal {
            name: "StartS",
            display_name: "S",
        },
    ];
    const DISPLAY_ORDER: &'static [&'static str] = &["S"];
    const TERMINALS: &'static [Terminal] = &[
        Terminal {
            name: "TypeIdentifier",
        },
        Terminal { name: "Identifier" },
        Terminal { name: "Keyword" },
        Terminal { name: "Var" },
        Terminal { name: "Epsilon" },
        Terminal { name: "EOF" },
    ];
    const SLOTS: &'static [Slot] = &[
        Slot {
            display_name: "S : . TypeIdentifier",
        },
        Slot {
            display_name: "S : TypeIdentifier.",
        },
        Slot {
            display_name: "S : . start:S",
        },
        Slot {
            display_name: "S : start:S.",
        },
    ];
    const LAYOUT_NAME: Option<&'static str> = None;
    const LAYOUT_TERMINALS: &'static [TerminalId] = &[];
    // A failed terminal match refers to a static terminal set like every other failure, so the
    // error reporting path needs to reach a terminal set from a terminal id. This slice, indexed
    // by terminal id, serves only that.
    const SINGLE_TERMINAL_SETS: &'static [TerminalSet] = &[
        TerminalSet {
            id: 3,
            terminals: &[TerminalId(0)],
        },
        TerminalSet {
            id: 4,
            terminals: &[TerminalId(1)],
        },
        TerminalSet {
            id: 5,
            terminals: &[TerminalId(2)],
        },
        TerminalSet {
            id: 6,
            terminals: &[TerminalId(3)],
        },
        TerminalSet {
            id: 7,
            terminals: &[TerminalId(4)],
        },
        TerminalSet {
            id: 8,
            terminals: &[TerminalId(5)],
        },
    ];
    fn nonterminal_id(name: &str) -> Option<NonterminalId> {
        match name {
            "S" => Some(S),
            "StartS" => Some(START_S),
            _ => None,
        }
    }
}
// S { EOF }
pub static FOLLOW_SET_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(5)],
};
// S : . TypeIdentifier { TypeIdentifier }
pub static FIRST_SET_S_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(0)],
};
// StartS { EOF }
pub static FOLLOW_SET_START_S: TerminalSet = TerminalSet {
    id: 0,
    terminals: &[TerminalId(5)],
};
// StartS : . start:S { TypeIdentifier }
pub static FIRST_SET_START_S_ALT0: TerminalSet = TerminalSet {
    id: 1,
    terminals: &[TerminalId(0)],
};
// S { TypeIdentifier }
pub static FIRST_SET_S: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[TerminalId(0)],
};
// StartS { TypeIdentifier }
pub static FIRST_SET_START_S: TerminalSet = TerminalSet {
    id: 2,
    terminals: &[TerminalId(0)],
};
