// @generated by iguana. Do not edit manually.
use iguana_runtime::ids::{NonterminalId, TerminalId};
use crate::types::{EbnfKind, Nonterminal, Slot, Terminal};
use phf::phf_map;
pub const NONTERMINALS: [Nonterminal; 3] = [
    Nonterminal {
        name: "S",
        display: "S",
        kind: None,
    },
    Nonterminal {
        name: "Element",
        display: "Element",
        kind: None,
    },
    Nonterminal {
        name: "S_Plus_0",
        display: "Element+",
        kind: Some(EbnfKind::Plus),
    },
];
pub static NONTERMINAL_IDS: phf::Map<&'static str, NonterminalId> = phf_map! {
    "S" => NonterminalId(0), "Element" => NonterminalId(1), "S_Plus_0" =>
    NonterminalId(2)
};
pub const TERMINALS: [Terminal; 6] = [
    Terminal { name: "Num" },
    Terminal { name: "Alpha" },
    Terminal { name: "Id" },
    Terminal { name: "WS" },
    Terminal { name: "Epsilon" },
    Terminal { name: "EOF" },
];
pub const SLOTS: [Slot; 12] = [
    Slot {
        display_name: "S : . Element+",
    },
    Slot {
        display_name: "S : Element+.",
    },
    Slot {
        display_name: "Element : . Num",
    },
    Slot {
        display_name: "Element : Num.",
    },
    Slot {
        display_name: "Element : . Id",
    },
    Slot {
        display_name: "Element : Id.",
    },
    Slot {
        display_name: "Element+ : . Element+ WS Element",
    },
    Slot {
        display_name: "Element+ : Element+ . WS Element",
    },
    Slot {
        display_name: "Element+ : Element+ WS . Element",
    },
    Slot {
        display_name: "Element+ : Element+ WS Element.",
    },
    Slot {
        display_name: "Element+ : . Element",
    },
    Slot {
        display_name: "Element+ : Element.",
    },
];
//S { EOF }
pub static FOLLOW_SET_S: &[TerminalId] = &[TerminalId(5)];
//S { Num, Id }
pub static FIRST_SET_S: &[TerminalId] = &[TerminalId(0), TerminalId(2)];
//S : . S_Plus_0 { Num, Id }
pub static PREDICTION_SET_S_ALT0: &[TerminalId] = &[TerminalId(0), TerminalId(2)];
//Element { WS, Num, Id, EOF }
pub static FOLLOW_SET_ELEMENT: &[TerminalId] = &[
    TerminalId(3),
    TerminalId(0),
    TerminalId(2),
    TerminalId(5),
];
//Element { Num, Id }
pub static FIRST_SET_ELEMENT: &[TerminalId] = &[TerminalId(0), TerminalId(2)];
//Element : . Num { Num }
pub static PREDICTION_SET_ELEMENT_ALT0: &[TerminalId] = &[TerminalId(0)];
//Element : . Id { Id }
pub static PREDICTION_SET_ELEMENT_ALT1: &[TerminalId] = &[TerminalId(2)];
//S_Plus_0 { EOF, Num, Id, WS }
pub static FOLLOW_SET_S_PLUS_0: &[TerminalId] = &[
    TerminalId(5),
    TerminalId(0),
    TerminalId(2),
    TerminalId(3),
];
//S_Plus_0 { Num, Id }
pub static FIRST_SET_S_PLUS_0: &[TerminalId] = &[TerminalId(0), TerminalId(2)];
//S_Plus_0 : . S_Plus_0 WS Element { Num, Id }
pub static PREDICTION_SET_S_PLUS_0_ALT0: &[TerminalId] = &[TerminalId(0), TerminalId(2)];
//S_Plus_0 : . Element { Num, Id }
pub static PREDICTION_SET_S_PLUS_0_ALT1: &[TerminalId] = &[TerminalId(0), TerminalId(2)];

